# imports

In [1]:
import sys
sys.path.append(r'\\192.168.10.106\imdea\DataDriven_UT_AlbertoVicente\10_code\UTvsXCT-preprocessing')
from preprocess_tools import onlypores , datasetmaker, io, aligner, register, reslicer
import numpy as np
from dbtools import dbtools as db
from dbtools import load as load
import pandas as pd
from pathlib import Path
import ast

# Database conection

In [2]:
try:
    conn = db.connect()
    print("Connected to the database")
except Exception as error:
    print(error)

Connected to the database

# Select measurements to create the datasets

## measurement type

In [3]:
measurementtypes_table = db.get_data_metadata('measurementtypes')

measurementtypes_table

,id_measurementtype,name_measurementtype,description_measurementtype,technique_measurementtype,equipment_measurementtype,transducer_name_measurementtype,transducer_nominal_freq_measurementtype,transducer_diameter_measurementtype,transducer_focal_length_measurementtype,z_resolution_measurementtype,...,binning_measurementtype,projections_measurementtype,target_measurementtype,filter_measurementtype,Detector_measurementtype,scaling_measurementtype,power_measurementtype,DAC_measurementtype,lens_measurementtype,lens_focal_length_measurementtype
0,5,Monoelement Ultrasound Pulse Echo 1,None,Ultrasound Monoelement Pulse Echo nominal,TRITON 1000P nominal,Technisonic ISL-0503-HR nominal,5 MHz,9.525 mm,76.2 mm,0.02232141 mm,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,6,XCT 1,None,X-Ray Computed Tomography nominal,ZEISS Xradia Versa 620 nominal,NaN,NaN,NaN,NaN,NaN,...,1 cardinal,3738 cardinal,wolframio nominal,LE1 nominal,Flat Panel nominal,"[-1.700072,1.841701] float array",4.5 W,NaN,NaN,NaN
2,7,Monoelement Ultrasound Pulse Echo Airbus DAC,None,Ultrasound Monoelement Pulse Echo nominal,TRITON 1000P nominal,Technisonic ISL-0503-HR nominal,5 MHz,9.525 mm,76.2 mm,0.02232141 mm,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[10.1,4.33],[12.1,6.18],[19.7,10.38],[26.7,15...",NaN,NaN
3,8,Monoelement Ultrasound Pulse Echo Low Resolution,None,Ultrasound Monoelement Pulse Echo nominal,TRITON 1000P nominal,Technisonic ISL-0503-HR nominal,5 MHz,9.525 mm,76.2 mm,0.05940588 mm,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,9,Placeholder Measurement Type,A generic placeholder for a measurement techni...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,10,Monoelement Ultrasound Pulse Echo Airbus DAC L...,None,Ultrasound Monoelement Pulse Echo nominal,TRITON 1000P nominal,Technisonic ISL-0503-HR nominal,5 MHz,9.525 mm,42 mm,0.02232141 mm,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[10.1,4.33],[12.1,6.18],[19.7,10.38],[26.7,15...",True bool,"38,1 mm"

In [4]:
ut_type = 10

xct_type = 6

## Selecting UT measurements

In [5]:
ut_measurements_table = db.get_data_metadata('measurements')

In [6]:
ut_measurements_table = ut_measurements_table[ut_measurements_table['measurementtype_id_measurement'] == ut_type]

ut_measurements_table

,id_measurement,file_path_measurement,parent_measurement_id_measurement,measurementtype_id_measurement,height_measurement,width_measurement,depth_measurement,dtype_measurement,file_type_measurement,aligned_measurement,equalized_measurement,axes_order_measurement,transformations_measurement,signal_type_measurement
129,260,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,NaN,10,448 cardinal,174 cardinal,316 cardinal,uint8 nominal,.tif nominal,NaN,NaN,"['z', 'y', 'x'] list",NaN,RF nominal
130,261,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,NaN,10,447 cardinal,187 cardinal,320 cardinal,uint8 nominal,.tif nominal,NaN,NaN,"['z', 'y', 'x'] list",NaN,RF nominal
131,262,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,NaN,10,448 cardinal,187 cardinal,320 cardinal,uint8 nominal,.tif nominal,NaN,NaN,"['z', 'y', 'x'] list",NaN,RF nominal
132,294,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,262.0,10,448 cardinal,147 cardinal,63 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal
133,295,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,262.0,10,448 cardinal,148 cardinal,63 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,375,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,349.0,10,448 cardinal,145 cardinal,49 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal
208,376,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,349.0,10,448 cardinal,132 cardinal,49 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal
209,377,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,349.0,10,448 cardinal,131 cardinal,49 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal
210,378,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,349.0,10,448 cardinal,131 cardinal,50 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal
331,363,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,346.0,10,448 cardinal,132 cardinal,47 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal

## Selecting XCT measurements

In [7]:
xct_measurements_table = db.get_data_metadata('measurements')

In [8]:
xct_measurements_table = xct_measurements_table[xct_measurements_table['measurementtype_id_measurement'] == xct_type]

xct_measurements_table

,id_measurement,file_path_measurement,parent_measurement_id_measurement,measurementtype_id_measurement,height_measurement,width_measurement,depth_measurement,dtype_measurement,file_type_measurement,aligned_measurement,equalized_measurement,axes_order_measurement,transformations_measurement,signal_type_measurement
0,253,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,252.0,6,3411 cardinal,1908 cardinal,1117 cardinal,uint8 string,folder string,False bool,True bool,"['x', 'y', 'z'] list",Volume equalized with this parameters: Referen...,NaN
2,101,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,NaN,6,3737 cardinal,1770 cardinal,1015 cardinal,uint16 string,folder string,NaN,NaN,"['x', 'y', 'z'] list",NaN,NaN
3,102,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,101.0,6,3224 cardinal,1770 cardinal,1015 cardinal,uint8 string,folder string,False bool,True bool,"['x', 'y', 'z'] list",Volume equalized with this parameters:\r\n\r\n...,NaN
4,103,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,NaN,6,3735 cardinal,1734 cardinal,1003 cardinal,uint16 string,folder string,False bool,False bool,"['x', 'y', 'z'] list",NaN,NaN
5,104,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,103.0,6,3226 cardinal,1734 cardinal,1003 cardinal,uint8 string,folder string,False bool,True bool,"['x', 'y', 'z'] list",Volume equalized with this parameters: \r\n\r\...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
326,528,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,478.0,6,243 cardinal,3849 cardinal,1941 cardinal,uint8 string,tif string,True bool,True bool,"['z', 'y', 'x'] list","Frontwall aligned with axes, rotated 90 degree...",NaN
327,529,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,479.0,6,255 cardinal,3849 cardinal,1965 cardinal,uint8 string,tif string,True bool,True bool,"['z', 'y', 'x'] list","Frontwall aligned with axes, rotated 90 degree...",NaN
328,530,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,480.0,6,250 cardinal,3851 cardinal,1924 cardinal,uint8 string,tif string,True bool,True bool,"['z', 'y', 'x'] list","Frontwall aligned with axes, rotated 90 degree...",NaN
329,531,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,481.0,6,226 cardinal,3478 cardinal,1651 cardinal,uint8 string,tif string,True bool,True bool,"['z', 'y', 'x'] list","Frontwall aligned with axes, rotated 90 degree...",NaN
330,532,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,482.0,6,237 cardinal,3478 cardinal,1649 cardinal,uint8 string,tif string,True bool,True bool,"['z', 'y', 'x'] list","Frontwall aligned with axes, rotated 90 degree...",NaN

## Getting registered pairs

In [9]:
registrations_table = db.get_data_metadata('registrations')

registrations_table = registrations_table[registrations_table['reference_measurement_id_registration'].isin(ut_measurements_table['id_measurement'])]

registrations_table = registrations_table[registrations_table['registered_measurement_id_registration'].isin(xct_measurements_table['id_measurement'])]

registrations_table

,id_registration,reference_measurement_id_registration,registered_measurement_id_registration,registration_matrix_registration,description_registration,type_registration,axes_registration
28,76,312,483,"[[0.9997974126013454, 0.02012793470913604, -13...",None,"Alberto 2024 registration method, UTvsXCTPrepr...","['x', 'y'] list"
29,77,313,484,"[[0.9997960016298643, 0.02019789902282558, -13...",None,"Alberto 2024 registration method, UTvsXCTPrepr...","['x', 'y'] list"
30,78,314,485,"[[0.9997875053099681, 0.02061417536721595, -13...",None,"Alberto 2024 registration method, UTvsXCTPrepr...","['x', 'y'] list"
31,79,315,486,"[[0.9987765486568175, 0.049451045016016146, -1...",None,"Alberto 2024 registration method, UTvsXCTPrepr...","['x', 'y'] list"
32,84,297,491,"[[0.9999999999999999, -1.3857223320199514e-17,...",None,"Alberto 2024 registration method, UTvsXCTPrepr...","['x', 'y'] list"
...,...,...,...,...,...,...,...
91,155,359,235,"[[0.9996299363821078, 0.027202762519707893, -1...",None,"Alberto 2024 registration method, UTvsXCTPrepr...","['x', 'y'] list"
92,156,360,236,"[[0.999937150094625, -0.011211416531363972, -1...",None,"Alberto 2024 registration method, UTvsXCTPrepr...","['x', 'y'] list"
93,157,361,238,"[[0.9999970012629682, -0.0024489722479909457, ...",None,"Alberto 2024 registration method, UTvsXCTPrepr...","['x', 'y'] list"
94,158,362,239,"[[0.9997215484668069, 0.023597150911284333, -9...",None,"Alberto 2024 registration method, UTvsXCTPrepr...","['x', 'y'] list"
95,159,363,234,"[[0.9999855900633831, -0.005368395066226072, -...",None,"Alberto 2024 registration method, UTvsXCTPrepr...","['x', 'y'] list"

In [10]:
reference_measurements = []
registered_measurements = []
registration_ids = []

for index, row in registrations_table.iterrows():

    reference_id = row['reference_measurement_id_registration']
    registered_id = row['registered_measurement_id_registration']
    registration_id = row['id_registration']

    reference_measurements.append(ut_measurements_table[ut_measurements_table['id_measurement'] == reference_id].iloc[0])
    registered_measurements.append(xct_measurements_table[xct_measurements_table['id_measurement'] == registered_id].iloc[0])
    registration_ids.append(registration_id)

print(f"Found {len(reference_measurements)} registrations")

Found 68 registrations

## Sample names

In [11]:
sample_measurements_table = db.relation_metadata('samples','measurements','sample_measurements')

# sample_measurements_table = sample_measurements_table[sample_measurements_table['name_sample'].isin(['1.27', '1.28', '1.29', '1.32', '1.33'])]

sample_measurements_table

,id_sample,name_sample,description_sample,panel_id_sample,height_sample,width_sample,thickness_sample,keyhole_sample,parallel_faces_sample,Missing_sample,...,height_measurement,width_measurement,depth_measurement,dtype_measurement,file_type_measurement,aligned_measurement,equalized_measurement,axes_order_measurement,transformations_measurement,signal_type_measurement
0,9,JI_4,None,3,150.0 mm,50.0 mm,5.0 mm,True bool,True bool,NaN,...,448 cardinal,190 cardinal,492 cardinal,uint8 nominal,.tif nominal,NaN,NaN,"['z', 'y', 'x'] list",NaN,RF nominal
1,9,JI_4,None,3,150.0 mm,50.0 mm,5.0 mm,True bool,True bool,NaN,...,448 cardinal,125 cardinal,48 cardinal,uint8 nominal,.tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped region containing only the sample. text,RF nominal
2,9,JI_4,None,3,150.0 mm,50.0 mm,5.0 mm,True bool,True bool,NaN,...,3737 cardinal,1770 cardinal,1015 cardinal,uint16 string,folder string,NaN,NaN,"['x', 'y', 'z'] list",NaN,NaN
3,9,JI_4,None,3,150.0 mm,50.0 mm,5.0 mm,True bool,True bool,NaN,...,3224 cardinal,1770 cardinal,1015 cardinal,uint8 string,folder string,False bool,True bool,"['x', 'y', 'z'] list",Volume equalized with this parameters:\r\n\r\n...,NaN
4,9,JI_4,None,3,150.0 mm,50.0 mm,5.0 mm,True bool,True bool,NaN,...,3224 cardinal,1610 cardinal,240 cardinal,uint8 string,folder string,False bool,True bool,"['x', 'y', 'z'] list",Cropped to region that contains the sample onl...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
523,101,Na_10_5,None,14,150 mm,40 mm,5 mm,True bool,True bool,NaN,...,447 cardinal,149 cardinal,64 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal
524,101,Na_10_5,None,14,150 mm,40 mm,5 mm,True bool,True bool,NaN,...,3934 cardinal,1708 cardinal,507 cardinal,uint16 string,folder string,False bool,False bool,"['x', 'y', 'z'] list",NaN,NaN
525,101,Na_10_5,None,14,150 mm,40 mm,5 mm,True bool,True bool,NaN,...,3477 cardinal,1708 cardinal,507 cardinal,uint8 string,folder string,False bool,True bool,"['x', 'y', 'z'] list",Volume equalized with this parameters: Referen...,NaN
526,101,Na_10_5,None,14,150 mm,40 mm,5 mm,True bool,True bool,NaN,...,3477 cardinal,1649 cardinal,221 cardinal,uint8 string,folder string,False bool,True bool,"['x', 'y', 'z'] list",Isolated from a volume conatining more samples...,NaN
527,101,Na_10_5,None,14,150 mm,40 mm,5 mm,True bool,True bool,NaN,...,237 cardinal,3478 cardinal,1649 cardinal,uint8 string,tif string,True bool,True bool,"['z', 'y', 'x'] list","Frontwall aligned with axes, rotated 90 degree...",NaN

In [12]:
sample_names = []

for i in range(len(reference_measurements)):

    measurement = reference_measurements[i]
    sample_names.append(sample_measurements_table[sample_measurements_table['id_measurement'] == measurement['id_measurement']].iloc[0]['name_sample'])

print(f"Found {len(sample_names)} samples")

Found 68 samples

# Datasettype selection

In [13]:
datasettype_table = db.get_data('datasettypes')

datasettype_table

   id_datasettype                            description_datasettype
0               4  2024 Dataset Type. Material mask computed usin...
1               3  2025 Dataset Type. Material mask computed usin...
2               5  Placeholder Dataset Type: A generic category f...
3               6  2025 Dataset Type. Material mask computed usin...

In [14]:
datasettype = 3

# Discard already computed datasets

In [15]:
try:
    dataset_registrations_table = db.relation_metadata('datasets','registrations','dataset_registrations')

    dataset_registrations_table = dataset_registrations_table[dataset_registrations_table['datasettype_id_dataset'] == datasettype]

    dataset_registrations = dataset_registrations_table['id_registration'].values

except Exception as e:
    print("No dataset registrations found or error occurred:", e)
    dataset_registrations = []

# Saving folder

In [16]:
folder = Path(r'\\192.168.10.106\imdea\DataDriven_UT_AlbertoVicente\04_ML_data\Airbus\Pegaso\lente\2025\patch_vs_nopatch')

# Patch sizes

In [17]:
patch_sizes = [1,3,5]

# Resolutions

In [18]:
xct_resolution = float(measurementtypes_table[measurementtypes_table['id_measurementtype'] == xct_type]['voxel_size_measurementtype'].values[0].split(' ')[0])
ut_resolution = float(measurementtypes_table[measurementtypes_table['id_measurementtype'] == ut_type]['x_resolution_measurementtype'].values[0].split(' ')[0])
print(f"XCT resolution: {xct_resolution}, UT resolution: {ut_resolution}")

XCT resolution: 0.025, UT resolution: 1.0

# Dataset Generation

In [19]:
for i in range(len(registration_ids)):
    reference_measurement_path = reference_measurements[i]['file_path_measurement']
    registered_measurement_path = registered_measurements[i]['file_path_measurement']
    registration_id = registration_ids[i]
    sample_name = sample_names[i]

    if registration_id in dataset_registrations:
        print(f"Dataset for registration {registration_id} already exists, skipping...")
        continue

    print(f"Creating dataset for registration {registration_id} with reference measurement {reference_measurement_path} and registered measurement {registered_measurement_path}")

    #load the reference and registered measurements
    ut_volume = io.load_tif(reference_measurement_path)
    xct_volume = io.load_tif(registered_measurement_path)

    #xct_volume is z,y,x, so we need to transpose it to x,y,z
    xct_volume = np.transpose(xct_volume, (1, 2, 0))
    #ut_volume is z,y,x, so we need to transpose it to x,y,z
    ut_volume = np.transpose(ut_volume, (1, 2, 0))

    #apply the registration to the xct volume
    registration_parameters = registrations_table[registrations_table['id_registration'] == registration_id]['registration_matrix_registration'].values[0]
    registration_parameters = np.array(ast.literal_eval(registration_parameters))
    
    xct_volume = register.apply_registration(ut_volume,xct_volume,registration_parameters,ut_resolution,xct_resolution,parallel=True)

    #get the frontwall and backwall of the xct volume
    _,frontwall,backwall = aligner.crop_walls(xct_volume)

    #back to z,y,x
    xct_volume = np.transpose(xct_volume, (2, 0, 1))
    ut_volume = np.transpose(ut_volume, (2, 0, 1))

    #compute the onlypores
    onlypores_volume,material_mask,_ = onlypores.onlypores(xct_volume,frontwall,backwall,min_size_filtering=8)

    #create a folder for the dataset
    dataset_folder = folder / f"{sample_name}"
    dataset_folder.mkdir(parents=True, exist_ok=True)

    #compute the datasets
    
    for patch_size in patch_sizes:

        reconstruction_shape,df = datasetmaker.main(onlypores_volume,material_mask,ut_volume,xct_resolution,ut_resolution,ut_patch_size=patch_size, ut_step_size=1,xct_patch_reduced_size=1)

        #save the dataset
        dataset_path = dataset_folder / f"patch_size_{patch_size}_volfrac_areafrac.csv"
        df.to_csv(dataset_path, index=False)

        #save into the database
        rows = len(df)
        targets = ['volfrac','areafrac']
        description = 'Created with the production notebook in preprocess tools v 0.1.17'

        load.load_dataset(conn,
                          datasettype_id=datasettype,
                          file_path=str(dataset_path),
                          rows=rows,
                          patch_size=str(patch_size),
                          targets=targets,
                          reconstruction_shape=reconstruction_shape,
                          registration_ids = [registration_id],
                          description=description
                          )

        print(f"Dataset for registration {registration_id} with patch size {patch_size} saved to {dataset_path}")

Dataset for registration 76 already exists, skipping...
Dataset for registration 77 already exists, skipping...
Dataset for registration 78 already exists, skipping...
Dataset for registration 79 already exists, skipping...
Dataset for registration 84 already exists, skipping...
Dataset for registration 85 already exists, skipping...
Dataset for registration 86 already exists, skipping...
Dataset for registration 87 already exists, skipping...
Dataset for registration 88 already exists, skipping...
Dataset for registration 89 already exists, skipping...
Dataset for registration 90 already exists, skipping...
Dataset for registration 91 already exists, skipping...
Dataset for registration 92 already exists, skipping...
Dataset for registration 93 already exists, skipping...
Dataset for registration 94 already exists, skipping...
Dataset for registration 95 already exists, skipping...
Dataset for registration 96 already exists, skipping...
Dataset for registration 97 already exists, skipping...
Dataset for registration 98 already exists, skipping...
Dataset for registration 99 already exists, skipping...
Dataset for registration 100 already exists, skipping...
Dataset for registration 101 already exists, skipping...
Dataset for registration 102 already exists, skipping...
Dataset for registration 103 already exists, skipping...
Dataset for registration 104 already exists, skipping...
Dataset for registration 105 already exists, skipping...
Dataset for registration 106 already exists, skipping...
Dataset for registration 107 already exists, skipping...
Dataset for registration 108 already exists, skipping...
Dataset for registration 109 already exists, skipping...
Dataset for registration 110 already exists, skipping...
Dataset for registration 111 already exists, skipping...
Dataset for registration 116 already exists, skipping...
Dataset for registration 117 already exists, skipping...
Dataset for registration 118 already exists, skipping...
Dataset for registration 119 already exists, skipping...
Dataset for registration 120 already exists, skipping...
Dataset for registration 121 already exists, skipping...
Dataset for registration 122 already exists, skipping...
Dataset for registration 123 already exists, skipping...
Dataset for registration 124 already exists, skipping...
Dataset for registration 125 already exists, skipping...
Dataset for registration 128 already exists, skipping...
Dataset for registration 129 already exists, skipping...
Dataset for registration 131 already exists, skipping...
Dataset for registration 132 already exists, skipping...
Dataset for registration 133 already exists, skipping...
Dataset for registration 134 already exists, skipping...
Dataset for registration 135 already exists, skipping...
Dataset for registration 136 already exists, skipping...
Dataset for registration 137 already exists, skipping...
Dataset for registration 138 already exists, skipping...
Dataset for registration 139 already exists, skipping...
Dataset for registration 140 already exists, skipping...
Dataset for registration 141 already exists, skipping...
Dataset for registration 142 already exists, skipping...
Dataset for registration 143 already exists, skipping...
Dataset for registration 144 already exists, skipping...
Dataset for registration 145 already exists, skipping...
Dataset for registration 146 already exists, skipping...
Dataset for registration 147 already exists, skipping...
Dataset for registration 148 already exists, skipping...
Dataset for registration 149 already exists, skipping...
Creating dataset for registration 155 with reference measurement \\192.168.10.106\imdea\DataDriven_UT_AlbertoVicente\03_UT_data\Panel PEGASO\lente\probetas\1_28\1_28.tif and registered measurement \\192.168.10.106\imdea\DataDriven_UT_AlbertoVicente\02_XCT_data\Airbus\Panel Pegaso\probetas\1\28\volumen_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 252/252 [00:13<00:00, 18.73it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.

c:\Users\alberto.vicente\AppData\Local\miniconda3\envs\prep\Lib\site-packages\numpy\_core\fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
c:\Users\alberto.vicente\AppData\Local\miniconda3\envs\prep\Lib\site-packages\numpy\_core\_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (252, 5280, 2000)
Data bounding box: Z[0:251], Y[1110:4124], X[75:1868]
Cropped volume shape: (252, 3019, 1798)
Applying Sauvola adaptive thresholding...
Volume size: 1.27 GB
Available memory: 141.71 GB
Required memory estimate: 2.55 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 32
Excluding back wall: slices 227 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 39029975 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 3816947
  Components after size filtering: 649536
  Valid components after dimensional filtering: 631697
  Components after dimensional filtering: 631697
  Total pore voxels retained: 31533613
After filtering: 31533613 pore voxels remaining.
Pore detection analysis complete.
Preprocessing and patching the images...
Patching the images...
Cleaning the pores...
Creating the datasets...
Dataset from '\\192.168.10.106\imdea\DataDriven_UT_AlbertoVicente\04_ML_data\Airbus\Pegaso\lente\2025\patch_vs_nopatch\1.28\patch_size_1_volfrac_areafrac.csv' loaded with ID: 729
Dataset for registration 155 with patch size 1 saved to \\192.168.10.106\imdea\DataDriven_UT_AlbertoVicente\04_ML_data\Airbus\Pegaso\lente\2025\patch_vs_nopatch\1.28\patch_size_1_volfrac_areafrac.csv
Preprocessing and patching the images...
Patching the images...
Cleaning the pores...
Creating the datasets...
Dataset from '\\192.168.10.106\imdea\DataDriven_UT_AlbertoVicente\04_ML_data\Airbus\Pegaso\lente\2025\patch_vs_nopatch\1.28\patch_size_3_volfrac_areafrac.csv' loaded with ID: 730
Dataset for registration 155 with patch size 3 saved to \\192.168.10.106\imdea\DataDriven_UT_AlbertoVicente\04_ML_data\Airbus\Pegaso\lente\2025\patch_vs_nopatch\1.28\patch_size_3_volfrac_areafrac.csv
Preprocessing and patching the images...
Patching the images...
Cleaning the pores...
Creating the datasets...
Dataset from '\\192.168.10.106\imdea\DataDriven_UT_AlbertoVicente\04_ML_data\Airbus\Pegaso\lente\2025\patch_vs_nopatch\1.28\patch_size_5_volfrac_areafrac.csv' loaded with ID: 731
Dataset for registration 155 with patch size 5 saved to \\192.168.10.106\imdea\DataDriven_UT_AlbertoVicente\04_ML_data\Airbus\Pegaso\lente\2025\patch_vs_nopatch\1.28\patch_size_5_volfrac_areafrac.csv
Creating dataset for registration 156 with reference measurement \\192.168.10.106\imdea\DataDriven_UT_AlbertoVicente\03_UT_data\Panel PEGASO\lente\probetas\1_29\1_29.tif and registered measurement \\192.168.10.106\imdea\DataDriven_UT_AlbertoVicente\02_XCT_data\Airbus\Panel Pegaso\probetas\1\29\volumen_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 294/294 [00:20<00:00, 14.54it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.

c:\Users\alberto.vicente\AppData\Local\miniconda3\envs\prep\Lib\site-packages\numpy\_core\fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
c:\Users\alberto.vicente\AppData\Local\miniconda3\envs\prep\Lib\site-packages\numpy\_core\_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (294, 5240, 1920)
Data bounding box: Z[0:293], Y[1098:4087], X[93:1854]
Cropped volume shape: (294, 2994, 1766)
Applying Sauvola adaptive thresholding...
Volume size: 1.45 GB
Available memory: 131.31 GB
Required memory estimate: 2.90 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding back wall: slices 295 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 30693709 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 3379905
  Components after size filtering: 561853
  Valid components after dimensional filtering: 549024
  Components after dimensional filtering: 549024
  Total pore voxels retained: 24098242
After filtering: 24098242 pore voxels remaining.
Pore detection analysis complete.
Preprocessing and patching the images...
Patching the images...
Cleaning the pores...
Creating the datasets...
Dataset from '\\192.168.10.106\imdea\DataDriven_UT_AlbertoVicente\04_ML_data\Airbus\Pegaso\lente\2025\patch_vs_nopatch\1.29\patch_size_1_volfrac_areafrac.csv' loaded with ID: 732
Dataset for registration 156 with patch size 1 saved to \\192.168.10.106\imdea\DataDriven_UT_AlbertoVicente\04_ML_data\Airbus\Pegaso\lente\2025\patch_vs_nopatch\1.29\patch_size_1_volfrac_areafrac.csv
Preprocessing and patching the images...
Patching the images...
Cleaning the pores...
Creating the datasets...
Dataset from '\\192.168.10.106\imdea\DataDriven_UT_AlbertoVicente\04_ML_data\Airbus\Pegaso\lente\2025\patch_vs_nopatch\1.29\patch_size_3_volfrac_areafrac.csv' loaded with ID: 733
Dataset for registration 156 with patch size 3 saved to \\192.168.10.106\imdea\DataDriven_UT_AlbertoVicente\04_ML_data\Airbus\Pegaso\lente\2025\patch_vs_nopatch\1.29\patch_size_3_volfrac_areafrac.csv
Preprocessing and patching the images...
Patching the images...
Cleaning the pores...
Creating the datasets...
Dataset from '\\192.168.10.106\imdea\DataDriven_UT_AlbertoVicente\04_ML_data\Airbus\Pegaso\lente\2025\patch_vs_nopatch\1.29\patch_size_5_volfrac_areafrac.csv' loaded with ID: 734
Dataset for registration 156 with patch size 5 saved to \\192.168.10.106\imdea\DataDriven_UT_AlbertoVicente\04_ML_data\Airbus\Pegaso\lente\2025\patch_vs_nopatch\1.29\patch_size_5_volfrac_areafrac.csv
Creating dataset for registration 157 with reference measurement \\192.168.10.106\imdea\DataDriven_UT_AlbertoVicente\03_UT_data\Panel PEGASO\lente\probetas\1_32\1_32.tif and registered measurement \\192.168.10.106\imdea\DataDriven_UT_AlbertoVicente\02_XCT_data\Airbus\Panel Pegaso\probetas\1\32\volumen_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 230/230 [00:12<00:00, 18.13it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.

c:\Users\alberto.vicente\AppData\Local\miniconda3\envs\prep\Lib\site-packages\numpy\_core\fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
c:\Users\alberto.vicente\AppData\Local\miniconda3\envs\prep\Lib\site-packages\numpy\_core\_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (230, 5280, 1880)
Data bounding box: Z[0:229], Y[918:4128], X[64:1812]
Cropped volume shape: (230, 3215, 1753)
Applying Sauvola adaptive thresholding...
Volume size: 1.21 GB
Available memory: 136.36 GB
Required memory estimate: 2.41 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding back wall: slices 231 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 12450718 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 2218670
  Components after size filtering: 244231
  Valid components after dimensional filtering: 218722
  Components after dimensional filtering: 218722
  Total pore voxels retained: 7682992
After filtering: 7682992 pore voxels remaining.
Pore detection analysis complete.
Preprocessing and patching the images...
Patching the images...
Cleaning the pores...
Creating the datasets...
Dataset from '\\192.168.10.106\imdea\DataDriven_UT_AlbertoVicente\04_ML_data\Airbus\Pegaso\lente\2025\patch_vs_nopatch\1.32\patch_size_1_volfrac_areafrac.csv' loaded with ID: 735
Dataset for registration 157 with patch size 1 saved to \\192.168.10.106\imdea\DataDriven_UT_AlbertoVicente\04_ML_data\Airbus\Pegaso\lente\2025\patch_vs_nopatch\1.32\patch_size_1_volfrac_areafrac.csv
Preprocessing and patching the images...
Patching the images...
Cleaning the pores...
Creating the datasets...
Dataset from '\\192.168.10.106\imdea\DataDriven_UT_AlbertoVicente\04_ML_data\Airbus\Pegaso\lente\2025\patch_vs_nopatch\1.32\patch_size_3_volfrac_areafrac.csv' loaded with ID: 736
Dataset for registration 157 with patch size 3 saved to \\192.168.10.106\imdea\DataDriven_UT_AlbertoVicente\04_ML_data\Airbus\Pegaso\lente\2025\patch_vs_nopatch\1.32\patch_size_3_volfrac_areafrac.csv
Preprocessing and patching the images...
Patching the images...
Cleaning the pores...
Creating the datasets...
Dataset from '\\192.168.10.106\imdea\DataDriven_UT_AlbertoVicente\04_ML_data\Airbus\Pegaso\lente\2025\patch_vs_nopatch\1.32\patch_size_5_volfrac_areafrac.csv' loaded with ID: 737
Dataset for registration 157 with patch size 5 saved to \\192.168.10.106\imdea\DataDriven_UT_AlbertoVicente\04_ML_data\Airbus\Pegaso\lente\2025\patch_vs_nopatch\1.32\patch_size_5_volfrac_areafrac.csv
Creating dataset for registration 158 with reference measurement \\192.168.10.106\imdea\DataDriven_UT_AlbertoVicente\03_UT_data\Panel PEGASO\lente\probetas\1_33\1_33.tif and registered measurement \\192.168.10.106\imdea\DataDriven_UT_AlbertoVicente\02_XCT_data\Airbus\Panel Pegaso\probetas\1\33\volumen_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 235/235 [00:12<00:00, 18.57it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.

c:\Users\alberto.vicente\AppData\Local\miniconda3\envs\prep\Lib\site-packages\numpy\_core\fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
c:\Users\alberto.vicente\AppData\Local\miniconda3\envs\prep\Lib\site-packages\numpy\_core\_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (235, 5280, 1880)
Data bounding box: Z[0:234], Y[901:4150], X[25:1821]
Cropped volume shape: (235, 3254, 1801)
Applying Sauvola adaptive thresholding...
Volume size: 1.28 GB
Available memory: 137.21 GB
Required memory estimate: 2.57 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding back wall: slices 236 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 14780058 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 2243762
  Components after size filtering: 246013
  Valid components after dimensional filtering: 222229
  Components after dimensional filtering: 222229
  Total pore voxels retained: 9990862
After filtering: 9990862 pore voxels remaining.
Pore detection analysis complete.
Preprocessing and patching the images...
Patching the images...
Cleaning the pores...
Creating the datasets...
Dataset from '\\192.168.10.106\imdea\DataDriven_UT_AlbertoVicente\04_ML_data\Airbus\Pegaso\lente\2025\patch_vs_nopatch\1.33\patch_size_1_volfrac_areafrac.csv' loaded with ID: 738
Dataset for registration 158 with patch size 1 saved to \\192.168.10.106\imdea\DataDriven_UT_AlbertoVicente\04_ML_data\Airbus\Pegaso\lente\2025\patch_vs_nopatch\1.33\patch_size_1_volfrac_areafrac.csv
Preprocessing and patching the images...
Patching the images...
Cleaning the pores...
Creating the datasets...
Dataset from '\\192.168.10.106\imdea\DataDriven_UT_AlbertoVicente\04_ML_data\Airbus\Pegaso\lente\2025\patch_vs_nopatch\1.33\patch_size_3_volfrac_areafrac.csv' loaded with ID: 739
Dataset for registration 158 with patch size 3 saved to \\192.168.10.106\imdea\DataDriven_UT_AlbertoVicente\04_ML_data\Airbus\Pegaso\lente\2025\patch_vs_nopatch\1.33\patch_size_3_volfrac_areafrac.csv
Preprocessing and patching the images...
Patching the images...
Cleaning the pores...
Creating the datasets...
Dataset from '\\192.168.10.106\imdea\DataDriven_UT_AlbertoVicente\04_ML_data\Airbus\Pegaso\lente\2025\patch_vs_nopatch\1.33\patch_size_5_volfrac_areafrac.csv' loaded with ID: 740
Dataset for registration 158 with patch size 5 saved to \\192.168.10.106\imdea\DataDriven_UT_AlbertoVicente\04_ML_data\Airbus\Pegaso\lente\2025\patch_vs_nopatch\1.33\patch_size_5_volfrac_areafrac.csv
Creating dataset for registration 159 with reference measurement \\192.168.10.106\imdea\DataDriven_UT_AlbertoVicente\03_UT_data\Panel PEGASO\lente\probetas\1_27\1_27.tif and registered measurement \\192.168.10.106\imdea\DataDriven_UT_AlbertoVicente\02_XCT_data\Airbus\Panel Pegaso\probetas\1\27\volumen_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 315/315 [00:18<00:00, 17.27it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.

c:\Users\alberto.vicente\AppData\Local\miniconda3\envs\prep\Lib\site-packages\numpy\_core\fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
c:\Users\alberto.vicente\AppData\Local\miniconda3\envs\prep\Lib\site-packages\numpy\_core\_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (315, 5200, 2000)
Data bounding box: Z[0:314], Y[1022:3998], X[114:1849]
Cropped volume shape: (315, 2981, 1740)
Applying Sauvola adaptive thresholding...
Volume size: 1.52 GB
Available memory: 130.14 GB
Required memory estimate: 3.04 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding back wall: slices 316 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 36387657 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 3606954
  Components after size filtering: 650739
  Valid components after dimensional filtering: 631766
  Components after dimensional filtering: 631766
  Total pore voxels retained: 29220133
After filtering: 29220133 pore voxels remaining.
Pore detection analysis complete.
Preprocessing and patching the images...
Patching the images...
Cleaning the pores...
Creating the datasets...
Dataset from '\\192.168.10.106\imdea\DataDriven_UT_AlbertoVicente\04_ML_data\Airbus\Pegaso\lente\2025\patch_vs_nopatch\1.27\patch_size_1_volfrac_areafrac.csv' loaded with ID: 741
Dataset for registration 159 with patch size 1 saved to \\192.168.10.106\imdea\DataDriven_UT_AlbertoVicente\04_ML_data\Airbus\Pegaso\lente\2025\patch_vs_nopatch\1.27\patch_size_1_volfrac_areafrac.csv
Preprocessing and patching the images...
Patching the images...
Cleaning the pores...
Creating the datasets...
Dataset from '\\192.168.10.106\imdea\DataDriven_UT_AlbertoVicente\04_ML_data\Airbus\Pegaso\lente\2025\patch_vs_nopatch\1.27\patch_size_3_volfrac_areafrac.csv' loaded with ID: 742
Dataset for registration 159 with patch size 3 saved to \\192.168.10.106\imdea\DataDriven_UT_AlbertoVicente\04_ML_data\Airbus\Pegaso\lente\2025\patch_vs_nopatch\1.27\patch_size_3_volfrac_areafrac.csv
Preprocessing and patching the images...
Patching the images...
Cleaning the pores...
Creating the datasets...
Dataset from '\\192.168.10.106\imdea\DataDriven_UT_AlbertoVicente\04_ML_data\Airbus\Pegaso\lente\2025\patch_vs_nopatch\1.27\patch_size_5_volfrac_areafrac.csv' loaded with ID: 743
Dataset for registration 159 with patch size 5 saved to \\192.168.10.106\imdea\DataDriven_UT_AlbertoVicente\04_ML_data\Airbus\Pegaso\lente\2025\patch_vs_nopatch\1.27\patch_size_5_volfrac_areafrac.csv