# imports

In [18]:
import sys
project_root = r'/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing'
if project_root not in sys.path:
    sys.path.append(project_root)
import importlib
from preprocess_tools import onlypores, datasetmaker, io, aligner, register
datasetmaker = importlib.reload(datasetmaker)
import numpy as np
import pandas as pd
import tifffile
from dbtools import dbtools as db
from dbtools import load as load
from pathlib import Path
import ast

# Path mapping

In [19]:
LOCAL_DATA_ROOT = Path('/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente')
UNC_DATA_ROOT = r'\\192.168.10.106\imdea\DataDriven_UT_AlbertoVicente'


def resolve_data_path(path, must_exist=True):
    path_str = str(path).strip()
    direct_path = Path(path_str)

    try:
        direct_exists = direct_path.exists()
    except OSError:
        direct_exists = False

    if direct_exists:
        return direct_path

    normalized_path = path_str.replace('\\', '/')
    normalized_unc_root = UNC_DATA_ROOT.replace('\\', '/')

    if normalized_path.lower().startswith(normalized_unc_root.lower()):
        relative_path = normalized_path[len(normalized_unc_root):].lstrip('/')
        local_path = LOCAL_DATA_ROOT / relative_path
        if local_path.exists() or not must_exist:
            return local_path

    if must_exist:
        raise FileNotFoundError(
            f"Could not resolve data path: {path_str}\n"
            f"Tried direct path and UNC mapping to: {LOCAL_DATA_ROOT}"
        )

    return direct_path

# Database connection

In [20]:
try:
    conn = db.connect()
    print("Connected to the database")
except Exception as error:
    print(error)

Connected to the database

# Select measurements to create the image datasets

## Measurement type

In [21]:
measurementtypes_table = db.get_data_metadata('measurementtypes')

measurementtypes_table

,id_measurementtype,name_measurementtype,description_measurementtype,technique_measurementtype,equipment_measurementtype,transducer_name_measurementtype,transducer_nominal_freq_measurementtype,transducer_diameter_measurementtype,transducer_focal_length_measurementtype,z_resolution_measurementtype,...,projections_measurementtype,target_measurementtype,filter_measurementtype,Detector_measurementtype,scaling_measurementtype,power_measurementtype,DAC_measurementtype,lens_measurementtype,lens_focal_length_measurementtype,transducer_measurementtype
0,5,Monoelement Ultrasound Pulse Echo 1,NaN,Ultrasound Monoelement Pulse Echo nominal,TRITON 1000P nominal,Technisonic ISL-0503-HR nominal,5 MHz,9.525 mm,76.2 mm,0.02232141 mm,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,6,XCT 1,NaN,X-Ray Computed Tomography nominal,ZEISS Xradia Versa 620 nominal,NaN,NaN,NaN,NaN,NaN,...,3738 cardinal,wolframio nominal,LE1 nominal,Flat Panel nominal,"[-1.700072,1.841701] float array",4.5 W,NaN,NaN,NaN,NaN
2,7,Monoelement Ultrasound Pulse Echo Airbus DAC,NaN,Ultrasound Monoelement Pulse Echo nominal,TRITON 1000P nominal,Technisonic ISL-0503-HR nominal,5 MHz,9.525 mm,76.2 mm,0.02232141 mm,...,NaN,NaN,NaN,NaN,NaN,NaN,"[[10.1,4.33],[12.1,6.18],[19.7,10.38],[26.7,15...",NaN,NaN,NaN
3,8,Monoelement Ultrasound Pulse Echo Low Resolution,NaN,Ultrasound Monoelement Pulse Echo nominal,TRITON 1000P nominal,Technisonic ISL-0503-HR nominal,5 MHz,9.525 mm,76.2 mm,0.05940588 mm,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,9,Placeholder Measurement Type,A generic placeholder for a measurement techni...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,10,Monoelement Ultrasound Pulse Echo Airbus DAC L...,NaN,Ultrasound Monoelement Pulse Echo nominal,TRITON 1000P nominal,Technisonic ISL-0503-HR nominal,5 MHz,9.525 mm,42 mm,0.02232141 mm,...,NaN,NaN,NaN,NaN,NaN,NaN,"[[10.1,4.33],[12.1,6.18],[19.7,10.38],[26.7,15...",True bool,"38,1 mm",NaN
6,11,Monoelement Ultrasound Pulse Echo Na,NaN,Ultrasound Monoelement Pulse Echo nominal,TRITON 1000P nominal,NaN,5 MHz,9.525 mm,76.2 mm,0.02232141 mm,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Technisonic ISL-0503-HR nominal

In [22]:
ut_type = 11

xct_type = 6

## Selecting UT measurements

In [23]:
ut_measurements_table = db.get_data_metadata('measurements')

ut_measurements_table = ut_measurements_table[ut_measurements_table['measurementtype_id_measurement'] == ut_type]

ut_measurements_table

,id_measurement,file_path_measurement,parent_measurement_id_measurement,measurementtype_id_measurement,height_measurement,width_measurement,depth_measurement,dtype_measurement,file_type_measurement,aligned_measurement,equalized_measurement,axes_order_measurement,transformations_measurement,signal_type_measurement,actual_voxel_size_measurement,raw_file_path_measurement,raw_dtype_measurement,raw_byte_order_measurement,raw_shape_zyx_measurement
332,533,/home/alberto.vicente/phd/DataDriven_UT_Albert...,NaN,11,448 cardinal,164 cardinal,304 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",NaN,RF nominal,NaN,/home/alberto.vicente/phd/DataDriven_UT_Albert...,uint8 nominal,little nominal,"(448, 164, 304) nominal"
333,534,/home/alberto.vicente/phd/DataDriven_UT_Albert...,NaN,11,448 cardinal,164 cardinal,304 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",NaN,RF nominal,NaN,/home/alberto.vicente/phd/DataDriven_UT_Albert...,uint8 nominal,little nominal,"(448, 164, 304) nominal"
334,535,/home/alberto.vicente/phd/DataDriven_UT_Albert...,NaN,11,448 cardinal,164 cardinal,304 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",NaN,RF nominal,NaN,/home/alberto.vicente/phd/DataDriven_UT_Albert...,uint8 nominal,little nominal,"(448, 164, 304) nominal"
335,536,/home/alberto.vicente/phd/DataDriven_UT_Albert...,NaN,11,448 cardinal,164 cardinal,304 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",NaN,RF nominal,NaN,/home/alberto.vicente/phd/DataDriven_UT_Albert...,uint8 nominal,little nominal,"(448, 164, 304) nominal"
336,537,/home/alberto.vicente/phd/DataDriven_UT_Albert...,NaN,11,448 cardinal,164 cardinal,304 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",NaN,RF nominal,NaN,/home/alberto.vicente/phd/DataDriven_UT_Albert...,uint8 nominal,little nominal,"(448, 164, 304) nominal"
337,538,/home/alberto.vicente/phd/DataDriven_UT_Albert...,NaN,11,448 cardinal,164 cardinal,280 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",NaN,RF nominal,NaN,/home/alberto.vicente/phd/DataDriven_UT_Albert...,uint8 nominal,little nominal,"(448, 164, 280) nominal"
338,539,/home/alberto.vicente/phd/DataDriven_UT_Albert...,NaN,11,448 cardinal,172 cardinal,236 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",NaN,RF nominal,NaN,/home/alberto.vicente/phd/DataDriven_UT_Albert...,uint8 nominal,little nominal,"(448, 172, 236) nominal"
339,540,/home/alberto.vicente/phd/DataDriven_UT_Albert...,NaN,11,448 cardinal,169 cardinal,248 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",NaN,RF nominal,NaN,/home/alberto.vicente/phd/DataDriven_UT_Albert...,uint8 nominal,little nominal,"(448, 169, 248) nominal"
340,541,/home/alberto.vicente/phd/DataDriven_UT_Albert...,NaN,11,448 cardinal,160 cardinal,252 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",NaN,RF nominal,NaN,/home/alberto.vicente/phd/DataDriven_UT_Albert...,uint8 nominal,little nominal,"(448, 160, 252) nominal"
341,542,/home/alberto.vicente/phd/DataDriven_UT_Albert...,NaN,11,448 cardinal,161 cardinal,264 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",NaN,RF nominal,NaN,/home/alberto.vicente/phd/DataDriven_UT_Albert...,uint8 nominal,little nominal,"(448, 161, 264) nominal"
342,548,/home/alberto.vicente/phd/DataDriven_UT_Albert...,533.0,11,448 cardinal,132 cardinal,49 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
343,549,/home/alberto.vicente/phd/DataDriven_UT_Albert...,533.0,11,448 cardinal,133 cardinal,50 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
344,550,/home/alberto.vicente/phd/DataDriven_UT_Albert...,533.0,11,448 cardinal,133 cardinal,50 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
345,551,/home/alberto.vicente/phd/DataDriven_UT_Albert...,533.0,11,448 cardinal,132 cardinal,48 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
346,552,/home/alberto.vicente/phd/DataDriven_UT_Albert...,533.0,11,448 cardinal,132 cardinal,48 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
347,558,/home/alberto.vicente/phd/DataDriven_UT_Albert...,534.0,11,448 cardinal,133 cardinal,53 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
348,559,/home/alberto.vicente/phd/DataDriven_UT_Albert...,534.0,11,448 cardinal,133 cardinal,50 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
349,560,/home/alberto.vicente/phd/DataDriven_UT_Albert...,534.0,11,448 cardinal,134 cardinal,49 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
350,561,/home/alberto.vicente/phd/DataDriven_UT_Albert...,534.0,11,448 cardinal,131 cardinal,49 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
351,562,/home/alberto.vicente/phd/DataDriven_UT_Albert...,534.0,11,448 cardinal,134 cardinal,48 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
352,563,/home/alberto.vicente/phd/DataDriven_UT_Albert...,535.0,11,448 cardinal,133 cardinal,52 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
353,564,/home/alberto.vicente/phd/DataDriven_UT_Albert...,535.0,11,448 cardinal,132 cardinal,49 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
354,565,/home/alberto.vicente/phd/DataDriven_UT_Albert...,535.0,11,448 cardinal,132 cardinal,47 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
355,566,/home/alberto.vicente/phd/DataDriven_UT_Albert...,535.0,11,448 cardinal,132 cardinal,49 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
356,567,/home/alberto.vicente/phd/DataDriven_UT_Albert...,535.0,11,448 cardinal,133 cardinal,49 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
357,568,/home/alberto.vicente/phd/DataDriven_UT_Albert...,536.0,11,448 cardinal,132 cardinal,48 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
358,569,/home/alberto.vicente/phd/DataDriven_UT_Albert...,536.0,11,448 cardinal,133 cardinal,47 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
359,570,/home/alberto.vicente/phd/DataDriven_UT_Albert...,536.0,11,448 cardinal,132 cardinal,48 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
360,571,/home/alberto.vicente/phd/DataDriven_UT_Albert...,536.0,11,448 cardinal,132 cardinal,48 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
361,572,/home/alberto.vicente/phd/DataDriven_UT_Albert...,536.0,11,448 cardinal,132 cardinal,47 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
362,573,/home/alberto.vicente/phd/DataDriven_UT_Albert...,537.0,11,448 cardinal,132 cardinal,49 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
363,574,/home/alberto.vicente/phd/DataDriven_UT_Albert...,537.0,11,448 cardinal,131 cardinal,47 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
364,575,/home/alberto.vicente/phd/DataDriven_UT_Albert...,537.0,11,448 cardinal,132 cardinal,47 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
365,576,/home/alberto.vicente/phd/DataDriven_UT_Albert...,537.0,11,448 cardinal,131 cardinal,46 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
366,577,/home/alberto.vicente/phd/DataDriven_UT_Albert...,537.0,11,448 cardinal,131 cardinal,46 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
367,578,/home/alberto.vicente/phd/DataDriven_UT_Albert...,538.0,11,448 cardinal,131 cardinal,49 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
368,579,/home/alberto.vicente/phd/DataDriven_UT_Albert...,538.0,11,448 cardinal,132 cardinal,48 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
369,580,/home/alberto.vicente/phd/DataDriven_UT_Albert...,538.0,11,448 cardinal,133 cardinal,47 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
370,581,/home/alberto.vicente/phd/DataDriven_UT_Albert...,538.0,11,448 cardinal,132 cardinal,47 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
371,582,/home/alberto.vicente/phd/DataDriven_UT_Albert...,538.0,11,448 cardinal,131 cardinal,47 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
372,583,/home/alberto.vicente/phd/DataDriven_UT_Albert...,539.0,11,448 cardinal,132 cardinal,50 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
373,584,/home/alberto.vicente/phd/DataDriven_UT_Albert...,539.0,11,448 cardinal,132 cardinal,49 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
374,585,/home/alberto.vicente/phd/DataDriven_UT_Albert...,539.0,11,448 cardinal,133 cardinal,51 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
375,586,/home/alberto.vicente/phd/DataDriven_UT_Albert...,539.0,11,448 cardinal,132 cardinal,51 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
376,587,/home/alberto.vicente/phd/DataDriven_UT_Albert...,540.0,11,448 cardinal,132 cardinal,52 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
377,588,/home/alberto.vicente/phd/DataDriven_UT_Albert...,540.0,11,448 cardinal,134 cardinal,55 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
378,589,/home/alberto.vicente/phd/DataDriven_UT_Albert...,540.0,11,448 cardinal,132 cardinal,55 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
379,590,/home/alberto.vicente/phd/DataDriven_UT_Albert...,540.0,11,448 cardinal,132 cardinal,53 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
380,591,/home/alberto.vicente/phd/DataDriven_UT_Albert...,540.0,11,448 cardinal,132 cardinal,53 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
381,592,/home/alberto.vicente/phd/DataDriven_UT_Albert...,541.0,11,448 cardinal,131 cardinal,46 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
382,593,/home/alberto.vicente/phd/DataDriven_UT_Albert...,541.0,11,448 cardinal,132 cardinal,46 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
383,594,/home/alberto.vicente/phd/DataDriven_UT_Albert...,541.0,11,448 cardinal,131 cardinal,49 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
384,595,/home/alberto.vicente/phd/DataDriven_UT_Albert...,541.0,11,448 cardinal,131 cardinal,48 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
385,596,/home/alberto.vicente/phd/DataDriven_UT_Albert...,541.0,11,448 cardinal,131 cardinal,48 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
386,597,/home/alberto.vicente/phd/DataDriven_UT_Albert...,542.0,11,448 cardinal,132 cardinal,47 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
387,598,/home/alberto.vicente/phd/DataDriven_UT_Albert...,542.0,11,448 cardinal,132 cardinal,48 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
388,599,/home/alberto.vicente/phd/DataDriven_UT_Albert...,542.0,11,448 cardinal,134 cardinal,48 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
389,600,/home/alberto.vicente/phd/DataDriven_UT_Albert...,542.0,11,448 cardinal,132 cardinal,50 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN
390,601,/home/alberto.vicente/phd/DataDriven_UT_Albert...,542.0,11,448 cardinal,131 cardinal,47 cardinal,uint8 nominal,tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN

## Selecting XCT measurements

In [24]:
xct_measurements_table = db.get_data_metadata('measurements')

xct_measurements_table = xct_measurements_table[xct_measurements_table['measurementtype_id_measurement'] == xct_type]

xct_measurements_table

,id_measurement,file_path_measurement,parent_measurement_id_measurement,measurementtype_id_measurement,height_measurement,width_measurement,depth_measurement,dtype_measurement,file_type_measurement,aligned_measurement,equalized_measurement,axes_order_measurement,transformations_measurement,signal_type_measurement,actual_voxel_size_measurement,raw_file_path_measurement,raw_dtype_measurement,raw_byte_order_measurement,raw_shape_zyx_measurement
0,253,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,252.0,6,3411 cardinal,1908 cardinal,1117 cardinal,uint8 string,folder string,False bool,True bool,"['x', 'y', 'z'] list",Volume equalized with this parameters: Referen...,NaN,NaN,NaN,NaN,NaN,NaN
2,101,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,NaN,6,3737 cardinal,1770 cardinal,1015 cardinal,uint16 string,folder string,NaN,NaN,"['x', 'y', 'z'] list",NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,102,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,101.0,6,3224 cardinal,1770 cardinal,1015 cardinal,uint8 string,folder string,False bool,True bool,"['x', 'y', 'z'] list",Volume equalized with this parameters:\r\n\r\n...,NaN,NaN,NaN,NaN,NaN,NaN
4,103,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,NaN,6,3735 cardinal,1734 cardinal,1003 cardinal,uint16 string,folder string,False bool,False bool,"['x', 'y', 'z'] list",NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,104,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,103.0,6,3226 cardinal,1734 cardinal,1003 cardinal,uint8 string,folder string,False bool,True bool,"['x', 'y', 'z'] list",Volume equalized with this parameters: \r\n\r\...,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
330,532,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,482.0,6,237 cardinal,3478 cardinal,1649 cardinal,uint8 string,tif string,True bool,True bool,"['z', 'y', 'x'] list","Frontwall aligned with axes, rotated 90 degree...",NaN,NaN,NaN,NaN,NaN,NaN
391,606,/home/alberto.vicente/phd/DataDriven_UT_Albert...,527.0,6,199 cardinal,3172 cardinal,1593 cardinal,uint8 string,tif string,True bool,True bool,"['z', 'y', 'x'] list",Downscaled from 0.0206 mm/voxel to 0.025 mm/vo...,NaN,NaN,NaN,NaN,NaN,NaN
392,607,/home/alberto.vicente/phd/DataDriven_UT_Albert...,528.0,6,200 cardinal,3172 cardinal,1599 cardinal,uint8 string,tif string,True bool,True bool,"['z', 'y', 'x'] list",Downscaled from 0.0206 mm/voxel to 0.025 mm/vo...,NaN,NaN,NaN,NaN,NaN,NaN
393,608,/home/alberto.vicente/phd/DataDriven_UT_Albert...,529.0,6,210 cardinal,3172 cardinal,1619 cardinal,uint8 string,tif string,True bool,True bool,"['z', 'y', 'x'] list",Downscaled from 0.0206 mm/voxel to 0.025 mm/vo...,NaN,NaN,NaN,NaN,NaN,NaN
394,609,/home/alberto.vicente/phd/DataDriven_UT_Albert...,530.0,6,206 cardinal,3173 cardinal,1585 cardinal,uint8 string,tif string,True bool,True bool,"['z', 'y', 'x'] list",Downscaled from 0.0206 mm/voxel to 0.025 mm/vo...,NaN,NaN,NaN,NaN,NaN,NaN

## Getting registered pairs

In [25]:
registrations_table = db.get_data_metadata('registrations')

registrations_table = registrations_table[registrations_table['reference_measurement_id_registration'].isin(ut_measurements_table['id_measurement'])]

registrations_table = registrations_table[registrations_table['registered_measurement_id_registration'].isin(xct_measurements_table['id_measurement'])]

registrations_table

,id_registration,reference_measurement_id_registration,registered_measurement_id_registration,registration_matrix_registration,description_registration,type_registration,axes_registration
92,279,574,504,"[[0.9999999999999996, 7.287339190013969e-18, -...",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
93,280,575,505,"[[0.999999943354598, -0.00033658698867541925, ...",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
94,281,576,506,"[[0.9999997689294977, -0.000679809496213158, -...",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
95,282,577,507,"[[0.9999999999999996, 7.287339190013969e-18, -...",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
96,283,578,508,"[[0.9995430679443119, -0.03022673195158059, -8...",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
97,284,579,509,"[[0.9995421143940344, -0.03025824768063574, -8...",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
98,285,580,510,"[[0.9999477017148175, -0.010227112752609518, -...",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
99,286,581,511,"[[0.9999999455391131, -0.0003300329853264041, ...",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
100,287,582,512,"[[0.9995503035223673, -0.029986509105671164, -...",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
101,288,583,514,"[[0.999181287998132, -0.040456812953990354, -9...",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
102,289,584,515,"[[0.9992611746313148, -0.03843312210120442, -9...",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
103,290,585,516,"[[0.9999565342591332, -0.009323604049036148, -...",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
104,291,586,517,"[[0.9987768776459356, -0.049444399883462206, -...",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
105,292,587,518,"[[0.9992363788304918, -0.039072486761477995, -...",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
106,293,588,519,"[[0.9974569601884967, -0.07127140079670474, -8...",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
107,294,589,520,"[[0.996884272852586, -0.07887804852537303, -77...",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
108,295,590,521,"[[0.9968141992754567, -0.07975871189299702, -7...",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
109,296,591,522,"[[0.996816357249325, -0.07973173722041901, -81...",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
110,297,592,523,"[[0.9999995191016949, 0.000980712179570115, -9...",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
111,298,593,524,"[[0.9999477017148175, 0.010227112752609397, -9...",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
112,299,594,525,"[[1.0000000000000002, -3.137301352915218e-17, ...",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
113,300,595,526,"[[0.9999999445184492, 0.0003331112406789912, -...",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
114,301,596,606,"[[0.9995323102850224, -0.030580397255196724, -...",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
115,302,597,607,"[[0.9999573335608684, -0.009237481141439902, -...",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
116,303,598,608,"[[0.9999559912209339, 0.009381664103981608, -1...",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
117,304,599,609,"[[0.999560527542106, -0.029643747734504258, -1...",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
118,305,600,531,"[[0.9987982414536298, -0.049010946421553965, -...",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
119,306,601,532,"[[0.9982170481561048, -0.05968856482202007, -8...",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
125,258,548,483,"[[0.9999452889103096, 0.010460362616910664, -1...",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
126,259,549,484,"[[0.9995790769772142, -0.029011529938652712, -...",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
127,260,550,485,"[[0.9999616841168166, -0.008753873328968681, -...",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
128,261,551,486,"[[0.9998054619375741, 0.01972405333074122, -10...",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
129,262,552,487,"[[0.9999519450250807, -0.009803450441422246, -...",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
130,263,558,488,"[[0.912631645605348, -0.408782924594062, -450....",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
131,264,559,489,"[[0.9352226649534569, 0.3540601177164037, -156...",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
132,265,560,490,"[[0.9997880881002273, -0.02058589062663478, -9...",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
133,266,561,491,"[[0.9796027006414902, 0.200944143721331, -1150...",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
134,267,562,492,"[[0.728783620734287, 0.6847440647055094, -627....",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
135,268,563,493,"[[0.9987830979218685, -0.04931858985814332, -9...",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
136,269,564,494,"[[0.9987915364250748, -0.049147398360832546, -...",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
137,270,565,495,"[[0.9995486381109622, -0.030041971481936845, -...",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
138,271,566,496,"[[0.9998000599800072, -0.019996001199600266, -...",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
139,272,567,497,"[[0.9987830979218685, -0.04931858985814332, -9...",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
140,273,568,498,"[[0.9997945272752498, -0.02027074814750511, -9...",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
141,274,569,499,"[[0.9995402616778833, -0.030319387937562406, -...",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
142,275,570,500,"[[0.9999997544601993, 0.0007007706758655315, -...",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
143,276,571,501,"[[0.9997960016298645, -0.020197899022825618, -...",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
144,277,572,502,"[[0.9992106097698422, -0.03972602828599773, -9...",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"
145,278,573,503,"[[0.9987982414536298, -0.049010946421553965, -...",NaN,"Alberto and Lucia 2025 registration method, fi...","['x', 'y'] list"

## Sample and panel metadata

In [26]:
sample_measurements_table = db.relation_metadata('samples', 'measurements', 'sample_measurements')
samples_table = db.get_data_metadata('samples')
panels_table = db.get_data_metadata('panels')

sample_measurements_table

,id_sample,name_sample,description_sample,panel_id_sample,height_sample,width_sample,thickness_sample,keyhole_sample,parallel_faces_sample,Missing_sample,...,aligned_measurement,equalized_measurement,axes_order_measurement,transformations_measurement,signal_type_measurement,actual_voxel_size_measurement,raw_file_path_measurement,raw_dtype_measurement,raw_byte_order_measurement,raw_shape_zyx_measurement
0,9,JI_4,NaN,3,150.0 mm,50.0 mm,5.0 mm,True bool,True bool,NaN,...,NaN,NaN,"['z', 'y', 'x'] list",NaN,RF nominal,NaN,NaN,NaN,NaN,NaN
1,9,JI_4,NaN,3,150.0 mm,50.0 mm,5.0 mm,True bool,True bool,NaN,...,NaN,NaN,"['z', 'y', 'x'] list",Cropped region containing only the sample. text,RF nominal,NaN,NaN,NaN,NaN,NaN
2,9,JI_4,NaN,3,150.0 mm,50.0 mm,5.0 mm,True bool,True bool,NaN,...,NaN,NaN,"['x', 'y', 'z'] list",NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,9,JI_4,NaN,3,150.0 mm,50.0 mm,5.0 mm,True bool,True bool,NaN,...,False bool,True bool,"['x', 'y', 'z'] list",Volume equalized with this parameters:\r\n\r\n...,NaN,NaN,NaN,NaN,NaN,NaN
4,9,JI_4,NaN,3,150.0 mm,50.0 mm,5.0 mm,True bool,True bool,NaN,...,False bool,True bool,"['x', 'y', 'z'] list",Cropped to region that contains the sample onl...,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
625,101,Na_10_5,NaN,14,150 mm,40 mm,5 mm,True bool,True bool,NaN,...,False bool,True bool,"['x', 'y', 'z'] list",Volume equalized with this parameters: Referen...,NaN,NaN,NaN,NaN,NaN,NaN
626,101,Na_10_5,NaN,14,150 mm,40 mm,5 mm,True bool,True bool,NaN,...,False bool,True bool,"['x', 'y', 'z'] list",Isolated from a volume conatining more samples...,NaN,NaN,NaN,NaN,NaN,NaN
627,101,Na_10_5,NaN,14,150 mm,40 mm,5 mm,True bool,True bool,NaN,...,True bool,True bool,"['z', 'y', 'x'] list","Frontwall aligned with axes, rotated 90 degree...",NaN,NaN,NaN,NaN,NaN,NaN
628,101,Na_10_5,NaN,14,150 mm,40 mm,5 mm,True bool,True bool,NaN,...,NaN,NaN,"['z', 'y', 'x'] list",NaN,RF nominal,NaN,/home/alberto.vicente/phd/DataDriven_UT_Albert...,uint8 nominal,little nominal,"(448, 161, 264) nominal"
629,101,Na_10_5,NaN,14,150 mm,40 mm,5 mm,True bool,True bool,NaN,...,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN

In [27]:
def lookup_sample_metadata(measurement_id):
    sample_rows = sample_measurements_table[sample_measurements_table['id_measurement'] == measurement_id]
    if sample_rows.empty:
        return {
            'sample_id': None,
            'sample_name': None,
            'panel_id': None,
            'panel_name': None,
        }

    sample_row = sample_rows.iloc[0]
    sample_id = sample_row.get('id_sample')
    sample_name = sample_row.get('name_sample')
    panel_id = sample_row.get('panel_id_sample')

    if pd.isna(panel_id) and sample_id is not None:
        matching_samples = samples_table[samples_table['id_sample'] == sample_id]
        if not matching_samples.empty:
            panel_id = matching_samples.iloc[0].get('panel_id_sample')

    panel_name = None
    if panel_id is not None and not pd.isna(panel_id):
        matching_panels = panels_table[panels_table['id_panel'] == panel_id]
        if not matching_panels.empty:
            panel_name = matching_panels.iloc[0].get('name_panel')

    return {
        'sample_id': sample_id,
        'sample_name': sample_name,
        'panel_id': panel_id,
        'panel_name': panel_name,
    }


registered_pairs = []

for _, registration in registrations_table.iterrows():
    reference_id = registration['reference_measurement_id_registration']
    registered_id = registration['registered_measurement_id_registration']

    reference_measurement = ut_measurements_table[ut_measurements_table['id_measurement'] == reference_id].iloc[0]
    registered_measurement = xct_measurements_table[xct_measurements_table['id_measurement'] == registered_id].iloc[0]
    sample_metadata = lookup_sample_metadata(reference_id)

    registered_pairs.append({
        'registration_id': registration['id_registration'],
        'reference_measurement_id': reference_id,
        'registered_measurement_id': registered_id,
        'reference_measurement_path': reference_measurement['file_path_measurement'],
        'registered_measurement_path': registered_measurement['file_path_measurement'],
        'sample_id': sample_metadata['sample_id'],
        'sample_name': sample_metadata['sample_name'],
        'panel_id': sample_metadata['panel_id'],
        'panel_name': sample_metadata['panel_name'],
    })

registered_pairs_df = pd.DataFrame(registered_pairs)

print(f"Found {len(registered_pairs_df)} registrations")
registered_pairs_df

Found 49 registrations

,registration_id,reference_measurement_id,registered_measurement_id,reference_measurement_path,registered_measurement_path,sample_id,sample_name,panel_id,panel_name
0,279,574,504,/home/alberto.vicente/phd/DataDriven_UT_Albert...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,73,Na_05_2,9,Na_05
1,280,575,505,/home/alberto.vicente/phd/DataDriven_UT_Albert...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,74,Na_05_3,9,Na_05
2,281,576,506,/home/alberto.vicente/phd/DataDriven_UT_Albert...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,75,Na_05_4,9,Na_05
3,282,577,507,/home/alberto.vicente/phd/DataDriven_UT_Albert...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,76,Na_05_5,9,Na_05
4,283,578,508,/home/alberto.vicente/phd/DataDriven_UT_Albert...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,77,Na_06_1,10,Na_06
5,284,579,509,/home/alberto.vicente/phd/DataDriven_UT_Albert...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,78,Na_06_2,10,Na_06
6,285,580,510,/home/alberto.vicente/phd/DataDriven_UT_Albert...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,79,Na_06_3,10,Na_06
7,286,581,511,/home/alberto.vicente/phd/DataDriven_UT_Albert...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,80,Na_06_4,10,Na_06
8,287,582,512,/home/alberto.vicente/phd/DataDriven_UT_Albert...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,81,Na_06_5,10,Na_06
9,288,583,514,/home/alberto.vicente/phd/DataDriven_UT_Albert...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,83,Na_07_2,11,Na_07
10,289,584,515,/home/alberto.vicente/phd/DataDriven_UT_Albert...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,84,Na_07_3,11,Na_07
11,290,585,516,/home/alberto.vicente/phd/DataDriven_UT_Albert...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,85,Na_07_4,11,Na_07
12,291,586,517,/home/alberto.vicente/phd/DataDriven_UT_Albert...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,86,Na_07_5,11,Na_07
13,292,587,518,/home/alberto.vicente/phd/DataDriven_UT_Albert...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,87,Na_08_1,12,Na_08
14,293,588,519,/home/alberto.vicente/phd/DataDriven_UT_Albert...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,88,Na_08_2,12,Na_08
15,294,589,520,/home/alberto.vicente/phd/DataDriven_UT_Albert...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,89,Na_08_3,12,Na_08
16,295,590,521,/home/alberto.vicente/phd/DataDriven_UT_Albert...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,90,Na_08_4,12,Na_08
17,296,591,522,/home/alberto.vicente/phd/DataDriven_UT_Albert...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,91,Na_08_5,12,Na_08
18,297,592,523,/home/alberto.vicente/phd/DataDriven_UT_Albert...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,92,Na_09_1,13,Na_09
19,298,593,524,/home/alberto.vicente/phd/DataDriven_UT_Albert...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,93,Na_09_2,13,Na_09
20,299,594,525,/home/alberto.vicente/phd/DataDriven_UT_Albert...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,94,Na_09_3,13,Na_09
21,300,595,526,/home/alberto.vicente/phd/DataDriven_UT_Albert...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,95,Na_09_4,13,Na_09
22,301,596,606,/home/alberto.vicente/phd/DataDriven_UT_Albert...,/home/alberto.vicente/phd/DataDriven_UT_Albert...,96,Na_09_5,13,Na_09
23,302,597,607,/home/alberto.vicente/phd/DataDriven_UT_Albert...,/home/alberto.vicente/phd/DataDriven_UT_Albert...,97,Na_10_1,14,Na_10
24,303,598,608,/home/alberto.vicente/phd/DataDriven_UT_Albert...,/home/alberto.vicente/phd/DataDriven_UT_Albert...,98,Na_10_2,14,Na_10
25,304,599,609,/home/alberto.vicente/phd/DataDriven_UT_Albert...,/home/alberto.vicente/phd/DataDriven_UT_Albert...,99,Na_10_3,14,Na_10
26,305,600,531,/home/alberto.vicente/phd/DataDriven_UT_Albert...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,100,Na_10_4,14,Na_10
27,306,601,532,/home/alberto.vicente/phd/DataDriven_UT_Albert...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,101,Na_10_5,14,Na_10
28,258,548,483,/home/alberto.vicente/phd/DataDriven_UT_Albert...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,47,Na_01_1,5,Na_01
29,259,549,484,/home/alberto.vicente/phd/DataDriven_UT_Albert...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,48,Na_01_2,5,Na_01
30,260,550,485,/home/alberto.vicente/phd/DataDriven_UT_Albert...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,49,Na_01_3,5,Na_01
31,261,551,486,/home/alberto.vicente/phd/DataDriven_UT_Albert...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,50,Na_01_4,5,Na_01
32,262,552,487,/home/alberto.vicente/phd/DataDriven_UT_Albert...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,51,Na_01_5,5,Na_01
33,263,558,488,/home/alberto.vicente/phd/DataDriven_UT_Albert...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,52,Na_02_1,6,Na_02
34,264,559,489,/home/alberto.vicente/phd/DataDriven_UT_Albert...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,53,Na_02_2,6,Na_02
35,265,560,490,/home/alberto.vicente/phd/DataDriven_UT_Albert...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,54,Na_02_3,6,Na_02
36,266,561,491,/home/alberto.vicente/phd/DataDriven_UT_Albert...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,55,Na_02_4,6,Na_02
37,267,562,492,/home/alberto.vicente/phd/DataDriven_UT_Albert...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,56,Na_02_5,6,Na_02
38,268,563,493,/home/alberto.vicente/phd/DataDriven_UT_Albert...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,57,Na_03_1,7,Na_03
39,269,564,494,/home/alberto.vicente/phd/DataDriven_UT_Albert...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,58,Na_03_2,7,Na_03
40,270,565,495,/home/alberto.vicente/phd/DataDriven_UT_Albert...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,59,Na_03_3,7,Na_03
41,271,566,496,/home/alberto.vicente/phd/DataDriven_UT_Albert...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,60,Na_03_4,7,Na_03
42,272,567,497,/home/alberto.vicente/phd/DataDriven_UT_Albert...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,61,Na_03_5,7,Na_03
43,273,568,498,/home/alberto.vicente/phd/DataDriven_UT_Albert...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,67,Na_04_1,8,Na_04
44,274,569,499,/home/alberto.vicente/phd/DataDriven_UT_Albert...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,68,Na_04_2,8,Na_04
45,275,570,500,/home/alberto.vicente/phd/DataDriven_UT_Albert...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,69,Na_04_3,8,Na_04
46,276,571,501,/home/alberto.vicente/phd/DataDriven_UT_Albert...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,70,Na_04_4,8,Na_04
47,277,572,502,/home/alberto.vicente/phd/DataDriven_UT_Albert...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,71,Na_04_5,8,Na_04
48,278,573,503,/home/alberto.vicente/phd/DataDriven_UT_Albert...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,72,Na_05_1,9,Na_05

# Dataset type selection

In [28]:
datasettype_table = db.get_data('datasettypes')

datasettype_table

   id_datasettype                            description_datasettype
0               4  2024 Dataset Type. Material mask computed usin...
1               3  2025 Dataset Type. Material mask computed usin...
2               5  Placeholder Dataset Type: A generic category f...
3               6  2025 Dataset Type. Material mask computed usin...
4               8  2026 Conical Dataset Type. Material mask compu...
5               7  2026 Dataset Type. Material mask computed usin...
6               9  2026 reference signal dataset, reference signa...
7              10  2026 Dataset Type. Material mask computed usin...

In [29]:
datasettype = 10
load_into_database = True

# Discard already computed datasets

In [30]:
if datasettype is not None:
    try:
        dataset_registrations_table = db.relation_metadata('datasets', 'registrations', 'dataset_registrations')

        dataset_registrations_table = dataset_registrations_table[dataset_registrations_table['datasettype_id_dataset'] == datasettype]

        dataset_registrations = dataset_registrations_table['id_registration'].values

    except Exception as e:
        print("No dataset registrations found or error occurred:", e)
        dataset_registrations = []
else:
    dataset_registrations = []

# Saving folder

In [31]:
folder = Path(r'/home/alberto.vicente/phd//DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores')

folder.mkdir(parents=True, exist_ok=True)

# Image settings

In [32]:
material_threshold = 0.8
stop_after_first = False
sauvola_radius = 15
sauvola_k = 0.2

# Resolutions

In [33]:
xct_resolution = float(measurementtypes_table[measurementtypes_table['id_measurementtype'] == xct_type]['voxel_size_measurementtype'].values[0].split(' ')[0])
ut_resolution = float(measurementtypes_table[measurementtypes_table['id_measurementtype'] == ut_type]['x_resolution_measurementtype'].values[0].split(' ')[0])
print(f"XCT resolution: {xct_resolution}, UT resolution: {ut_resolution}")

XCT resolution: 0.025, UT resolution: 1.0

# Dataset generation

In [34]:
excluded_samples = []

manifest_rows = []

for _, pair in registered_pairs_df.iterrows():
    reference_measurement_path_raw = pair['reference_measurement_path']
    registered_measurement_path_raw = pair['registered_measurement_path']
    registration_id = pair['registration_id']
    sample_name = pair['sample_name']
    sample_folder_name = sample_name if pd.notna(sample_name) else f"registration_{registration_id}"

    if sample_name in excluded_samples:
        print(f"Sample {sample_name} is in the exclusion list, skipping...")
        continue

    if registration_id in dataset_registrations:
        print(f"Dataset for registration {registration_id} already exists, skipping...")
        continue

    reference_measurement_path = resolve_data_path(reference_measurement_path_raw)
    registered_measurement_path = resolve_data_path(registered_measurement_path_raw)

    print(f"Creating image dataset for registration {registration_id} with reference measurement {reference_measurement_path} and registered measurement {registered_measurement_path}")

    ut_volume = io.load_tif(reference_measurement_path)
    xct_volume = io.load_tif(registered_measurement_path)

    xct_volume = np.transpose(xct_volume, (1, 2, 0))
    ut_volume = np.transpose(ut_volume, (1, 2, 0))

    registration_parameters = registrations_table[registrations_table['id_registration'] == registration_id]['registration_matrix_registration'].values[0]
    registration_parameters = np.array(ast.literal_eval(registration_parameters))

    xct_volume = register.apply_registration(ut_volume, xct_volume, registration_parameters, ut_resolution, xct_resolution, parallel=True)

    _, frontwall, backwall = aligner.crop_walls(xct_volume)

    xct_volume = np.transpose(xct_volume, (2, 0, 1))
    ut_volume = np.transpose(ut_volume, (2, 0, 1))

    onlypores_volume, material_mask, _ = onlypores.onlypores(xct_volume, frontwall, backwall, min_size_filtering=8)

    dataset_folder = folder / f"{sample_folder_name}" / f"registration_{registration_id}"
    dataset_folder.mkdir(parents=True, exist_ok=True)

    ut_image, volfrac_maps, areafrac_image, depth_rois = datasetmaker.main_images(
        onlypores_volume,
        material_mask,
        ut_volume,
        xct_resolution,
        ut_resolution,
        material_threshold=material_threshold,
    )

    depth_roi_regions = tuple(roi['region'] for roi in depth_rois)
    depth_roi_start_from_frontwall = tuple(roi['start_from_frontwall'] for roi in depth_rois)
    depth_roi_end_exclusive_from_frontwall = tuple(roi['end_exclusive_from_frontwall'] for roi in depth_rois)
    depth_roi_end_inclusive_from_frontwall = tuple(roi['end_inclusive_from_frontwall'] for roi in depth_rois)
    depth_roi_start_z = tuple(roi['start_z'] for roi in depth_rois)
    depth_roi_end_exclusive_z = tuple(roi['end_exclusive_z'] for roi in depth_rois)
    depth_roi_end_inclusive_z = tuple(roi['end_inclusive_z'] for roi in depth_rois)
    material_frontwall_z = depth_rois[0]['material_frontwall_z']
    material_backwall_z = depth_rois[0]['material_backwall_z']

    image_outputs = {
        'ut': (dataset_folder / 'ut_volume.tif', ut_image, None),
        'volfrac': (dataset_folder / 'volfrac_maps.tif', volfrac_maps.astype(np.float32), depth_roi_regions),
        'areafrac': (dataset_folder / 'areafrac_map.tif', areafrac_image.astype(np.float32), None),
    }

    current_rows = []
    for image_kind, (image_path, image_array, depth_region) in image_outputs.items():
        tifffile.imwrite(image_path, image_array, bigtiff=True)
        current_rows.append({
            'image_kind': image_kind,
            'image_path': str(image_path),
            'image_shape': tuple(image_array.shape),
            'image_dtype': str(image_array.dtype),
            'file_format': 'tif',
            'depth_region': depth_region,
            'sample_id': pair['sample_id'],
            'sample_name': sample_name,
            'panel_id': pair['panel_id'],
            'panel_name': pair['panel_name'],
            'registration_id': registration_id,
            'reference_measurement_id': pair['reference_measurement_id'],
            'registered_measurement_id': pair['registered_measurement_id'],
            'reference_measurement_path': str(reference_measurement_path),
            'registered_measurement_path': str(registered_measurement_path),
            'reference_measurement_path_raw': reference_measurement_path_raw,
            'registered_measurement_path_raw': registered_measurement_path_raw,
            'ut_image_shape': tuple(ut_image.shape),
            'target_map_shape': tuple(volfrac_maps.shape[1:]),
            'volfrac_maps_shape': tuple(volfrac_maps.shape),
            'volfrac_region_names': depth_roi_regions,
            'depth_roi_start_from_frontwall': depth_roi_start_from_frontwall,
            'depth_roi_end_exclusive_from_frontwall': depth_roi_end_exclusive_from_frontwall,
            'depth_roi_end_inclusive_from_frontwall': depth_roi_end_inclusive_from_frontwall,
            'depth_roi_start_z': depth_roi_start_z,
            'depth_roi_end_exclusive_z': depth_roi_end_exclusive_z,
            'depth_roi_end_inclusive_z': depth_roi_end_inclusive_z,
            'material_frontwall_z': material_frontwall_z,
            'material_backwall_z': material_backwall_z,
            'material_threshold': material_threshold,
            'xct_resolution': xct_resolution,
            'ut_resolution': ut_resolution,
        })

    registration_manifest_df = pd.DataFrame(current_rows)
    registration_manifest_path = dataset_folder / 'image_manifest.csv'
    registration_manifest_df.to_csv(registration_manifest_path, index=False)
    manifest_rows.extend(current_rows)

    if load_into_database and datasettype is not None:
        rows = int(np.prod(volfrac_maps.shape))
        targets = ['volfrac_front', 'volfrac_middle', 'volfrac_back', 'areafrac']
        description = 'Image-shaped dataset without UT patches, created with preprocess tools v 0.1.23'

        load.load_dataset(
            conn,
            datasettype_id=datasettype,
            file_path=str(registration_manifest_path),
            rows=rows,
            patch_size='no_ut_patches',
            targets=targets,
            reconstruction_shape=volfrac_maps.shape,
            registration_ids=[registration_id],
            description=description,
        )

    print(f"Image dataset for registration {registration_id} saved to {dataset_folder}")

    if stop_after_first:
        break

manifest_df = pd.DataFrame(manifest_rows)
manifest_path = folder / 'image_dataset_manifest.csv'

if manifest_path.exists() and not manifest_df.empty:
    existing_manifest_df = pd.read_csv(manifest_path)
    updated_ids = manifest_df['registration_id'].unique()
    existing_manifest_df = existing_manifest_df[~existing_manifest_df['registration_id'].isin(updated_ids)]
    manifest_df = pd.concat([existing_manifest_df, manifest_df], ignore_index=True)
elif manifest_path.exists():
    manifest_df = pd.read_csv(manifest_path)

manifest_df.to_csv(manifest_path, index=False)

print(f"Saved image dataset manifest to {manifest_path}")
manifest_df

Creating image dataset for registration 279 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_05_2/Na_05_2.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_05_2/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 196/196 [00:05<00:00, 38.23it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (196, 5240, 1880)
Data bounding box: Z[0:195], Y[907:4346], X[134:1743]
Cropped volume shape: (196, 3444, 1614)
Applying Sauvola adaptive thresholding...
Volume size: 1.01 GB
Available memory: 200.03 GB
Required memory estimate: 2.03 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 7
Excluding back wall: slices 183 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 3744153 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 1416730

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 43631
  Valid components after dimensional filtering: 40300
  Components after dimensional filtering: 40300
  Total pore voxels retained: 832093
After filtering: 832093 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_05_2/registration_279/image_manifest.csv' loaded with ID: 1237
Image dataset for registration 279 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_05_2/registration_279
Creating image dataset for registration 280 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_05_3/Na_05_3.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_05_3/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 200/200 [00:05<00:00, 40.00it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (200, 5280, 1880)
Data bounding box: Z[0:199], Y[947:4388], X[147:1748]
Cropped volume shape: (200, 3446, 1606)
Applying Sauvola adaptive thresholding...
Volume size: 1.03 GB
Available memory: 195.52 GB
Required memory estimate: 2.06 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 4
Excluding back wall: slices 179 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 3992042 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 1455241

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 42753
  Valid components after dimensional filtering: 40180
  Components after dimensional filtering: 40180
  Total pore voxels retained: 1073290
After filtering: 1073290 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_05_3/registration_280/image_manifest.csv' loaded with ID: 1238
Image dataset for registration 280 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_05_3/registration_280
Creating image dataset for registration 281 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_05_4/Na_05_4.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_05_4/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 214/214 [00:05<00:00, 42.13it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.

/home/alberto.vicente/miniconda3/envs/prep/lib/python3.14/site-packages/numpy/_core/fromnumeric.py:3824: RuntimeWarning: Mean of empty slice
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/alberto.vicente/miniconda3/envs/prep/lib/python3.14/site-packages/numpy/_core/_methods.py:142: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (214, 5240, 1840)
Data bounding box: Z[0:213], Y[907:4349], X[159:1782]
Cropped volume shape: (214, 3447, 1628)
Applying Sauvola adaptive thresholding...
Volume size: 1.12 GB
Available memory: 193.03 GB
Required memory estimate: 2.24 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 6
Excluding back wall: slices 179 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 3143915 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 978621

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 20046
  Valid components after dimensional filtering: 19223
  Components after dimensional filtering: 19223
  Total pore voxels retained: 1362283
After filtering: 1362283 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_05_4/registration_281/image_manifest.csv' loaded with ID: 1239
Image dataset for registration 281 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_05_4/registration_281
Creating image dataset for registration 282 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_05_5/Na_05_5.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_05_5/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 225/225 [00:05<00:00, 38.67it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.

/home/alberto.vicente/miniconda3/envs/prep/lib/python3.14/site-packages/numpy/_core/fromnumeric.py:3824: RuntimeWarning: Mean of empty slice
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/alberto.vicente/miniconda3/envs/prep/lib/python3.14/site-packages/numpy/_core/_methods.py:142: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (225, 5240, 1840)
Data bounding box: Z[0:224], Y[934:4335], X[147:1777]
Cropped volume shape: (225, 3406, 1635)
Applying Sauvola adaptive thresholding...
Volume size: 1.17 GB
Available memory: 191.92 GB
Required memory estimate: 2.33 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 10
Excluding back wall: slices 186 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 5111946 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 880027

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 51038
  Valid components after dimensional filtering: 49886
  Components after dimensional filtering: 49886
  Total pore voxels retained: 3488814
After filtering: 3488814 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_05_5/registration_282/image_manifest.csv' loaded with ID: 1240
Image dataset for registration 282 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_05_5/registration_282
Creating image dataset for registration 283 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_06_1/Na_06_1.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_06_1/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 212/212 [00:05<00:00, 41.05it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (212, 5240, 1960)
Data bounding box: Z[0:211], Y[872:4319], X[135:1866]
Cropped volume shape: (212, 3452, 1736)
Applying Sauvola adaptive thresholding...
Volume size: 1.18 GB
Available memory: 193.21 GB
Required memory estimate: 2.37 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 18
Excluding back wall: slices 196 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 5452856 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 1570745

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 55150
  Valid components after dimensional filtering: 52624
  Components after dimensional filtering: 52624
  Total pore voxels retained: 2367527
After filtering: 2367527 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_06_1/registration_283/image_manifest.csv' loaded with ID: 1241
Image dataset for registration 283 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_06_1/registration_283
Creating image dataset for registration 284 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_06_2/Na_06_2.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_06_2/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 218/218 [00:05<00:00, 43.10it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.

/home/alberto.vicente/miniconda3/envs/prep/lib/python3.14/site-packages/numpy/_core/fromnumeric.py:3824: RuntimeWarning: Mean of empty slice
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/alberto.vicente/miniconda3/envs/prep/lib/python3.14/site-packages/numpy/_core/_methods.py:142: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (218, 5280, 1920)
Data bounding box: Z[0:217], Y[899:4346], X[122:1835]
Cropped volume shape: (218, 3452, 1718)
Applying Sauvola adaptive thresholding...
Volume size: 1.20 GB
Available memory: 192.52 GB
Required memory estimate: 2.41 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 21
Excluding back wall: slices 201 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 3795787 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 1437527

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 39977
  Valid components after dimensional filtering: 38205
  Components after dimensional filtering: 38205
  Total pore voxels retained: 978505
After filtering: 978505 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_06_2/registration_284/image_manifest.csv' loaded with ID: 1242
Image dataset for registration 284 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_06_2/registration_284
Creating image dataset for registration 285 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_06_3/Na_06_3.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_06_3/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 226/226 [00:05<00:00, 39.88it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.

/home/alberto.vicente/miniconda3/envs/prep/lib/python3.14/site-packages/numpy/_core/fromnumeric.py:3824: RuntimeWarning: Mean of empty slice
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/alberto.vicente/miniconda3/envs/prep/lib/python3.14/site-packages/numpy/_core/_methods.py:142: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (226, 5320, 1880)
Data bounding box: Z[0:225], Y[966:4382], X[129:1783]
Cropped volume shape: (226, 3421, 1659)
Applying Sauvola adaptive thresholding...
Volume size: 1.19 GB
Available memory: 191.20 GB
Required memory estimate: 2.39 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 30
Excluding back wall: slices 210 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 3389300 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 1159906

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 21305
  Valid components after dimensional filtering: 20383
  Components after dimensional filtering: 20383
  Total pore voxels retained: 1300172
After filtering: 1300172 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_06_3/registration_285/image_manifest.csv' loaded with ID: 1243
Image dataset for registration 285 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_06_3/registration_285
Creating image dataset for registration 286 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_06_4/Na_06_4.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_06_4/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 203/203 [00:05<00:00, 39.31it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (203, 5280, 1880)
Data bounding box: Z[0:202], Y[947:4356], X[147:1761]
Cropped volume shape: (203, 3414, 1619)
Applying Sauvola adaptive thresholding...
Volume size: 1.04 GB
Available memory: 194.03 GB
Required memory estimate: 2.09 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 14
Excluding back wall: slices 193 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 6636008 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 1043623

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 39599
  Valid components after dimensional filtering: 37965
  Components after dimensional filtering: 37965
  Total pore voxels retained: 4705990
After filtering: 4705990 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_06_4/registration_286/image_manifest.csv' loaded with ID: 1244
Image dataset for registration 286 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_06_4/registration_286
Creating image dataset for registration 287 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_06_5/Na_06_5.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_06_5/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 196/196 [00:04<00:00, 44.07it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (196, 5240, 1880)
Data bounding box: Z[0:195], Y[925:4381], X[81:1802]
Cropped volume shape: (196, 3461, 1726)
Applying Sauvola adaptive thresholding...
Volume size: 1.09 GB
Available memory: 195.64 GB
Required memory estimate: 2.18 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 8
Excluding back wall: slices 186 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 11170850 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 1642780

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 103263
  Valid components after dimensional filtering: 99971
  Components after dimensional filtering: 99971
  Total pore voxels retained: 7880575
After filtering: 7880575 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_06_5/registration_287/image_manifest.csv' loaded with ID: 1245
Image dataset for registration 287 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_06_5/registration_287
Creating image dataset for registration 288 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_07_2/Na_07_2.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_07_2/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 226/226 [00:05<00:00, 38.36it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.

/home/alberto.vicente/miniconda3/envs/prep/lib/python3.14/site-packages/numpy/_core/fromnumeric.py:3824: RuntimeWarning: Mean of empty slice
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/alberto.vicente/miniconda3/envs/prep/lib/python3.14/site-packages/numpy/_core/_methods.py:142: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (226, 5280, 2000)
Data bounding box: Z[0:225], Y[931:4406], X[102:1878]
Cropped volume shape: (226, 3480, 1781)
Applying Sauvola adaptive thresholding...
Volume size: 1.30 GB
Available memory: 190.87 GB
Required memory estimate: 2.61 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 23
Excluding back wall: slices 212 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 7040717 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 1392182

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 44045
  Valid components after dimensional filtering: 42361
  Components after dimensional filtering: 42361
  Total pore voxels retained: 4468475
After filtering: 4468475 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_07_2/registration_288/image_manifest.csv' loaded with ID: 1246
Image dataset for registration 288 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_07_2/registration_288
Creating image dataset for registration 289 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_07_3/Na_07_3.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_07_3/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 212/212 [00:05<00:00, 41.03it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (212, 5280, 1960)
Data bounding box: Z[0:211], Y[959:4403], X[106:1854]
Cropped volume shape: (212, 3449, 1753)
Applying Sauvola adaptive thresholding...
Volume size: 1.19 GB
Available memory: 192.92 GB
Required memory estimate: 2.39 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 8
Excluding back wall: slices 196 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 6485447 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 959693

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 28577
  Valid components after dimensional filtering: 27549
  Components after dimensional filtering: 27549
  Total pore voxels retained: 4739648
After filtering: 4739648 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_07_3/registration_289/image_manifest.csv' loaded with ID: 1247
Image dataset for registration 289 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_07_3/registration_289
Creating image dataset for registration 290 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_07_4/Na_07_4.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_07_4/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 209/209 [00:05<00:00, 40.18it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (209, 5320, 2040)
Data bounding box: Z[0:208], Y[1007:4408], X[224:1870]
Cropped volume shape: (209, 3406, 1651)
Applying Sauvola adaptive thresholding...
Volume size: 1.09 GB
Available memory: 193.49 GB
Required memory estimate: 2.19 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 8
Excluding back wall: slices 195 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 14960019 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 1527189

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 150475
  Valid components after dimensional filtering: 146614
  Components after dimensional filtering: 146614
  Total pore voxels retained: 12011262
After filtering: 12011262 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_07_4/registration_290/image_manifest.csv' loaded with ID: 1248
Image dataset for registration 290 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_07_4/registration_290
Creating image dataset for registration 291 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_07_5/Na_07_5.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_07_5/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 235/235 [00:06<00:00, 38.91it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.

/home/alberto.vicente/miniconda3/envs/prep/lib/python3.14/site-packages/numpy/_core/fromnumeric.py:3824: RuntimeWarning: Mean of empty slice
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/alberto.vicente/miniconda3/envs/prep/lib/python3.14/site-packages/numpy/_core/_methods.py:142: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (235, 5280, 2040)
Data bounding box: Z[0:234], Y[938:4402], X[153:1966]
Cropped volume shape: (235, 3469, 1818)
Applying Sauvola adaptive thresholding...
Volume size: 1.38 GB
Available memory: 188.99 GB
Required memory estimate: 2.76 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 33
Excluding back wall: slices 220 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 24059245 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 1587954

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 210239
  Valid components after dimensional filtering: 204818
  Components after dimensional filtering: 204818
  Total pore voxels retained: 21026749
After filtering: 21026749 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_07_5/registration_291/image_manifest.csv' loaded with ID: 1249
Image dataset for registration 291 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_07_5/registration_291
Creating image dataset for registration 292 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_08_1/Na_08_1.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_08_1/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 196/196 [00:04<00:00, 42.76it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (196, 5280, 2080)
Data bounding box: Z[0:195], Y[958:4406], X[144:1925]
Cropped volume shape: (196, 3453, 1786)
Applying Sauvola adaptive thresholding...
Volume size: 1.13 GB
Available memory: 193.73 GB
Required memory estimate: 2.25 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 7
Excluding back wall: slices 182 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 3776003 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 1013115

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 21720
  Valid components after dimensional filtering: 20708
  Components after dimensional filtering: 20708
  Total pore voxels retained: 1924103
After filtering: 1924103 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_08_1/registration_292/image_manifest.csv' loaded with ID: 1250
Image dataset for registration 292 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_08_1/registration_292
Creating image dataset for registration 293 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_08_2/Na_08_2.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_08_2/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 218/218 [00:05<00:00, 39.34it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.

/home/alberto.vicente/miniconda3/envs/prep/lib/python3.14/site-packages/numpy/_core/fromnumeric.py:3824: RuntimeWarning: Mean of empty slice
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/alberto.vicente/miniconda3/envs/prep/lib/python3.14/site-packages/numpy/_core/_methods.py:142: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (218, 5360, 2200)
Data bounding box: Z[0:217], Y[856:4407], X[173:2041]
Cropped volume shape: (218, 3556, 1873)
Applying Sauvola adaptive thresholding...
Volume size: 1.35 GB
Available memory: 191.48 GB
Required memory estimate: 2.70 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 23
Excluding back wall: slices 200 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 2014752 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 938929

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 14120
  Valid components after dimensional filtering: 13159
  Components after dimensional filtering: 13159
  Total pore voxels retained: 336856
After filtering: 336856 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_08_2/registration_293/image_manifest.csv' loaded with ID: 1251
Image dataset for registration 293 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_08_2/registration_293
Creating image dataset for registration 294 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_08_3/Na_08_3.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_08_3/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 191/191 [00:04<00:00, 42.02it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (191, 5280, 2200)
Data bounding box: Z[0:190], Y[813:4372], X[161:2053]
Cropped volume shape: (191, 3564, 1897)
Applying Sauvola adaptive thresholding...
Volume size: 1.20 GB
Available memory: 193.82 GB
Required memory estimate: 2.41 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 7
Excluding back wall: slices 183 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 3363280 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 1336457

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 36881
  Valid components after dimensional filtering: 34300
  Components after dimensional filtering: 34300
  Total pore voxels retained: 731637
After filtering: 731637 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_08_3/registration_294/image_manifest.csv' loaded with ID: 1252
Image dataset for registration 294 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_08_3/registration_294
Creating image dataset for registration 295 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_08_4/Na_08_4.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_08_4/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 210/210 [00:05<00:00, 39.92it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.

/home/alberto.vicente/miniconda3/envs/prep/lib/python3.14/site-packages/numpy/_core/fromnumeric.py:3824: RuntimeWarning: Mean of empty slice
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/alberto.vicente/miniconda3/envs/prep/lib/python3.14/site-packages/numpy/_core/_methods.py:142: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (210, 5280, 2120)
Data bounding box: Z[0:209], Y[814:4377], X[147:2044]
Cropped volume shape: (210, 3568, 1902)
Applying Sauvola adaptive thresholding...
Volume size: 1.33 GB
Available memory: 192.23 GB
Required memory estimate: 2.65 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 22
Excluding back wall: slices 198 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 4807678 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 1324108

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 40125
  Valid components after dimensional filtering: 37439
  Components after dimensional filtering: 37439
  Total pore voxels retained: 2191821
After filtering: 2191821 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_08_4/registration_295/image_manifest.csv' loaded with ID: 1253
Image dataset for registration 295 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_08_4/registration_295
Creating image dataset for registration 296 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_08_5/Na_08_5.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_08_5/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 199/199 [00:04<00:00, 42.46it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (199, 5280, 2120)
Data bounding box: Z[0:198], Y[852:4413], X[131:2027]
Cropped volume shape: (199, 3566, 1901)
Applying Sauvola adaptive thresholding...
Volume size: 1.26 GB
Available memory: 193.47 GB
Required memory estimate: 2.51 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 7
Excluding back wall: slices 184 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 4486444 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 948163

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 27687
  Valid components after dimensional filtering: 26225
  Components after dimensional filtering: 26225
  Total pore voxels retained: 2760433
After filtering: 2760433 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_08_5/registration_296/image_manifest.csv' loaded with ID: 1254
Image dataset for registration 296 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_08_5/registration_296
Creating image dataset for registration 297 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_09_1/Na_09_1.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_09_1/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 194/194 [00:04<00:00, 43.42it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (194, 5240, 1840)
Data bounding box: Z[0:193], Y[946:4348], X[132:1751]
Cropped volume shape: (194, 3407, 1624)
Applying Sauvola adaptive thresholding...
Volume size: 1.00 GB
Available memory: 195.27 GB
Required memory estimate: 2.00 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 7
Excluding back wall: slices 186 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 10272115 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 1006437

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 57706
  Valid components after dimensional filtering: 56544
  Components after dimensional filtering: 56544
  Total pore voxels retained: 8462442
After filtering: 8462442 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_09_1/registration_297/image_manifest.csv' loaded with ID: 1255
Image dataset for registration 297 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_09_1/registration_297
Creating image dataset for registration 298 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_09_2/Na_09_2.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_09_2/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 194/194 [00:04<00:00, 45.06it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (194, 5280, 1840)
Data bounding box: Z[0:193], Y[965:4381], X[77:1736]
Cropped volume shape: (194, 3421, 1664)
Applying Sauvola adaptive thresholding...
Volume size: 1.03 GB
Available memory: 195.41 GB
Required memory estimate: 2.06 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 7
Excluding back wall: slices 187 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 4783521 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 1557256

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 46973
  Valid components after dimensional filtering: 44670
  Components after dimensional filtering: 44670
  Total pore voxels retained: 1681439
After filtering: 1681439 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_09_2/registration_298/image_manifest.csv' loaded with ID: 1256
Image dataset for registration 298 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_09_2/registration_298
Creating image dataset for registration 299 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_09_3/Na_09_3.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_09_3/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 203/203 [00:05<00:00, 39.41it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (203, 5240, 1960)
Data bounding box: Z[0:202], Y[961:4360], X[160:1770]
Cropped volume shape: (203, 3404, 1615)
Applying Sauvola adaptive thresholding...
Volume size: 1.04 GB
Available memory: 194.25 GB
Required memory estimate: 2.08 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 12
Excluding back wall: slices 192 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 5188775 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 1739515

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 52147
  Valid components after dimensional filtering: 49952
  Components after dimensional filtering: 49952
  Total pore voxels retained: 1779811
After filtering: 1779811 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_09_3/registration_299/image_manifest.csv' loaded with ID: 1257
Image dataset for registration 299 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_09_3/registration_299
Creating image dataset for registration 300 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_09_4/Na_09_4.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_09_4/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 196/196 [00:04<00:00, 44.35it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (196, 5240, 1920)
Data bounding box: Z[0:195], Y[987:4386], X[120:1774]
Cropped volume shape: (196, 3404, 1659)
Applying Sauvola adaptive thresholding...
Volume size: 1.03 GB
Available memory: 194.17 GB
Required memory estimate: 2.06 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 7
Excluding back wall: slices 186 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 6242489 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 1062285

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 27953
  Valid components after dimensional filtering: 26708
  Components after dimensional filtering: 26708
  Total pore voxels retained: 4270538
After filtering: 4270538 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_09_4/registration_300/image_manifest.csv' loaded with ID: 1258
Image dataset for registration 300 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_09_4/registration_300
Creating image dataset for registration 301 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_09_5/Na_09_5.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_09_5/volume_eq_aligned_rescaled.tif
Applying transformation

Transforming slices: 100%|██████████| 199/199 [00:04<00:00, 48.66it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (199, 5240, 1920)
Data bounding box: Z[0:198], Y[991:4208], X[111:1798]
Cropped volume shape: (199, 3222, 1692)
Applying Sauvola adaptive thresholding...
Volume size: 1.01 GB
Available memory: 196.52 GB
Required memory estimate: 2.02 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 7
Excluding back wall: slices 185 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 15815914 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 2351733

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 155237
  Valid components after dimensional filtering: 149960
  Components after dimensional filtering: 149960
  Total pore voxels retained: 10999980
After filtering: 10999980 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_09_5/registration_301/image_manifest.csv' loaded with ID: 1259
Image dataset for registration 301 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_09_5/registration_301
Creating image dataset for registration 302 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_10_1/Na_10_1.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_10_1/volume_eq_aligned_rescaled.tif
Applying transformation

Transforming slices: 100%|██████████| 200/200 [00:04<00:00, 43.40it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (200, 5280, 1880)
Data bounding box: Z[0:199], Y[1087:4272], X[132:1758]
Cropped volume shape: (200, 3190, 1631)
Applying Sauvola adaptive thresholding...
Volume size: 0.97 GB
Available memory: 196.60 GB
Required memory estimate: 1.94 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 9
Excluding back wall: slices 193 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 24379448 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 3114445

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 277123
  Valid components after dimensional filtering: 265070
  Components after dimensional filtering: 265070
  Total pore voxels retained: 17679309
After filtering: 17679309 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_10_1/registration_302/image_manifest.csv' loaded with ID: 1260
Image dataset for registration 302 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_10_1/registration_302
Creating image dataset for registration 303 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_10_2/Na_10_2.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_10_2/volume_eq_aligned_rescaled.tif
Applying transformation

Transforming slices: 100%|██████████| 210/210 [00:04<00:00, 44.36it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.

/home/alberto.vicente/miniconda3/envs/prep/lib/python3.14/site-packages/numpy/_core/fromnumeric.py:3824: RuntimeWarning: Mean of empty slice
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/alberto.vicente/miniconda3/envs/prep/lib/python3.14/site-packages/numpy/_core/_methods.py:142: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (210, 5280, 1920)
Data bounding box: Z[0:209], Y[1086:4271], X[159:1806]
Cropped volume shape: (210, 3190, 1652)
Applying Sauvola adaptive thresholding...
Volume size: 1.03 GB
Available memory: 194.78 GB
Required memory estimate: 2.06 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 8
Excluding back wall: slices 194 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 14152483 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 3432304

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 258162
  Valid components after dimensional filtering: 246147
  Components after dimensional filtering: 246147
  Total pore voxels retained: 6642830
After filtering: 6642830 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_10_2/registration_303/image_manifest.csv' loaded with ID: 1261
Image dataset for registration 303 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_10_2/registration_303
Creating image dataset for registration 304 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_10_3/Na_10_3.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_10_3/volume_eq_aligned_rescaled.tif
Applying transformation

Transforming slices: 100%|██████████| 206/206 [00:04<00:00, 42.67it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (206, 5360, 1920)
Data bounding box: Z[0:205], Y[1113:4329], X[125:1801]
Cropped volume shape: (206, 3221, 1681)
Applying Sauvola adaptive thresholding...
Volume size: 1.04 GB
Available memory: 195.68 GB
Required memory estimate: 2.08 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 10
Excluding back wall: slices 196 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 9460594 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 2562823

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 119551
  Valid components after dimensional filtering: 114674
  Components after dimensional filtering: 114674
  Total pore voxels retained: 4164015
After filtering: 4164015 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_10_3/registration_304/image_manifest.csv' loaded with ID: 1262
Image dataset for registration 304 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_10_3/registration_304
Creating image dataset for registration 305 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_10_4/Na_10_4.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_10_4/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 226/226 [00:05<00:00, 38.21it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.

/home/alberto.vicente/miniconda3/envs/prep/lib/python3.14/site-packages/numpy/_core/fromnumeric.py:3824: RuntimeWarning: Mean of empty slice
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/alberto.vicente/miniconda3/envs/prep/lib/python3.14/site-packages/numpy/_core/_methods.py:142: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (226, 5280, 2000)
Data bounding box: Z[0:225], Y[924:4477], X[100:1917]
Cropped volume shape: (226, 3558, 1822)
Applying Sauvola adaptive thresholding...
Volume size: 1.36 GB
Available memory: 189.29 GB
Required memory estimate: 2.73 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 9
Excluding back wall: slices 195 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 9065621 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 414553

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 75849
  Valid components after dimensional filtering: 74025
  Components after dimensional filtering: 74025
  Total pore voxels retained: 8359219
After filtering: 8359219 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_10_4/registration_305/image_manifest.csv' loaded with ID: 1263
Image dataset for registration 305 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_10_4/registration_305
Creating image dataset for registration 306 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_10_5/Na_10_5.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_10_5/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 237/237 [00:05<00:00, 40.12it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.

/home/alberto.vicente/miniconda3/envs/prep/lib/python3.14/site-packages/numpy/_core/fromnumeric.py:3824: RuntimeWarning: Mean of empty slice
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/alberto.vicente/miniconda3/envs/prep/lib/python3.14/site-packages/numpy/_core/_methods.py:142: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (237, 5240, 1880)
Data bounding box: Z[0:236], Y[864:4432], X[14:1865]
Cropped volume shape: (237, 3573, 1856)
Applying Sauvola adaptive thresholding...
Volume size: 1.46 GB
Available memory: 188.32 GB
Required memory estimate: 2.93 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 20
Excluding back wall: slices 205 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 18361568 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 489044

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 97807
  Valid components after dimensional filtering: 94842
  Components after dimensional filtering: 94842
  Total pore voxels retained: 17490679
After filtering: 17490679 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_10_5/registration_306/image_manifest.csv' loaded with ID: 1264
Image dataset for registration 306 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_10_5/registration_306
Creating image dataset for registration 258 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_01_1/Na_01_1.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_01_1/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 208/208 [00:05<00:00, 38.90it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (208, 5280, 1960)
Data bounding box: Z[0:207], Y[1004:4425], X[144:1880]
Cropped volume shape: (208, 3426, 1741)
Applying Sauvola adaptive thresholding...
Volume size: 1.16 GB
Available memory: 191.72 GB
Required memory estimate: 2.31 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 6
Excluding back wall: slices 193 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 23371149 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 1270629

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 227740
  Valid components after dimensional filtering: 224473
  Components after dimensional filtering: 224473
  Total pore voxels retained: 21143848
After filtering: 21143848 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_01_1/registration_258/image_manifest.csv' loaded with ID: 1265
Image dataset for registration 258 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_01_1/registration_258
Creating image dataset for registration 259 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_01_2/Na_01_2.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_01_2/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 210/210 [00:05<00:00, 41.09it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (210, 5320, 2000)
Data bounding box: Z[0:209], Y[993:4445], X[148:1884]
Cropped volume shape: (210, 3457, 1741)
Applying Sauvola adaptive thresholding...
Volume size: 1.18 GB
Available memory: 192.36 GB
Required memory estimate: 2.35 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 7
Excluding back wall: slices 195 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 12575398 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 1545388

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 82687
  Valid components after dimensional filtering: 79848
  Components after dimensional filtering: 79848
  Total pore voxels retained: 9558642
After filtering: 9558642 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_01_2/registration_259/image_manifest.csv' loaded with ID: 1266
Image dataset for registration 259 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_01_2/registration_259
Creating image dataset for registration 260 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_01_3/Na_01_3.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_01_3/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 214/214 [00:05<00:00, 40.87it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (214, 5320, 2000)
Data bounding box: Z[0:213], Y[994:4413], X[172:1857]
Cropped volume shape: (214, 3424, 1690)
Applying Sauvola adaptive thresholding...
Volume size: 1.15 GB
Available memory: 191.20 GB
Required memory estimate: 2.31 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 9
Excluding back wall: slices 196 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 14325790 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 1517885

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 72214
  Valid components after dimensional filtering: 69417
  Components after dimensional filtering: 69417
  Total pore voxels retained: 11357985
After filtering: 11357985 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_01_3/registration_260/image_manifest.csv' loaded with ID: 1267
Image dataset for registration 260 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_01_3/registration_260
Creating image dataset for registration 261 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_01_4/Na_01_4.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_01_4/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 222/222 [00:06<00:00, 36.61it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.

/home/alberto.vicente/miniconda3/envs/prep/lib/python3.14/site-packages/numpy/_core/fromnumeric.py:3824: RuntimeWarning: Mean of empty slice
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/alberto.vicente/miniconda3/envs/prep/lib/python3.14/site-packages/numpy/_core/_methods.py:142: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (222, 5280, 1920)
Data bounding box: Z[0:221], Y[970:4410], X[76:1834]
Cropped volume shape: (222, 3445, 1763)
Applying Sauvola adaptive thresholding...
Volume size: 1.26 GB
Available memory: 189.68 GB
Required memory estimate: 2.51 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 8
Excluding back wall: slices 194 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 22578087 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 1165294

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 167422
  Valid components after dimensional filtering: 164506
  Components after dimensional filtering: 164506
  Total pore voxels retained: 20539655
After filtering: 20539655 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_01_4/registration_261/image_manifest.csv' loaded with ID: 1268
Image dataset for registration 261 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_01_4/registration_261
Creating image dataset for registration 262 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_01_5/Na_01_5.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_01_5/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 208/208 [00:05<00:00, 41.43it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (208, 5280, 1920)
Data bounding box: Z[0:207], Y[926:4351], X[144:1791]
Cropped volume shape: (208, 3430, 1652)
Applying Sauvola adaptive thresholding...
Volume size: 1.10 GB
Available memory: 193.00 GB
Required memory estimate: 2.20 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 7
Excluding back wall: slices 195 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 32793212 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 1658491

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 293298
  Valid components after dimensional filtering: 289084
  Components after dimensional filtering: 289084
  Total pore voxels retained: 29822617
After filtering: 29822617 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_01_5/registration_262/image_manifest.csv' loaded with ID: 1269
Image dataset for registration 262 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_01_5/registration_262
Creating image dataset for registration 263 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_02_1/Na_02_1.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_02_1/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 222/222 [00:05<00:00, 39.04it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (222, 5320, 2120)
Data bounding box: Z[0:221], Y[834:4614], X[0:2119]
Cropped volume shape: (222, 3785, 2120)
Applying Sauvola adaptive thresholding...
Volume size: 1.66 GB
Available memory: 193.20 GB
Required memory estimate: 3.32 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 8
Excluding back wall: slices 210 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 99910784 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 1171513

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 169094
  Valid components after dimensional filtering: 154890
  Components after dimensional filtering: 154890
  Total pore voxels retained: 97448805
After filtering: 97448805 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_02_1/registration_263/image_manifest.csv' loaded with ID: 1270
Image dataset for registration 263 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_02_1/registration_263
Creating image dataset for registration 264 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_02_2/Na_02_2.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_02_2/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 220/220 [00:06<00:00, 34.83it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (220, 5320, 2000)
Data bounding box: Z[0:219], Y[1195:4967], X[0:1999]
Cropped volume shape: (220, 3777, 2000)
Applying Sauvola adaptive thresholding...
Volume size: 1.55 GB
Available memory: 192.94 GB
Required memory estimate: 3.10 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 6
Excluding back wall: slices 207 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 103655675 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 1206274

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 168493
  Valid components after dimensional filtering: 152785
  Components after dimensional filtering: 152785
  Total pore voxels retained: 101100090
After filtering: 101100090 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_02_2/registration_264/image_manifest.csv' loaded with ID: 1271
Image dataset for registration 264 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_02_2/registration_264
Creating image dataset for registration 265 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_02_3/Na_02_3.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_02_3/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 249/249 [00:06<00:00, 39.01it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.

/home/alberto.vicente/miniconda3/envs/prep/lib/python3.14/site-packages/numpy/_core/fromnumeric.py:3824: RuntimeWarning: Mean of empty slice
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/alberto.vicente/miniconda3/envs/prep/lib/python3.14/site-packages/numpy/_core/_methods.py:142: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (249, 5360, 1960)
Data bounding box: Z[0:248], Y[945:4388], X[112:1840]
Cropped volume shape: (249, 3448, 1733)
Applying Sauvola adaptive thresholding...
Volume size: 1.39 GB
Available memory: 186.75 GB
Required memory estimate: 2.77 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 10
Excluding back wall: slices 210 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 106491031 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 1076624

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 155721
  Valid components after dimensional filtering: 141648
  Components after dimensional filtering: 141648
  Total pore voxels retained: 104232257
After filtering: 104232257 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_02_3/registration_265/image_manifest.csv' loaded with ID: 1272
Image dataset for registration 265 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_02_3/registration_265
Creating image dataset for registration 266 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_02_4/Na_02_4.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_02_4/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 225/225 [00:06<00:00, 34.42it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (225, 5240, 1960)
Data bounding box: Z[0:224], Y[929:4599], X[0:1883]
Cropped volume shape: (225, 3675, 1886)
Applying Sauvola adaptive thresholding...
Volume size: 1.45 GB
Available memory: 192.24 GB
Required memory estimate: 2.90 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 13
Excluding back wall: slices 213 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 92758624 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 948139

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 135357
  Valid components after dimensional filtering: 123300
  Components after dimensional filtering: 123300
  Total pore voxels retained: 90794013
After filtering: 90794013 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_02_4/registration_266/image_manifest.csv' loaded with ID: 1273
Image dataset for registration 266 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_02_4/registration_266
Creating image dataset for registration 267 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_02_5/Na_02_5.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_02_5/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 226/226 [00:06<00:00, 36.09it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (226, 5360, 1920)
Data bounding box: Z[0:225], Y[455:4041], X[0:1919]
Cropped volume shape: (226, 3591, 1920)
Applying Sauvola adaptive thresholding...
Volume size: 1.45 GB
Available memory: 197.26 GB
Required memory estimate: 2.90 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 11
Excluding back wall: slices 213 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 82550104 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 875194

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 132369
  Valid components after dimensional filtering: 119155
  Components after dimensional filtering: 119155
  Total pore voxels retained: 80660894
After filtering: 80660894 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_02_5/registration_267/image_manifest.csv' loaded with ID: 1274
Image dataset for registration 267 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_02_5/registration_267
Creating image dataset for registration 268 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_03_1/Na_03_1.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_03_1/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 220/220 [00:05<00:00, 38.94it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.

/home/alberto.vicente/miniconda3/envs/prep/lib/python3.14/site-packages/numpy/_core/fromnumeric.py:3824: RuntimeWarning: Mean of empty slice
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/alberto.vicente/miniconda3/envs/prep/lib/python3.14/site-packages/numpy/_core/_methods.py:142: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (220, 5320, 2080)
Data bounding box: Z[0:219], Y[937:4420], X[141:1955]
Cropped volume shape: (220, 3488, 1819)
Applying Sauvola adaptive thresholding...
Volume size: 1.30 GB
Available memory: 190.88 GB
Required memory estimate: 2.60 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 7
Excluding back wall: slices 180 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 7711823 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 2081065

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 106456
  Valid components after dimensional filtering: 102119
  Components after dimensional filtering: 102119
  Total pore voxels retained: 3477924
After filtering: 3477924 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_03_1/registration_268/image_manifest.csv' loaded with ID: 1275
Image dataset for registration 268 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_03_1/registration_268
Creating image dataset for registration 269 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_03_2/Na_03_2.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_03_2/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 203/203 [00:04<00:00, 41.22it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (203, 5280, 1960)
Data bounding box: Z[0:202], Y[898:4381], X[75:1884]
Cropped volume shape: (203, 3488, 1814)
Applying Sauvola adaptive thresholding...
Volume size: 1.20 GB
Available memory: 193.19 GB
Required memory estimate: 2.39 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 11
Excluding back wall: slices 187 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 3485006 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 1580162

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 36298
  Valid components after dimensional filtering: 34952
  Components after dimensional filtering: 34952
  Total pore voxels retained: 482387
After filtering: 482387 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_03_2/registration_269/image_manifest.csv' loaded with ID: 1276
Image dataset for registration 269 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_03_2/registration_269
Creating image dataset for registration 270 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_03_3/Na_03_3.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_03_3/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 209/209 [00:05<00:00, 41.63it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.

/home/alberto.vicente/miniconda3/envs/prep/lib/python3.14/site-packages/numpy/_core/fromnumeric.py:3824: RuntimeWarning: Mean of empty slice
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/alberto.vicente/miniconda3/envs/prep/lib/python3.14/site-packages/numpy/_core/_methods.py:142: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (209, 5280, 1880)
Data bounding box: Z[0:208], Y[951:4421], X[41:1797]
Cropped volume shape: (209, 3475, 1761)
Applying Sauvola adaptive thresholding...
Volume size: 1.19 GB
Available memory: 192.93 GB
Required memory estimate: 2.38 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 19
Excluding back wall: slices 194 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 1875599 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 822103

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 12618
  Valid components after dimensional filtering: 12034
  Components after dimensional filtering: 12034
  Total pore voxels retained: 406520
After filtering: 406520 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_03_3/registration_270/image_manifest.csv' loaded with ID: 1277
Image dataset for registration 270 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_03_3/registration_270
Creating image dataset for registration 271 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_03_4/Na_03_4.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_03_4/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 196/196 [00:04<00:00, 44.59it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (196, 5280, 1960)
Data bounding box: Z[0:195], Y[946:4398], X[138:1820]
Cropped volume shape: (196, 3457, 1687)
Applying Sauvola adaptive thresholding...
Volume size: 1.06 GB
Available memory: 194.65 GB
Required memory estimate: 2.13 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 9
Excluding back wall: slices 182 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 2725596 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 1196146

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 26777
  Valid components after dimensional filtering: 25088
  Components after dimensional filtering: 25088
  Total pore voxels retained: 408139
After filtering: 408139 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_03_4/registration_271/image_manifest.csv' loaded with ID: 1278
Image dataset for registration 271 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_03_4/registration_271
Creating image dataset for registration 272 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_03_5/Na_03_5.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_03_5/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 185/185 [00:04<00:00, 42.13it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (185, 5320, 1960)
Data bounding box: Z[0:184], Y[939:4436], X[100:1890]
Cropped volume shape: (185, 3502, 1795)
Applying Sauvola adaptive thresholding...
Volume size: 1.08 GB
Available memory: 195.89 GB
Required memory estimate: 2.17 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 7
Excluding back wall: slices 180 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 7228612 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 1316146

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 74383
  Valid components after dimensional filtering: 71076
  Components after dimensional filtering: 71076
  Total pore voxels retained: 4665136
After filtering: 4665136 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_03_5/registration_272/image_manifest.csv' loaded with ID: 1279
Image dataset for registration 272 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_03_5/registration_272
Creating image dataset for registration 273 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_04_1/Na_04_1.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_04_1/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 217/217 [00:05<00:00, 41.81it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.

/home/alberto.vicente/miniconda3/envs/prep/lib/python3.14/site-packages/numpy/_core/fromnumeric.py:3824: RuntimeWarning: Mean of empty slice
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/alberto.vicente/miniconda3/envs/prep/lib/python3.14/site-packages/numpy/_core/_methods.py:142: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (217, 5280, 1920)
Data bounding box: Z[0:216], Y[931:4387], X[71:1830]
Cropped volume shape: (217, 3461, 1764)
Applying Sauvola adaptive thresholding...
Volume size: 1.23 GB
Available memory: 190.79 GB
Required memory estimate: 2.47 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 12
Excluding back wall: slices 188 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 4926222 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 911962

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 27067
  Valid components after dimensional filtering: 26117
  Components after dimensional filtering: 26117
  Total pore voxels retained: 3280660
After filtering: 3280660 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_04_1/registration_273/image_manifest.csv' loaded with ID: 1280
Image dataset for registration 273 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_04_1/registration_273
Creating image dataset for registration 274 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_04_2/Na_04_2.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_04_2/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 203/203 [00:05<00:00, 40.37it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (203, 5320, 1880)
Data bounding box: Z[0:202], Y[925:4394], X[81:1820]
Cropped volume shape: (203, 3474, 1744)
Applying Sauvola adaptive thresholding...
Volume size: 1.15 GB
Available memory: 193.42 GB
Required memory estimate: 2.29 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 9
Excluding back wall: slices 190 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 1848403 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 828573

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 11738
  Valid components after dimensional filtering: 10952
  Components after dimensional filtering: 10952
  Total pore voxels retained: 343951
After filtering: 343951 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_04_2/registration_274/image_manifest.csv' loaded with ID: 1281
Image dataset for registration 274 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_04_2/registration_274
Creating image dataset for registration 275 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_04_3/Na_04_3.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_04_3/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 223/223 [00:05<00:00, 38.99it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.

/home/alberto.vicente/miniconda3/envs/prep/lib/python3.14/site-packages/numpy/_core/fromnumeric.py:3824: RuntimeWarning: Mean of empty slice
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/alberto.vicente/miniconda3/envs/prep/lib/python3.14/site-packages/numpy/_core/_methods.py:142: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (223, 5280, 1920)
Data bounding box: Z[0:222], Y[947:4371], X[133:1787]
Cropped volume shape: (223, 3429, 1659)
Applying Sauvola adaptive thresholding...
Volume size: 1.18 GB
Available memory: 190.85 GB
Required memory estimate: 2.36 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 7
Excluding back wall: slices 188 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 3109983 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 1329955

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 33940
  Valid components after dimensional filtering: 31602
  Components after dimensional filtering: 31602
  Total pore voxels retained: 463984
After filtering: 463984 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_04_3/registration_275/image_manifest.csv' loaded with ID: 1282
Image dataset for registration 275 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_04_3/registration_275
Creating image dataset for registration 276 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_04_4/Na_04_4.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_04_4/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 226/226 [00:05<00:00, 40.17it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.

/home/alberto.vicente/miniconda3/envs/prep/lib/python3.14/site-packages/numpy/_core/fromnumeric.py:3824: RuntimeWarning: Mean of empty slice
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/alberto.vicente/miniconda3/envs/prep/lib/python3.14/site-packages/numpy/_core/_methods.py:142: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (226, 5280, 1920)
Data bounding box: Z[0:225], Y[945:4400], X[111:1835]
Cropped volume shape: (226, 3460, 1729)
Applying Sauvola adaptive thresholding...
Volume size: 1.26 GB
Available memory: 189.53 GB
Required memory estimate: 2.52 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 7
Excluding back wall: slices 187 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 3559283 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 1378986

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 37381
  Valid components after dimensional filtering: 35113
  Components after dimensional filtering: 35113
  Total pore voxels retained: 839805
After filtering: 839805 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_04_4/registration_276/image_manifest.csv' loaded with ID: 1283
Image dataset for registration 276 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_04_4/registration_276
Creating image dataset for registration 277 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_04_5/Na_04_5.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_04_5/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 197/197 [00:04<00:00, 45.42it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (197, 5280, 1880)
Data bounding box: Z[0:196], Y[918:4402], X[78:1841]
Cropped volume shape: (197, 3489, 1768)
Applying Sauvola adaptive thresholding...
Volume size: 1.13 GB
Available memory: 194.13 GB
Required memory estimate: 2.26 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 8
Excluding back wall: slices 186 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 4276236 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 922749

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 51033
  Valid components after dimensional filtering: 49385
  Components after dimensional filtering: 49385
  Total pore voxels retained: 2619487
After filtering: 2619487 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_04_5/registration_277/image_manifest.csv' loaded with ID: 1284
Image dataset for registration 277 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_04_5/registration_277
Creating image dataset for registration 278 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Fabricacion Nacho/probetas/5MHz/Na_05_1/Na_05_1.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Fabricacion Nacho/05_Probetas_Nacho_2025/probetas/Na_05_1/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 194/194 [00:04<00:00, 39.91it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (194, 5280, 1960)
Data bounding box: Z[0:193], Y[886:4402], X[102:1901]
Cropped volume shape: (194, 3521, 1804)
Applying Sauvola adaptive thresholding...
Volume size: 1.15 GB
Available memory: 194.95 GB
Required memory estimate: 2.30 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 2
Excluding back wall: slices 177 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 4317660 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 1169825

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 39962
  Valid components after dimensional filtering: 38724
  Components after dimensional filtering: 38724
  Total pore voxels retained: 2197919
After filtering: 2197919 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_05_1/registration_278/image_manifest.csv' loaded with ID: 1285
Image dataset for registration 278 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/Na_05_1/registration_278
Saved image dataset manifest to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Airbus/Hexcel/2026/5MHz_FedeOnlypores/image_dataset_manifest.csv

,image_kind,image_path,image_shape,image_dtype,file_format,depth_region,sample_id,sample_name,panel_id,panel_name,...,depth_roi_end_exclusive_from_frontwall,depth_roi_end_inclusive_from_frontwall,depth_roi_start_z,depth_roi_end_exclusive_z,depth_roi_end_inclusive_z,material_frontwall_z,material_backwall_z,material_threshold,xct_resolution,ut_resolution
0,ut,/home/alberto.vicente/phd/DataDriven_UT_Albert...,"(448, 85, 39)",uint8,tif,None,73,Na_05_2,9,Na_05,...,"(66, 131, 196)","(65, 130, 195)","(0, 66, 131)","(66, 131, 196)","(65, 130, 195)",0,196,0.8,0.025,1.0
1,volfrac,/home/alberto.vicente/phd/DataDriven_UT_Albert...,"(3, 85, 39)",float32,tif,"(front, middle, back)",73,Na_05_2,9,Na_05,...,"(66, 131, 196)","(65, 130, 195)","(0, 66, 131)","(66, 131, 196)","(65, 130, 195)",0,196,0.8,0.025,1.0
2,areafrac,/home/alberto.vicente/phd/DataDriven_UT_Albert...,"(85, 39)",float32,tif,None,73,Na_05_2,9,Na_05,...,"(66, 131, 196)","(65, 130, 195)","(0, 66, 131)","(66, 131, 196)","(65, 130, 195)",0,196,0.8,0.025,1.0
3,ut,/home/alberto.vicente/phd/DataDriven_UT_Albert...,"(448, 85, 39)",uint8,tif,None,74,Na_05_3,9,Na_05,...,"(67, 133, 199)","(66, 132, 198)","(0, 67, 133)","(67, 133, 199)","(66, 132, 198)",0,199,0.8,0.025,1.0
4,volfrac,/home/alberto.vicente/phd/DataDriven_UT_Albert...,"(3, 85, 39)",float32,tif,"(front, middle, back)",74,Na_05_3,9,Na_05,...,"(67, 133, 199)","(66, 132, 198)","(0, 67, 133)","(67, 133, 199)","(66, 132, 198)",0,199,0.8,0.025,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142,volfrac,/home/alberto.vicente/phd/DataDriven_UT_Albert...,"(3, 87, 41)",float32,tif,"(front, middle, back)",71,Na_04_5,8,Na_04,...,"(66, 132, 197)","(65, 131, 196)","(0, 66, 132)","(66, 132, 197)","(65, 131, 196)",0,197,0.8,0.025,1.0
143,areafrac,/home/alberto.vicente/phd/DataDriven_UT_Albert...,"(87, 41)",float32,tif,None,71,Na_04_5,8,Na_04,...,"(66, 132, 197)","(65, 131, 196)","(0, 66, 132)","(66, 132, 197)","(65, 131, 196)",0,197,0.8,0.025,1.0
144,ut,/home/alberto.vicente/phd/DataDriven_UT_Albert...,"(448, 87, 42)",uint8,tif,None,72,Na_05_1,9,Na_05,...,"(65, 130, 194)","(64, 129, 193)","(0, 65, 130)","(65, 130, 194)","(64, 129, 193)",0,194,0.8,0.025,1.0
145,volfrac,/home/alberto.vicente/phd/DataDriven_UT_Albert...,"(3, 87, 42)",float32,tif,"(front, middle, back)",72,Na_05_1,9,Na_05,...,"(65, 130, 194)","(64, 129, 193)","(0, 65, 130)","(65, 130, 194)","(64, 129, 193)",0,194,0.8,0.025,1.0
146,areafrac,/home/alberto.vicente/phd/DataDriven_UT_Albert...,"(87, 42)",float32,tif,None,72,Na_05_1,9,Na_05,...,"(65, 130, 194)","(64, 129, 193)","(0, 65, 130)","(65, 130, 194)","(64, 129, 193)",0,194,0.8,0.025,1.0

# Recompose global manifest from per-registration manifests

Run this cell independently to rebuild `image_dataset_manifest.csv` from scratch by scanning all `image_manifest.csv` files already on disk. Useful if the global manifest is missing, corrupted, or out of sync with the per-registration files (e.g. after a partial run or manual deletion).

Set `recompose_folder` to the root images folder if running outside the notebook flow.

In [35]:
# recompose_folder = folder  # change if running standalone

# per_registration_manifests = sorted(recompose_folder.glob('*/registration_*/image_manifest.csv'))
# print(f"Found {len(per_registration_manifests)} per-registration manifests")

# recomposed_df = pd.concat(
#     [pd.read_csv(p) for p in per_registration_manifests],
#     ignore_index=True,
# )

# recompose_manifest_path = recompose_folder / 'image_dataset_manifest.csv'
# recomposed_df.to_csv(recompose_manifest_path, index=False)

# print(f"Recomposed manifest saved to {recompose_manifest_path} ({len(recomposed_df)} rows)")
# recomposed_df