# imports

In [1]:
import sys
project_root = r'/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing'
if project_root not in sys.path:
    sys.path.append(project_root)
import importlib
from preprocess_tools import onlypores, datasetmaker, io, aligner, register
datasetmaker = importlib.reload(datasetmaker)
import numpy as np
import pandas as pd
import tifffile
from dbtools import dbtools as db
from dbtools import load as load
from pathlib import Path
import ast

# Path mapping

In [2]:
LOCAL_DATA_ROOT = Path('/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente')
UNC_DATA_ROOT = r'\\192.168.10.106\imdea\DataDriven_UT_AlbertoVicente'


def resolve_data_path(path, must_exist=True):
    path_str = str(path).strip()
    direct_path = Path(path_str)

    try:
        direct_exists = direct_path.exists()
    except OSError:
        direct_exists = False

    if direct_exists:
        return direct_path

    normalized_path = path_str.replace('\\', '/')
    normalized_unc_root = UNC_DATA_ROOT.replace('\\', '/')

    if normalized_path.lower().startswith(normalized_unc_root.lower()):
        relative_path = normalized_path[len(normalized_unc_root):].lstrip('/')
        local_path = LOCAL_DATA_ROOT / relative_path
        if local_path.exists() or not must_exist:
            return local_path

    if must_exist:
        raise FileNotFoundError(
            f"Could not resolve data path: {path_str}\n"
            f"Tried direct path and UNC mapping to: {LOCAL_DATA_ROOT}"
        )

    return direct_path

# Database connection

In [3]:
try:
    conn = db.connect()
    print("Connected to the database")
except Exception as error:
    print(error)

Connected to the database

# Select measurements to create the image datasets

## Measurement type

In [4]:
measurementtypes_table = db.get_data_metadata('measurementtypes')

measurementtypes_table

,id_measurementtype,name_measurementtype,description_measurementtype,technique_measurementtype,equipment_measurementtype,transducer_name_measurementtype,transducer_nominal_freq_measurementtype,transducer_diameter_measurementtype,transducer_focal_length_measurementtype,z_resolution_measurementtype,...,projections_measurementtype,target_measurementtype,filter_measurementtype,Detector_measurementtype,scaling_measurementtype,power_measurementtype,DAC_measurementtype,lens_measurementtype,lens_focal_length_measurementtype,transducer_measurementtype
0,5,Monoelement Ultrasound Pulse Echo 1,NaN,Ultrasound Monoelement Pulse Echo nominal,TRITON 1000P nominal,Technisonic ISL-0503-HR nominal,5 MHz,9.525 mm,76.2 mm,0.02232141 mm,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,6,XCT 1,NaN,X-Ray Computed Tomography nominal,ZEISS Xradia Versa 620 nominal,NaN,NaN,NaN,NaN,NaN,...,3738 cardinal,wolframio nominal,LE1 nominal,Flat Panel nominal,"[-1.700072,1.841701] float array",4.5 W,NaN,NaN,NaN,NaN
2,7,Monoelement Ultrasound Pulse Echo Airbus DAC,NaN,Ultrasound Monoelement Pulse Echo nominal,TRITON 1000P nominal,Technisonic ISL-0503-HR nominal,5 MHz,9.525 mm,76.2 mm,0.02232141 mm,...,NaN,NaN,NaN,NaN,NaN,NaN,"[[10.1,4.33],[12.1,6.18],[19.7,10.38],[26.7,15...",NaN,NaN,NaN
3,8,Monoelement Ultrasound Pulse Echo Low Resolution,NaN,Ultrasound Monoelement Pulse Echo nominal,TRITON 1000P nominal,Technisonic ISL-0503-HR nominal,5 MHz,9.525 mm,76.2 mm,0.05940588 mm,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,9,Placeholder Measurement Type,A generic placeholder for a measurement techni...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,10,Monoelement Ultrasound Pulse Echo Airbus DAC L...,NaN,Ultrasound Monoelement Pulse Echo nominal,TRITON 1000P nominal,Technisonic ISL-0503-HR nominal,5 MHz,9.525 mm,42 mm,0.02232141 mm,...,NaN,NaN,NaN,NaN,NaN,NaN,"[[10.1,4.33],[12.1,6.18],[19.7,10.38],[26.7,15...",True bool,"38,1 mm",NaN
6,11,Monoelement Ultrasound Pulse Echo Na,NaN,Ultrasound Monoelement Pulse Echo nominal,TRITON 1000P nominal,NaN,5 MHz,9.525 mm,76.2 mm,0.02232141 mm,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Technisonic ISL-0503-HR nominal

In [6]:
ut_type = 5

xct_type = 6

## Selecting UT measurements

In [7]:
ut_measurements_table = db.get_data_metadata('measurements')

ut_measurements_table = ut_measurements_table[ut_measurements_table['measurementtype_id_measurement'] == ut_type]

ut_measurements_table

,id_measurement,file_path_measurement,parent_measurement_id_measurement,measurementtype_id_measurement,height_measurement,width_measurement,depth_measurement,dtype_measurement,file_type_measurement,aligned_measurement,equalized_measurement,axes_order_measurement,transformations_measurement,signal_type_measurement,actual_voxel_size_measurement,raw_file_path_measurement,raw_dtype_measurement,raw_byte_order_measurement,raw_shape_zyx_measurement
1,93,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,NaN,5,448 cardinal,190 cardinal,492 cardinal,uint8 nominal,.tif nominal,NaN,NaN,"['z', 'y', 'x'] list",NaN,RF nominal,NaN,NaN,NaN,NaN,NaN
85,94,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,93.0,5,448 cardinal,125 cardinal,48 cardinal,uint8 nominal,.tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped region containing only the sample. text,RF nominal,NaN,NaN,NaN,NaN,NaN
86,95,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,93.0,5,505 cardinal,131 cardinal,47 cardinal,uint8 nominal,.tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped region containing the sample only text,RF nominal,NaN,NaN,NaN,NaN,NaN
87,96,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,93.0,5,448 cardinal,126 cardinal,51 cardinal,uint8 nominal,.tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped region containing the sample only text,RF nominal,NaN,NaN,NaN,NaN,NaN
88,97,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,93.0,5,448 cardinal,125 cardinal,51 cardinal,uint8 nominal,.tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped region containing the sample only text,RF nominal,NaN,NaN,NaN,NaN,NaN
89,98,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,93.0,5,448 cardinal,126 cardinal,49 cardinal,uint8 nominal,.tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped region containing the sample only text,RF nominal,NaN,NaN,NaN,NaN,NaN
90,99,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,93.0,5,448 cardinal,125 cardinal,50 cardinal,uint8 nominal,.tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped region containing the sample only text,RF nominal,NaN,NaN,NaN,NaN,NaN
91,100,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,93.0,5,448 cardinal,121 cardinal,49 cardinal,uint8 nominal,.tif nominal,NaN,NaN,"['z', 'y', 'x'] list",Cropped region containing the sample only text,RF nominal,NaN,NaN,NaN,NaN,NaN

## Selecting XCT measurements

In [8]:
xct_measurements_table = db.get_data_metadata('measurements')

xct_measurements_table = xct_measurements_table[xct_measurements_table['measurementtype_id_measurement'] == xct_type]

xct_measurements_table

,id_measurement,file_path_measurement,parent_measurement_id_measurement,measurementtype_id_measurement,height_measurement,width_measurement,depth_measurement,dtype_measurement,file_type_measurement,aligned_measurement,equalized_measurement,axes_order_measurement,transformations_measurement,signal_type_measurement,actual_voxel_size_measurement,raw_file_path_measurement,raw_dtype_measurement,raw_byte_order_measurement,raw_shape_zyx_measurement
0,253,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,252.0,6,3411 cardinal,1908 cardinal,1117 cardinal,uint8 string,folder string,False bool,True bool,"['x', 'y', 'z'] list",Volume equalized with this parameters: Referen...,NaN,NaN,NaN,NaN,NaN,NaN
2,101,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,NaN,6,3737 cardinal,1770 cardinal,1015 cardinal,uint16 string,folder string,NaN,NaN,"['x', 'y', 'z'] list",NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,102,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,101.0,6,3224 cardinal,1770 cardinal,1015 cardinal,uint8 string,folder string,False bool,True bool,"['x', 'y', 'z'] list",Volume equalized with this parameters:\r\n\r\n...,NaN,NaN,NaN,NaN,NaN,NaN
4,103,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,NaN,6,3735 cardinal,1734 cardinal,1003 cardinal,uint16 string,folder string,False bool,False bool,"['x', 'y', 'z'] list",NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,104,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,103.0,6,3226 cardinal,1734 cardinal,1003 cardinal,uint8 string,folder string,False bool,True bool,"['x', 'y', 'z'] list",Volume equalized with this parameters: \r\n\r\...,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
330,532,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,482.0,6,237 cardinal,3478 cardinal,1649 cardinal,uint8 string,tif string,True bool,True bool,"['z', 'y', 'x'] list","Frontwall aligned with axes, rotated 90 degree...",NaN,NaN,NaN,NaN,NaN,NaN
391,606,/home/alberto.vicente/phd/DataDriven_UT_Albert...,527.0,6,199 cardinal,3172 cardinal,1593 cardinal,uint8 string,tif string,True bool,True bool,"['z', 'y', 'x'] list",Downscaled from 0.0206 mm/voxel to 0.025 mm/vo...,NaN,NaN,NaN,NaN,NaN,NaN
392,607,/home/alberto.vicente/phd/DataDriven_UT_Albert...,528.0,6,200 cardinal,3172 cardinal,1599 cardinal,uint8 string,tif string,True bool,True bool,"['z', 'y', 'x'] list",Downscaled from 0.0206 mm/voxel to 0.025 mm/vo...,NaN,NaN,NaN,NaN,NaN,NaN
393,608,/home/alberto.vicente/phd/DataDriven_UT_Albert...,529.0,6,210 cardinal,3172 cardinal,1619 cardinal,uint8 string,tif string,True bool,True bool,"['z', 'y', 'x'] list",Downscaled from 0.0206 mm/voxel to 0.025 mm/vo...,NaN,NaN,NaN,NaN,NaN,NaN
394,609,/home/alberto.vicente/phd/DataDriven_UT_Albert...,530.0,6,206 cardinal,3173 cardinal,1585 cardinal,uint8 string,tif string,True bool,True bool,"['z', 'y', 'x'] list",Downscaled from 0.0206 mm/voxel to 0.025 mm/vo...,NaN,NaN,NaN,NaN,NaN,NaN

## Getting registered pairs

In [9]:
registrations_table = db.get_data_metadata('registrations')

registrations_table = registrations_table[registrations_table['reference_measurement_id_registration'].isin(ut_measurements_table['id_measurement'])]

registrations_table = registrations_table[registrations_table['registered_measurement_id_registration'].isin(xct_measurements_table['id_measurement'])]

registrations_table

,id_registration,reference_measurement_id_registration,registered_measurement_id_registration,registration_matrix_registration,description_registration,type_registration,axes_registration
0,48,94,107,"[[0.9999496101957784, -0.010038778277827542, -...",NaN,"Alberto 2024 registration method, UTvsXCTPrepr...","['x', 'y'] list"
1,49,95,110,"[[0.9989887888960844, -0.04495997842452192, -1...",NaN,"Alberto 2024 registration method, UTvsXCTPrepr...","['x', 'y'] list"
2,50,96,122,"[[0.9970851454944588, -0.07629687172022587, -8...",NaN,"Alberto 2024 registration method, UTvsXCTPrepr...","['x', 'y'] list"
3,51,97,121,"[[0.9966117166320059, -0.08225014450933457, -8...",NaN,"Alberto 2024 registration method, UTvsXCTPrepr...","['x', 'y'] list"
4,52,98,116,"[[0.9997579495659881, -0.022000960879274396, -...",NaN,"Alberto 2024 registration method, UTvsXCTPrepr...","['x', 'y'] list"
5,53,99,118,"[[0.9998347517133233, -0.018178813667514962, -...",NaN,"Alberto 2024 registration method, UTvsXCTPrepr...","['x', 'y'] list"
6,54,100,120,"[[0.9999771002825074, 0.006767489238134916, -6...",NaN,"Alberto 2024 registration method, UTvsXCTPrepr...","['x', 'y'] list"

## Sample and panel metadata

In [10]:
sample_measurements_table = db.relation_metadata('samples', 'measurements', 'sample_measurements')
samples_table = db.get_data_metadata('samples')
panels_table = db.get_data_metadata('panels')

sample_measurements_table

,id_sample,name_sample,description_sample,panel_id_sample,height_sample,width_sample,thickness_sample,keyhole_sample,parallel_faces_sample,Missing_sample,...,aligned_measurement,equalized_measurement,axes_order_measurement,transformations_measurement,signal_type_measurement,actual_voxel_size_measurement,raw_file_path_measurement,raw_dtype_measurement,raw_byte_order_measurement,raw_shape_zyx_measurement
0,9,JI_4,NaN,3,150.0 mm,50.0 mm,5.0 mm,True bool,True bool,NaN,...,NaN,NaN,"['z', 'y', 'x'] list",NaN,RF nominal,NaN,NaN,NaN,NaN,NaN
1,9,JI_4,NaN,3,150.0 mm,50.0 mm,5.0 mm,True bool,True bool,NaN,...,NaN,NaN,"['z', 'y', 'x'] list",Cropped region containing only the sample. text,RF nominal,NaN,NaN,NaN,NaN,NaN
2,9,JI_4,NaN,3,150.0 mm,50.0 mm,5.0 mm,True bool,True bool,NaN,...,NaN,NaN,"['x', 'y', 'z'] list",NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,9,JI_4,NaN,3,150.0 mm,50.0 mm,5.0 mm,True bool,True bool,NaN,...,False bool,True bool,"['x', 'y', 'z'] list",Volume equalized with this parameters:\r\n\r\n...,NaN,NaN,NaN,NaN,NaN,NaN
4,9,JI_4,NaN,3,150.0 mm,50.0 mm,5.0 mm,True bool,True bool,NaN,...,False bool,True bool,"['x', 'y', 'z'] list",Cropped to region that contains the sample onl...,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
625,101,Na_10_5,NaN,14,150 mm,40 mm,5 mm,True bool,True bool,NaN,...,False bool,True bool,"['x', 'y', 'z'] list",Volume equalized with this parameters: Referen...,NaN,NaN,NaN,NaN,NaN,NaN
626,101,Na_10_5,NaN,14,150 mm,40 mm,5 mm,True bool,True bool,NaN,...,False bool,True bool,"['x', 'y', 'z'] list",Isolated from a volume conatining more samples...,NaN,NaN,NaN,NaN,NaN,NaN
627,101,Na_10_5,NaN,14,150 mm,40 mm,5 mm,True bool,True bool,NaN,...,True bool,True bool,"['z', 'y', 'x'] list","Frontwall aligned with axes, rotated 90 degree...",NaN,NaN,NaN,NaN,NaN,NaN
628,101,Na_10_5,NaN,14,150 mm,40 mm,5 mm,True bool,True bool,NaN,...,NaN,NaN,"['z', 'y', 'x'] list",NaN,RF nominal,NaN,/home/alberto.vicente/phd/DataDriven_UT_Albert...,uint8 nominal,little nominal,"(448, 161, 264) nominal"
629,101,Na_10_5,NaN,14,150 mm,40 mm,5 mm,True bool,True bool,NaN,...,NaN,NaN,"['z', 'y', 'x'] list",Cropped to region containing only the sample text,RF nominal,NaN,NaN,NaN,NaN,NaN

In [11]:
def lookup_sample_metadata(measurement_id):
    sample_rows = sample_measurements_table[sample_measurements_table['id_measurement'] == measurement_id]
    if sample_rows.empty:
        return {
            'sample_id': None,
            'sample_name': None,
            'panel_id': None,
            'panel_name': None,
        }

    sample_row = sample_rows.iloc[0]
    sample_id = sample_row.get('id_sample')
    sample_name = sample_row.get('name_sample')
    panel_id = sample_row.get('panel_id_sample')

    if pd.isna(panel_id) and sample_id is not None:
        matching_samples = samples_table[samples_table['id_sample'] == sample_id]
        if not matching_samples.empty:
            panel_id = matching_samples.iloc[0].get('panel_id_sample')

    panel_name = None
    if panel_id is not None and not pd.isna(panel_id):
        matching_panels = panels_table[panels_table['id_panel'] == panel_id]
        if not matching_panels.empty:
            panel_name = matching_panels.iloc[0].get('name_panel')

    return {
        'sample_id': sample_id,
        'sample_name': sample_name,
        'panel_id': panel_id,
        'panel_name': panel_name,
    }


registered_pairs = []

for _, registration in registrations_table.iterrows():
    reference_id = registration['reference_measurement_id_registration']
    registered_id = registration['registered_measurement_id_registration']

    reference_measurement = ut_measurements_table[ut_measurements_table['id_measurement'] == reference_id].iloc[0]
    registered_measurement = xct_measurements_table[xct_measurements_table['id_measurement'] == registered_id].iloc[0]
    sample_metadata = lookup_sample_metadata(reference_id)

    registered_pairs.append({
        'registration_id': registration['id_registration'],
        'reference_measurement_id': reference_id,
        'registered_measurement_id': registered_id,
        'reference_measurement_path': reference_measurement['file_path_measurement'],
        'registered_measurement_path': registered_measurement['file_path_measurement'],
        'sample_id': sample_metadata['sample_id'],
        'sample_name': sample_metadata['sample_name'],
        'panel_id': sample_metadata['panel_id'],
        'panel_name': sample_metadata['panel_name'],
    })

registered_pairs_df = pd.DataFrame(registered_pairs)

print(f"Found {len(registered_pairs_df)} registrations")
registered_pairs_df

Found 7 registrations

,registration_id,reference_measurement_id,registered_measurement_id,reference_measurement_path,registered_measurement_path,sample_id,sample_name,panel_id,panel_name
0,48,94,107,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,9,JI_4,3,Juan_Ignacio_placeholder
1,49,95,110,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,10,JI_5,3,Juan_Ignacio_placeholder
2,50,96,122,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,11,JI_7,3,Juan_Ignacio_placeholder
3,51,97,121,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,12,JI_8,3,Juan_Ignacio_placeholder
4,52,98,116,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,14,JI_10,3,Juan_Ignacio_placeholder
5,53,99,118,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,15,JI_11,3,Juan_Ignacio_placeholder
6,54,100,120,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,\\192.168.10.106\imdea\DataDriven_UT_AlbertoVi...,16,JI_12,3,Juan_Ignacio_placeholder

# Dataset type selection

In [12]:
datasettype_table = db.get_data('datasettypes')

datasettype_table

   id_datasettype                            description_datasettype
0               4  2024 Dataset Type. Material mask computed usin...
1               3  2025 Dataset Type. Material mask computed usin...
2               5  Placeholder Dataset Type: A generic category f...
3               6  2025 Dataset Type. Material mask computed usin...
4               8  2026 Conical Dataset Type. Material mask compu...
5               7  2026 Dataset Type. Material mask computed usin...
6               9  2026 reference signal dataset, reference signa...
7              10  2026 Dataset Type. Material mask computed usin...

In [13]:
datasettype = 10
load_into_database = True

# Discard already computed datasets

In [14]:
if datasettype is not None:
    try:
        dataset_registrations_table = db.relation_metadata('datasets', 'registrations', 'dataset_registrations')

        dataset_registrations_table = dataset_registrations_table[dataset_registrations_table['datasettype_id_dataset'] == datasettype]

        dataset_registrations = dataset_registrations_table['id_registration'].values

    except Exception as e:
        print("No dataset registrations found or error occurred:", e)
        dataset_registrations = []
else:
    dataset_registrations = []

# Saving folder

In [15]:
folder = Path(r'/home/alberto.vicente/phd//DataDriven_UT_AlbertoVicente/04_ML_data/Juan Ignacio/2026/5MHz_FedeOnlypores')

folder.mkdir(parents=True, exist_ok=True)

# Image settings

In [16]:
material_threshold = 0.8
stop_after_first = False
sauvola_radius = 15
sauvola_k = 0.2

# Resolutions

In [17]:
xct_resolution = float(measurementtypes_table[measurementtypes_table['id_measurementtype'] == xct_type]['voxel_size_measurementtype'].values[0].split(' ')[0])
ut_resolution = float(measurementtypes_table[measurementtypes_table['id_measurementtype'] == ut_type]['x_resolution_measurementtype'].values[0].split(' ')[0])
print(f"XCT resolution: {xct_resolution}, UT resolution: {ut_resolution}")

XCT resolution: 0.025, UT resolution: 1.0

# Dataset generation

In [18]:
excluded_samples = []

manifest_rows = []

for _, pair in registered_pairs_df.iterrows():
    reference_measurement_path_raw = pair['reference_measurement_path']
    registered_measurement_path_raw = pair['registered_measurement_path']
    registration_id = pair['registration_id']
    sample_name = pair['sample_name']
    sample_folder_name = sample_name if pd.notna(sample_name) else f"registration_{registration_id}"

    if sample_name in excluded_samples:
        print(f"Sample {sample_name} is in the exclusion list, skipping...")
        continue

    if registration_id in dataset_registrations:
        print(f"Dataset for registration {registration_id} already exists, skipping...")
        continue

    reference_measurement_path = resolve_data_path(reference_measurement_path_raw)
    registered_measurement_path = resolve_data_path(registered_measurement_path_raw)

    print(f"Creating image dataset for registration {registration_id} with reference measurement {reference_measurement_path} and registered measurement {registered_measurement_path}")

    ut_volume = io.load_tif(reference_measurement_path)
    xct_volume = io.load_tif(registered_measurement_path)

    xct_volume = np.transpose(xct_volume, (1, 2, 0))
    ut_volume = np.transpose(ut_volume, (1, 2, 0))

    registration_parameters = registrations_table[registrations_table['id_registration'] == registration_id]['registration_matrix_registration'].values[0]
    registration_parameters = np.array(ast.literal_eval(registration_parameters))

    xct_volume = register.apply_registration(ut_volume, xct_volume, registration_parameters, ut_resolution, xct_resolution, parallel=True)

    _, frontwall, backwall = aligner.crop_walls(xct_volume)

    xct_volume = np.transpose(xct_volume, (2, 0, 1))
    ut_volume = np.transpose(ut_volume, (2, 0, 1))

    onlypores_volume, material_mask, _ = onlypores.onlypores(xct_volume, frontwall, backwall, min_size_filtering=8)

    dataset_folder = folder / f"{sample_folder_name}" / f"registration_{registration_id}"
    dataset_folder.mkdir(parents=True, exist_ok=True)

    ut_image, volfrac_maps, areafrac_image, depth_rois = datasetmaker.main_images(
        onlypores_volume,
        material_mask,
        ut_volume,
        xct_resolution,
        ut_resolution,
        material_threshold=material_threshold,
    )

    depth_roi_regions = tuple(roi['region'] for roi in depth_rois)
    depth_roi_start_from_frontwall = tuple(roi['start_from_frontwall'] for roi in depth_rois)
    depth_roi_end_exclusive_from_frontwall = tuple(roi['end_exclusive_from_frontwall'] for roi in depth_rois)
    depth_roi_end_inclusive_from_frontwall = tuple(roi['end_inclusive_from_frontwall'] for roi in depth_rois)
    depth_roi_start_z = tuple(roi['start_z'] for roi in depth_rois)
    depth_roi_end_exclusive_z = tuple(roi['end_exclusive_z'] for roi in depth_rois)
    depth_roi_end_inclusive_z = tuple(roi['end_inclusive_z'] for roi in depth_rois)
    material_frontwall_z = depth_rois[0]['material_frontwall_z']
    material_backwall_z = depth_rois[0]['material_backwall_z']

    image_outputs = {
        'ut': (dataset_folder / 'ut_volume.tif', ut_image, None),
        'volfrac': (dataset_folder / 'volfrac_maps.tif', volfrac_maps.astype(np.float32), depth_roi_regions),
        'areafrac': (dataset_folder / 'areafrac_map.tif', areafrac_image.astype(np.float32), None),
    }

    current_rows = []
    for image_kind, (image_path, image_array, depth_region) in image_outputs.items():
        tifffile.imwrite(image_path, image_array, bigtiff=True)
        current_rows.append({
            'image_kind': image_kind,
            'image_path': str(image_path),
            'image_shape': tuple(image_array.shape),
            'image_dtype': str(image_array.dtype),
            'file_format': 'tif',
            'depth_region': depth_region,
            'sample_id': pair['sample_id'],
            'sample_name': sample_name,
            'panel_id': pair['panel_id'],
            'panel_name': pair['panel_name'],
            'registration_id': registration_id,
            'reference_measurement_id': pair['reference_measurement_id'],
            'registered_measurement_id': pair['registered_measurement_id'],
            'reference_measurement_path': str(reference_measurement_path),
            'registered_measurement_path': str(registered_measurement_path),
            'reference_measurement_path_raw': reference_measurement_path_raw,
            'registered_measurement_path_raw': registered_measurement_path_raw,
            'ut_image_shape': tuple(ut_image.shape),
            'target_map_shape': tuple(volfrac_maps.shape[1:]),
            'volfrac_maps_shape': tuple(volfrac_maps.shape),
            'volfrac_region_names': depth_roi_regions,
            'depth_roi_start_from_frontwall': depth_roi_start_from_frontwall,
            'depth_roi_end_exclusive_from_frontwall': depth_roi_end_exclusive_from_frontwall,
            'depth_roi_end_inclusive_from_frontwall': depth_roi_end_inclusive_from_frontwall,
            'depth_roi_start_z': depth_roi_start_z,
            'depth_roi_end_exclusive_z': depth_roi_end_exclusive_z,
            'depth_roi_end_inclusive_z': depth_roi_end_inclusive_z,
            'material_frontwall_z': material_frontwall_z,
            'material_backwall_z': material_backwall_z,
            'material_threshold': material_threshold,
            'xct_resolution': xct_resolution,
            'ut_resolution': ut_resolution,
        })

    registration_manifest_df = pd.DataFrame(current_rows)
    registration_manifest_path = dataset_folder / 'image_manifest.csv'
    registration_manifest_df.to_csv(registration_manifest_path, index=False)
    manifest_rows.extend(current_rows)

    if load_into_database and datasettype is not None:
        rows = int(np.prod(volfrac_maps.shape))
        targets = ['volfrac_front', 'volfrac_middle', 'volfrac_back', 'areafrac']
        description = 'Image-shaped dataset without UT patches, created with preprocess tools v 0.1.23'

        load.load_dataset(
            conn,
            datasettype_id=datasettype,
            file_path=str(registration_manifest_path),
            rows=rows,
            patch_size='no_ut_patches',
            targets=targets,
            reconstruction_shape=volfrac_maps.shape,
            registration_ids=[registration_id],
            description=description,
        )

    print(f"Image dataset for registration {registration_id} saved to {dataset_folder}")

    if stop_after_first:
        break

manifest_df = pd.DataFrame(manifest_rows)
manifest_path = folder / 'image_dataset_manifest.csv'

if manifest_path.exists() and not manifest_df.empty:
    existing_manifest_df = pd.read_csv(manifest_path)
    updated_ids = manifest_df['registration_id'].unique()
    existing_manifest_df = existing_manifest_df[~existing_manifest_df['registration_id'].isin(updated_ids)]
    manifest_df = pd.concat([existing_manifest_df, manifest_df], ignore_index=True)
elif manifest_path.exists():
    manifest_df = pd.read_csv(manifest_path)

manifest_df.to_csv(manifest_path, index=False)

print(f"Saved image dataset manifest to {manifest_path}")
manifest_df

Creating image dataset for registration 48 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Probetas JI/probetas/2025 methodology/4/4.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/4/volume_eq_rotated_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 203/203 [00:04<00:00, 40.62it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (203, 5000, 1920)
Data bounding box: Z[0:202], Y[886:4126], X[146:1785]
Cropped volume shape: (203, 3245, 1644)
Applying Sauvola adaptive thresholding...
Volume size: 1.01 GB
Available memory: 201.77 GB
Required memory estimate: 2.02 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 8
Excluding back wall: slices 175 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 5923217 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 38242

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 3096
  Valid components after dimensional filtering: 2765
  Components after dimensional filtering: 2765
  Total pore voxels retained: 5842785
After filtering: 5842785 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Juan Ignacio/2026/5MHz_FedeOnlypores/JI_4/registration_48/image_manifest.csv' loaded with ID: 1286
Image dataset for registration 48 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Juan Ignacio/2026/5MHz_FedeOnlypores/JI_4/registration_48
Creating image dataset for registration 49 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Probetas JI/probetas/2025 methodology/5/5.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/5/volume_eq_rotated_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 192/192 [00:04<00:00, 45.57it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (192, 5240, 1880)
Data bounding box: Z[0:191], Y[1021:4315], X[52:1821]
Cropped volume shape: (192, 3299, 1774)
Applying Sauvola adaptive thresholding...
Volume size: 1.05 GB
Available memory: 199.35 GB
Required memory estimate: 2.09 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 8
Excluding back wall: slices 177 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 7320495 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 86946

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 5354
  Valid components after dimensional filtering: 4717
  Components after dimensional filtering: 4717
  Total pore voxels retained: 7152393
After filtering: 7152393 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Juan Ignacio/2026/5MHz_FedeOnlypores/JI_5/registration_49/image_manifest.csv' loaded with ID: 1287
Image dataset for registration 49 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Juan Ignacio/2026/5MHz_FedeOnlypores/JI_5/registration_49
Creating image dataset for registration 50 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Probetas JI/probetas/2025 methodology/7/7.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/7/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 196/196 [00:04<00:00, 44.81it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (196, 5040, 2040)
Data bounding box: Z[0:195], Y[892:4236], X[77:2001]
Cropped volume shape: (196, 3349, 1929)
Applying Sauvola adaptive thresholding...
Volume size: 1.18 GB
Available memory: 197.40 GB
Required memory estimate: 2.36 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 7
Excluding back wall: slices 173 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 4668020 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 103695

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 2957
  Valid components after dimensional filtering: 2001
  Components after dimensional filtering: 2001
  Total pore voxels retained: 4466038
After filtering: 4466038 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Juan Ignacio/2026/5MHz_FedeOnlypores/JI_7/registration_50/image_manifest.csv' loaded with ID: 1288
Image dataset for registration 50 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Juan Ignacio/2026/5MHz_FedeOnlypores/JI_7/registration_50
Creating image dataset for registration 51 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Probetas JI/probetas/2025 methodology/8/8.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/8/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 202/202 [00:04<00:00, 41.50it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (202, 5000, 2040)
Data bounding box: Z[0:201], Y[888:4239], X[91:2009]
Cropped volume shape: (202, 3356, 1923)
Applying Sauvola adaptive thresholding...
Volume size: 1.21 GB
Available memory: 197.18 GB
Required memory estimate: 2.43 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 8
Excluding back wall: slices 176 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 8993460 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 75245

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 5781
  Valid components after dimensional filtering: 4947
  Components after dimensional filtering: 4947
  Total pore voxels retained: 8859173
After filtering: 8859173 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Juan Ignacio/2026/5MHz_FedeOnlypores/JI_8/registration_51/image_manifest.csv' loaded with ID: 1289
Image dataset for registration 51 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Juan Ignacio/2026/5MHz_FedeOnlypores/JI_8/registration_51
Creating image dataset for registration 52 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Probetas JI/probetas/2025 methodology/10/10.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/10/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 205/205 [00:04<00:00, 44.03it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (205, 5040, 1960)
Data bounding box: Z[0:204], Y[1011:4270], X[188:1836]
Cropped volume shape: (205, 3264, 1653)
Applying Sauvola adaptive thresholding...
Volume size: 1.03 GB
Available memory: 197.63 GB
Required memory estimate: 2.06 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 7
Excluding back wall: slices 173 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 11259084 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 2245402

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 138778
  Valid components after dimensional filtering: 133100
  Components after dimensional filtering: 133100
  Total pore voxels retained: 6453999
After filtering: 6453999 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Juan Ignacio/2026/5MHz_FedeOnlypores/JI_10/registration_52/image_manifest.csv' loaded with ID: 1290
Image dataset for registration 52 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Juan Ignacio/2026/5MHz_FedeOnlypores/JI_10/registration_52
Creating image dataset for registration 53 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Probetas JI/probetas/2025 methodology/11/11.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/11/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 203/203 [00:04<00:00, 43.14it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (203, 5000, 2000)
Data bounding box: Z[0:202], Y[919:4174], X[205:1860]
Cropped volume shape: (203, 3260, 1660)
Applying Sauvola adaptive thresholding...
Volume size: 1.02 GB
Available memory: 197.01 GB
Required memory estimate: 2.05 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 12
Excluding back wall: slices 180 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 11863884 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 2317214

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 142438
  Valid components after dimensional filtering: 136279
  Components after dimensional filtering: 136279
  Total pore voxels retained: 6888343
After filtering: 6888343 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Juan Ignacio/2026/5MHz_FedeOnlypores/JI_11/registration_53/image_manifest.csv' loaded with ID: 1291
Image dataset for registration 53 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Juan Ignacio/2026/5MHz_FedeOnlypores/JI_11/registration_53
Creating image dataset for registration 54 with reference measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/03_UT_data/Probetas JI/probetas/2025 methodology/12/12.tif and registered measurement /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/12/volume_eq_aligned.tif
Applying transformation

Transforming slices: 100%|██████████| 200/200 [00:04<00:00, 42.59it/s]

Transformation applied
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Starting pore detection analysis...
Computing volume bounding box...
Original volume shape: (200, 4840, 1960)
Data bounding box: Z[0:199], Y[635:3871], X[147:1760]
Cropped volume shape: (200, 3241, 1618)
Applying Sauvola adaptive thresholding...
Volume size: 0.98 GB
Available memory: 197.52 GB
Required memory estimate: 1.95 GB
Using parallel implementation...
Window size adjusted to 31 (must be odd)
Applying Sauvola thresholding with parallel processing...
Excluding front wall: slices 0 to 6
Excluding back wall: slices 174 to end
Generating material mask...
Computing material mask using sequential processing...
Filling internal voids...
Material mask generation complete.
Initial pore detection complete. Found 9242478 pore voxels.
Applying pore filtering with minimum size: 8
Cleaning pores with min_size=8...
  Initial connected components: 1751694

/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/UTvsXCT-preprocessing/preprocess_tools/onlypores.py:512: FutureWarning: Parameter `min_size` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_objects`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  labeled_pores = remove_small_objects(labeled_pores, min_size=min_size, connectivity=3)

  Components after size filtering: 69123
  Valid components after dimensional filtering: 65250
  Components after dimensional filtering: 65250
  Total pore voxels retained: 5641995
After filtering: 5641995 pore voxels remaining.
Pore detection analysis complete.
Preprocessing the images...
Cleaning the pores...
Creating the image maps...
Dataset from '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Juan Ignacio/2026/5MHz_FedeOnlypores/JI_12/registration_54/image_manifest.csv' loaded with ID: 1292
Image dataset for registration 54 saved to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Juan Ignacio/2026/5MHz_FedeOnlypores/JI_12/registration_54
Saved image dataset manifest to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/04_ML_data/Juan Ignacio/2026/5MHz_FedeOnlypores/image_dataset_manifest.csv

,image_kind,image_path,image_shape,image_dtype,file_format,depth_region,sample_id,sample_name,panel_id,panel_name,...,depth_roi_end_exclusive_from_frontwall,depth_roi_end_inclusive_from_frontwall,depth_roi_start_z,depth_roi_end_exclusive_z,depth_roi_end_inclusive_z,material_frontwall_z,material_backwall_z,material_threshold,xct_resolution,ut_resolution
0,ut,/home/alberto.vicente/phd/DataDriven_UT_Albert...,"(448, 80, 38)",uint8,tif,None,9,JI_4,3,Juan_Ignacio_placeholder,...,"(68, 136, 203)","(67, 135, 202)","(0, 68, 136)","(68, 136, 203)","(67, 135, 202)",0,203,0.8,0.025,1.0
1,volfrac,/home/alberto.vicente/phd/DataDriven_UT_Albert...,"(3, 80, 38)",float32,tif,"(front, middle, back)",9,JI_4,3,Juan_Ignacio_placeholder,...,"(68, 136, 203)","(67, 135, 202)","(0, 68, 136)","(68, 136, 203)","(67, 135, 202)",0,203,0.8,0.025,1.0
2,areafrac,/home/alberto.vicente/phd/DataDriven_UT_Albert...,"(80, 38)",float32,tif,None,9,JI_4,3,Juan_Ignacio_placeholder,...,"(68, 136, 203)","(67, 135, 202)","(0, 68, 136)","(68, 136, 203)","(67, 135, 202)",0,203,0.8,0.025,1.0
3,ut,/home/alberto.vicente/phd/DataDriven_UT_Albert...,"(448, 81, 38)",uint8,tif,None,10,JI_5,3,Juan_Ignacio_placeholder,...,"(64, 128, 192)","(63, 127, 191)","(0, 64, 128)","(64, 128, 192)","(63, 127, 191)",0,192,0.8,0.025,1.0
4,volfrac,/home/alberto.vicente/phd/DataDriven_UT_Albert...,"(3, 81, 38)",float32,tif,"(front, middle, back)",10,JI_5,3,Juan_Ignacio_placeholder,...,"(64, 128, 192)","(63, 127, 191)","(0, 64, 128)","(64, 128, 192)","(63, 127, 191)",0,192,0.8,0.025,1.0
5,areafrac,/home/alberto.vicente/phd/DataDriven_UT_Albert...,"(81, 38)",float32,tif,None,10,JI_5,3,Juan_Ignacio_placeholder,...,"(64, 128, 192)","(63, 127, 191)","(0, 64, 128)","(64, 128, 192)","(63, 127, 191)",0,192,0.8,0.025,1.0
6,ut,/home/alberto.vicente/phd/DataDriven_UT_Albert...,"(448, 82, 42)",uint8,tif,None,11,JI_7,3,Juan_Ignacio_placeholder,...,"(66, 131, 196)","(65, 130, 195)","(0, 66, 131)","(66, 131, 196)","(65, 130, 195)",0,196,0.8,0.025,1.0
7,volfrac,/home/alberto.vicente/phd/DataDriven_UT_Albert...,"(3, 82, 42)",float32,tif,"(front, middle, back)",11,JI_7,3,Juan_Ignacio_placeholder,...,"(66, 131, 196)","(65, 130, 195)","(0, 66, 131)","(66, 131, 196)","(65, 130, 195)",0,196,0.8,0.025,1.0
8,areafrac,/home/alberto.vicente/phd/DataDriven_UT_Albert...,"(82, 42)",float32,tif,None,11,JI_7,3,Juan_Ignacio_placeholder,...,"(66, 131, 196)","(65, 130, 195)","(0, 66, 131)","(66, 131, 196)","(65, 130, 195)",0,196,0.8,0.025,1.0
9,ut,/home/alberto.vicente/phd/DataDriven_UT_Albert...,"(448, 83, 42)",uint8,tif,None,12,JI_8,3,Juan_Ignacio_placeholder,...,"(68, 135, 202)","(67, 134, 201)","(0, 68, 135)","(68, 135, 202)","(67, 134, 201)",0,202,0.8,0.025,1.0
10,volfrac,/home/alberto.vicente/phd/DataDriven_UT_Albert...,"(3, 83, 42)",float32,tif,"(front, middle, back)",12,JI_8,3,Juan_Ignacio_placeholder,...,"(68, 135, 202)","(67, 134, 201)","(0, 68, 135)","(68, 135, 202)","(67, 134, 201)",0,202,0.8,0.025,1.0
11,areafrac,/home/alberto.vicente/phd/DataDriven_UT_Albert...,"(83, 42)",float32,tif,None,12,JI_8,3,Juan_Ignacio_placeholder,...,"(68, 135, 202)","(67, 134, 201)","(0, 68, 135)","(68, 135, 202)","(67, 134, 201)",0,202,0.8,0.025,1.0
12,ut,/home/alberto.vicente/phd/DataDriven_UT_Albert...,"(448, 80, 39)",uint8,tif,None,14,JI_10,3,Juan_Ignacio_placeholder,...,"(69, 137, 205)","(68, 136, 204)","(0, 69, 137)","(69, 137, 205)","(68, 136, 204)",0,205,0.8,0.025,1.0
13,volfrac,/home/alberto.vicente/phd/DataDriven_UT_Albert...,"(3, 80, 39)",float32,tif,"(front, middle, back)",14,JI_10,3,Juan_Ignacio_placeholder,...,"(69, 137, 205)","(68, 136, 204)","(0, 69, 137)","(69, 137, 205)","(68, 136, 204)",0,205,0.8,0.025,1.0
14,areafrac,/home/alberto.vicente/phd/DataDriven_UT_Albert...,"(80, 39)",float32,tif,None,14,JI_10,3,Juan_Ignacio_placeholder,...,"(69, 137, 205)","(68, 136, 204)","(0, 69, 137)","(69, 137, 205)","(68, 136, 204)",0,205,0.8,0.025,1.0
15,ut,/home/alberto.vicente/phd/DataDriven_UT_Albert...,"(448, 81, 40)",uint8,tif,None,15,JI_11,3,Juan_Ignacio_placeholder,...,"(68, 136, 203)","(67, 135, 202)","(0, 68, 136)","(68, 136, 203)","(67, 135, 202)",0,203,0.8,0.025,1.0
16,volfrac,/home/alberto.vicente/phd/DataDriven_UT_Albert...,"(3, 81, 40)",float32,tif,"(front, middle, back)",15,JI_11,3,Juan_Ignacio_placeholder,...,"(68, 136, 203)","(67, 135, 202)","(0, 68, 136)","(68, 136, 203)","(67, 135, 202)",0,203,0.8,0.025,1.0
17,areafrac,/home/alberto.vicente/phd/DataDriven_UT_Albert...,"(81, 40)",float32,tif,None,15,JI_11,3,Juan_Ignacio_placeholder,...,"(68, 136, 203)","(67, 135, 202)","(0, 68, 136)","(68, 136, 203)","(67, 135, 202)",0,203,0.8,0.025,1.0
18,ut,/home/alberto.vicente/phd/DataDriven_UT_Albert...,"(448, 80, 40)",uint8,tif,None,16,JI_12,3,Juan_Ignacio_placeholder,...,"(67, 134, 200)","(66, 133, 199)","(0, 67, 134)","(67, 134, 200)","(66, 133, 199)",0,200,0.8,0.025,1.0
19,volfrac,/home/alberto.vicente/phd/DataDriven_UT_Albert...,"(3, 80, 40)",float32,tif,"(front, middle, back)",16,JI_12,3,Juan_Ignacio_placeholder,...,"(67, 134, 200)","(66, 133, 199)","(0, 67, 134)","(67, 134, 200)","(66, 133, 199)",0,200,0.8,0.025,1.0
20,areafrac,/home/alberto.vicente/phd/DataDriven_UT_Albert...,"(80, 40)",float32,tif,None,16,JI_12,3,Juan_Ignacio_placeholder,...,"(67, 134, 200)","(66, 133, 199)","(0, 67, 134)","(67, 134, 200)","(66, 133, 199)",0,200,0.8,0.025,1.0

# Recompose global manifest from per-registration manifests

Run this cell independently to rebuild `image_dataset_manifest.csv` from scratch by scanning all `image_manifest.csv` files already on disk. Useful if the global manifest is missing, corrupted, or out of sync with the per-registration files (e.g. after a partial run or manual deletion).

Set `recompose_folder` to the root images folder if running outside the notebook flow.

In [19]:
# recompose_folder = folder  # change if running standalone

# per_registration_manifests = sorted(recompose_folder.glob('*/registration_*/image_manifest.csv'))
# print(f"Found {len(per_registration_manifests)} per-registration manifests")

# recomposed_df = pd.concat(
#     [pd.read_csv(p) for p in per_registration_manifests],
#     ignore_index=True,
# )

# recompose_manifest_path = recompose_folder / 'image_dataset_manifest.csv'
# recomposed_df.to_csv(recompose_manifest_path, index=False)

# print(f"Recomposed manifest saved to {recompose_manifest_path} ({len(recomposed_df)} rows)")
# recomposed_df