# Per-pore analysis from XCT volumes (Defect Atlas backend)

Receives a **list of folders**; in each one it finds the `*_onlypores.tif` and matching `*_samplemask.tif` volumes and computes, for **every pore** in the specimen, geometric / shape / orientation / distance-to-surface / border / classification metrics, plus specimen-level summaries (void volume fraction, counts by type, key figures, histograms).

**Nothing is reimplemented.** The notebook imports the existing Defect Atlas backend (`app.…`, read-only) and calls:

| Step | Backend function |
|---|---|
| labelling + all properties + border flags | `PipelineExecutor.run_pipeline` |
| Pore / LoF / Cluster / Border | `app.domain.services.classification.classify_defects` |
| shape class (Spherical / Disc / …) | `app.domain.services.shape_classifier.classify_shape` (inputs converted with `app.routers.study._covariance_ratio_to_axis_ratio`) |
| key figures | `app.services.analytics_service._volume_key_figures` |
| per-slice porosity | `app.services.porosity_report_service.compute_direction_report` |
| Z projections | `app.domain.services.projections.compute_projections` |

**Inputs are TIFF** (`*_onlypores.tif`, `*_samplemask.tif`, as written by `onlypores.ipynb`). The backend only reads RAW, so they are streamed slice-by-slice into polarity-normalised RAW files in `OUT_DIR/_raw/` (pores = 255, material = 0). Axis convention is the TIFF's: `(Z, Y, X)` = `(page, row, column)`.

**Kernel:** `defect-atlas` (Python 3.11, pydantic 1.x, numpy 1.26). The default `prep` kernel cannot import the backend.

## 1. Parameters

In [1]:
# ----------------------------- INPUTS ---------------------------------------
# Folders to analyse. Each is searched (recursively) for '*_onlypores.tif' and the matching '*_samplemask.tif'
# (same prefix, as written by onlypores.ipynb). Every pair found is analysed; results go to <pores folder>/pore_analysis.
FOLDERS = [
    "/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/4/onlypores files",
    "/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/5/onlypores files",
    "/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/7/onlypores files",
    "/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/8/onlypores files",
    "/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/10/onlypores files",
    "/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/11/onlypores files",
    "/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/12/onlypores files",
]
PORES_GLOB = "*_onlypores.tif"
MASK_SUFFIX = "_samplemask.tif"    # mask name = pores name with '_onlypores.tif' replaced by this
OUT_SUBDIR = "pore_analysis"       # output folder name, created next to each pores TIFF
STOP_ON_ERROR = False              # False = log the error and continue with the next folder

VOXEL_SIZE_MM = 0.025          # default isotropic voxel size in mm (0.025 mm = 25 µm)
VOXEL_SIZE_OVERRIDES = {}      # per-folder/prefix override, e.g. {"Na_01_1": 0.02}; key = substring of the pores TIFF path
GRAY_VOLUME_PATH  = None       # not supported in batch mode (kept for run_config compatibility)
INVERT_PORES = None            # None = auto-detect polarity; True/False = force
INVERT_MASK  = None            # (polarity = which value means "pore"/"material")
WALLS = "auto"                 # front/back wall exclusion along the TIFF Z axis (pages):
                               #   "auto" = read 'Front wall slice' / 'Back wall slice' from the *_report.txt next to the pores TIFF
                               #   (front, back) = explicit slice indices for ALL volumes;  None = no wall exclusion
CROP = None                    # None, or ((z0, z1), (y0, y1), (x0, x1)) in voxels, for quick tests

# ----------------------------- PIPELINE -------------------------------------
MIN_SIZE_VOXELS = 0            # kill_small   (0 = keep everything)
MAX_SIZE_VOXELS = None         # kill_big     (None = no limit)
CONNECTIVITY    = 26
ENABLE_MERGING  = False        # merge nearby defects into clusters (recomputes properties)
ENABLE_LOF      = True         # False => no pore can become LoF (only Pore/Cluster/Border)

# classification (classify_defects defaults)
LOF_VOLUME_THRESHOLD_VOX   = 60.0
LOF_ELONGATION_THRESHOLD   = 0.7
LOF_DISTANCE_THRESHOLD_VOX = 100.0
CPX_THRESHOLD = 0.7001         # classify_shape default: cpx_factor above this => "Complex"

# ----------------------------- OUTPUT / RUN ---------------------------------
USE_CACHE = True               # reuse raw conversion + pipeline result if inputs/params unchanged
KEEP_RAW = True                # keep OUT/_raw/*.raw (needed for cache reuse, ~1 byte/voxel each)
RUN_SLICE_PROFILE = True
SLICE_AXES = ("z", "y", "x")   # per-slice porosity directions
RUN_PROJECTION = True
SHOW_PLOTS = True              # False = save figures only (faster / cleaner for many folders)
BATCH_SUMMARY_PATH = None      # None => <first folder>/pore_analysis_batch_summary.csv

# ----------------------------- SETUP PATHS ----------------------------------
REPO = "/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/Defect Atlas"

## 2. Environment and import setup

* Sets `DEFECT_ATLAS_ACCELERATION_MODE=cpu` *before* importing (no `cupy` in this env, so the CUDA path would only fail and fall back).
* Sets `sys.dont_write_bytecode` so **no `__pycache__` is written inside `REPO`** (read-only use).
* Checks that the whole `REPO` tree is intact: `app/core/supernames.py` inserts `v1-tk-version/DefViz-main` into `sys.path` and imports `quantification_analyzer`.
* No `.env` is needed: `app.core.config` has defaults for every setting.
* Importing any `app.domain.services.*` eagerly imports all services – slow, expected. The "Legacy … volumelab not available" messages are harmless (legacy DefQ package is optional).
* **Memory:** labelling + EDT need roughly 8–12 bytes per voxel (int32 labels, float32 distance map; the backend switches to slab labelling / out-of-core EDT automatically for big volumes). Properties are then computed per pore in threads.

In [2]:
import os, sys, json, hashlib, time, math, tempfile, subprocess, warnings
sys.dont_write_bytecode = True
os.environ.setdefault("DEFECT_ATLAS_ACCELERATION_MODE", "cpu")
from pathlib import Path
from datetime import datetime

REPO = Path(REPO); BACKEND = REPO / "backend"
_missing = [p for p in (REPO, BACKEND / "app", REPO / "v1-tk-version" / "DefViz-main") if not p.exists()]
if not _missing:
    pass
else:
    # supernames.py accepts QuantificationAnalyzer-main as an alternative
    alt = REPO / "v1-tk-version" / "QuantificationAnalyzer-main"
    _missing = [p for p in _missing if not (p.name == "DefViz-main" and alt.exists())]
if _missing:
    raise RuntimeError("Defect Atlas tree incomplete, missing: " + ", ".join(map(str, _missing))
                       + "\nThe whole REPO must stay intact (supernames.py needs v1-tk-version).")
sys.path.insert(0, str(BACKEND))

import numpy as np, pandas as pd, psutil
import matplotlib; import matplotlib.pyplot as plt
from tqdm.auto import tqdm
import tifffile
import pydantic
if int(pydantic.VERSION.split(".")[0]) >= 2:
    raise RuntimeError(f"pydantic {pydantic.VERSION} found; backend needs 1.x. Use the 'defect-atlas' kernel.")

warnings.filterwarnings("ignore", category=FutureWarning)
from app.domain.models import PipelineConfig
from app.domain.services.pipeline_executor import PipelineExecutor
from app.domain.services.classification import classify_defects, ClassificationConfig
from app.domain.services.shape_classifier import classify_shape
from app.domain.services.projections import compute_projections
from app.services.analytics_service import _volume_key_figures
from app.services.porosity_report_service import compute_direction_report
from app.core.runtime_acceleration import detect_runtime_acceleration
try:
    from app.routers.study import _covariance_ratio_to_axis_ratio as _cov_to_axis_ratio
    _C2A_SRC = "imported from app.routers.study"
except Exception as exc:                                   # router import is optional
    def _cov_to_axis_ratio(value):                         # EXACT copy of study.py:594-597
        if value is None or value <= 0:
            return None
        return math.sqrt(1.0 / value)
    _C2A_SRC = f"replicated from app/routers/study.py:594 (router import failed: {type(exc).__name__})"

def _code_version():
    h = hashlib.md5()
    for p in sorted((BACKEND / "app").rglob("*.py")):
        h.update(p.read_bytes())
    ver = (REPO / "VERSION").read_text().strip() if (REPO / "VERSION").exists() else "?"
    return {"defect_atlas_VERSION": ver, "backend_sources_md5": h.hexdigest()[:12]}
CODE_VERSION = _code_version()


print("python      :", sys.version.split()[0], "| numpy", np.__version__, "| pandas", pd.__version__, "| pydantic", pydantic.VERSION)
print("backend     :", BACKEND, CODE_VERSION)
print("acceleration:", detect_runtime_acceleration().selected_mode, "(env DEFECT_ATLAS_ACCELERATION_MODE=%s)" % os.environ["DEFECT_ATLAS_ACCELERATION_MODE"])
print("axis ratio  :", _C2A_SRC)
print("RAM         : %.0f GB available of %.0f GB" % (psutil.virtual_memory().available/2**30, psutil.virtual_memory().total/2**30))

/home/alberto.vicente/miniconda3/envs/defect-atlas/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Legacy property modules not available: No module named 'volumelab'
Legacy modules not available: No module named 'volumelab'

python      : 3.11.16 | numpy 1.26.4 | pandas 2.2.3 | pydantic 1.10.17
backend     : /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/10_code/Defect Atlas/backend {'defect_atlas_VERSION': '1.0.0', 'backend_sources_md5': 'f4bb1e073e1b'}
acceleration: cpu (env DEFECT_ATLAS_ACCELERATION_MODE=cpu)
axis ratio  : imported from app.routers.study
RAM         : 224 GB available of 249 GB

### 2b. Helpers (thin wrappers around the backend)

In [3]:
LIST_COLS = ("touching_border_faces", "original_labels", "merge_rules")

def build_config(pores_raw, mask_raw, dims_xyz, res_nm, **over):
    p = dict(connectivity=CONNECTIVITY, min_size_voxels=MIN_SIZE_VOXELS, max_size_voxels=MAX_SIZE_VOXELS,
             enable_merging=ENABLE_MERGING, enable_lof_classification=ENABLE_LOF,
             lof_volume_threshold=LOF_VOLUME_THRESHOLD_VOX, lof_elongation_threshold=LOF_ELONGATION_THRESHOLD,
             lof_distance_threshold=LOF_DISTANCE_THRESHOLD_VOX)
    p.update(over)
    return PipelineConfig(
        pores_volume_path=str(pores_raw), mask_volume_path=str(mask_raw), dimensions=tuple(dims_xyz),
        resolution_nm=float(res_nm), data_type="uint8", mask_data_type="uint8", endian="little", header_offset=0,
        calculate_shortest_distance=True, properties_to_compute=None,
        save_csv_excel=False, save_histograms=False, save_scatter_plots=False, save_pore_rotation_gifs=False,
        save_intermediate_results=False, save_distance_map=False, **p)

def defects_to_table(defects):
    """DefectCollection.to_property_dict_list() = label/type/ranking + all props + merge provenance
    (PipelineExecutor._defects_to_dataframe omits type/ranking/merge info, so it is not used)."""
    df = pd.DataFrame(defects.to_property_dict_list())
    df = df.drop(columns=[c for c in ("coords",) if c in df.columns])       # large array column
    for c in LIST_COLS:
        if c in df.columns:
            df[c] = df[c].map(lambda v: "" if v is None or (isinstance(v, float) and v != v) else
                              (",".join(map(str, v)) if isinstance(v, (list, tuple, set)) else
                               json.dumps(v) if isinstance(v, dict) else str(v)))
    return df

def run_backend(pores_raw, mask_raw, dims_xyz, res_nm, progress=None, **over):
    cfg = build_config(pores_raw, mask_raw, dims_xyz, res_nm, **over)
    errors = cfg.validate()
    if errors:
        raise ValueError("PipelineConfig.validate() errors:\n  - " + "\n  - ".join(errors))
    _volume, defects = PipelineExecutor().run_pipeline(cfg, progress_callback=progress)
    df = defects_to_table(defects)
    del _volume, defects
    return df

BORDER_COLS = ["is_boundary_touching", "is_internal_defect", "touching_border_faces",
               "border_touch_voxel_count", "border_touch_fraction", "border_classification"]

def enrich_table(df, res_nm, lof=None, cpx_threshold=None):
    """Border check + classify_defects + shape class. Returns a new DataFrame."""
    lof = lof or dict(volume=LOF_VOLUME_THRESHOLD_VOX, elongation=LOF_ELONGATION_THRESHOLD, distance=LOF_DISTANCE_THRESHOLD_VOX)
    cpx_threshold = CPX_THRESHOLD if cpx_threshold is None else cpx_threshold
    miss = [c for c in BORDER_COLS if c not in df.columns]
    if miss:   # run_pipeline -> label_volume fills these via _compute_border_props; coords are gone by now
        raise RuntimeError(f"border columns missing from pipeline output: {miss}")
    if "original_labels" in df.columns:
        clusters = set(df.loc[df["original_labels"].astype(str) != "", "label"].astype(int))
    else:
        clusters = set()
    cfg = ClassificationConfig(
        volume_threshold_voxels=lof["volume"] if ENABLE_LOF else float("inf"),
        elongation_threshold=lof["elongation"], distance_threshold_voxels=lof["distance"])
    out = classify_defects(df, cfg, cluster_labels=clusters, resolution_nm=res_nm).df.copy()
    # shape class: Cov_* are covariance ratios in (0, 1]; classify_shape wants axis ratios (>= 1): sqrt(1/ratio)
    out["elong_axis_ratio"] = out["Cov_Elongation"].map(_cov_to_axis_ratio)
    out["flat_axis_ratio"]  = out["Cov_Flatness"].map(_cov_to_axis_ratio)
    e, f, c = out["elong_axis_ratio"].astype(float), out["flat_axis_ratio"].astype(float), out["cpx_factor"].astype(float)
    out["shape_class"] = [classify_shape(a, b, k, cpx_threshold) for a, b, k in zip(e, f, c)]
    out["shape_class_no_cpx"] = [classify_shape(a, b, None) for a, b in zip(e, f)]   # elongation/flatness only
    out["Equivalent Diameter (µm)"] = 2.0 * out["Equivalent Radius (µm)"]
    out["Volume3D (mm³)"] = out["Volume3D (µm³)"] * 1e-9
    return out

def check_units(df, res_nm, rtol=1e-6):
    """Physical-unit sanity checks (asserts). Returns a report DataFrame."""
    res_um = res_nm / 1000.0
    rows = []
    def chk(name, got, expect):
        got, expect = np.asarray(got, float), np.asarray(expect, float)
        ok = np.isfinite(got) & np.isfinite(expect)
        err = float(np.max(np.abs(got[ok] - expect[ok]) / np.maximum(np.abs(expect[ok]), 1e-12))) if ok.any() else np.nan
        rows.append((name, err, bool(err <= rtol) if ok.any() else None))
    chk("Volume3D (µm³) == volume_voxels·(res_nm/1000)³", df["Volume3D (µm³)"], df["volume_voxels"] * res_um**3)
    chk("num_pixels == volume_voxels", df["num_pixels"], df["volume_voxels"])
    chk("Equivalent Radius (µm) == (3V/4π)^(1/3)", df["Equivalent Radius (µm)"], (3 * df["Volume3D (µm³)"] / (4 * math.pi)) ** (1/3))
    for k in ("shortest", "mean", "centroid"):
        v = df[f"{k}_distance_to_surface_vox"]
        chk(f"{k}_distance_to_surface_um == vox·res_um", df[f"{k}_distance_to_surface_um"], v * res_um)
        chk(f"{k}_distance_to_surface (legacy) == vox·res_nm  [legacy unit = nm]", df[f"{k}_distance_to_surface"], v * res_nm)
        if f"{k}_distance_to_surface_nm" in df:
            chk(f"{k}_distance_to_surface_nm == vox·res_nm", df[f"{k}_distance_to_surface_nm"], v * res_nm)
    rep = pd.DataFrame(rows, columns=["check", "max_rel_err", "passed"])
    bad = rep[rep["passed"] == False]
    assert bad.empty, "unit checks failed:\n" + bad.to_string()
    return rep
print("helpers defined")
def convert_to_raw(pores_tif, mask_tif, raw_dir, crop_box, inv_p, inv_m):
    """Stream TIFF pages -> normalised uint8 RAW (0/255) and count voxels on the way."""
    (z0, z1), (y0, y1), (x0, x1) = crop_box
    pr, mr = raw_dir / "pores.raw", raw_dir / "mask.raw"
    cnt = dict(pore_voxels=0, mask_voxels=0, pores_outside_mask=0)
    with tifffile.TiffFile(pores_tif) as tp, tifffile.TiffFile(mask_tif) as tm, open(pr, "wb") as fp, open(mr, "wb") as fm:
        for i in tqdm(range(z0, z1), desc="TIFF -> RAW"):
            a = tp.pages[i].asarray()[y0:y1, x0:x1]; b = tm.pages[i].asarray()[y0:y1, x0:x1]
            P = (a == 0) if inv_p else (a > 0); M = (b == 0) if inv_m else (b > 0)
            cnt["pore_voxels"] += int(P.sum()); cnt["mask_voxels"] += int(M.sum()); cnt["pores_outside_mask"] += int((P & ~M).sum())
            fp.write((P.astype(np.uint8) * 255).tobytes()); fm.write((M.astype(np.uint8) * 255).tobytes())
    return pr, mr, cnt

def _fileid(p): s = Path(p).stat(); return [str(p), s.st_size, int(s.st_mtime)]

def find_jobs(folders):
    """Pair every '*_onlypores.tif' under the folders with its '*_samplemask.tif'. Returns (jobs, problems)."""
    jobs, problems, seen = [], [], set()
    for f in map(Path, folders):
        if not f.is_dir():
            problems.append((str(f), "folder not found")); continue
        pores = sorted(p for p in f.rglob(PORES_GLOB) if OUT_SUBDIR not in p.parts)
        if not pores:
            problems.append((str(f), f"no '{PORES_GLOB}' found")); continue
        for p in pores:
            if p in seen: continue
            seen.add(p)
            m = p.with_name(p.name.replace("_onlypores.tif", MASK_SUFFIX))
            if not m.is_file():
                problems.append((str(p), f"mask not found: {m.name}")); continue
            siblings = [q for q in pores if q.parent == p.parent]
            out = p.parent / (OUT_SUBDIR if len(siblings) == 1 else f"{OUT_SUBDIR}_{p.name[:-len('_onlypores.tif')]}")
            jobs.append(dict(folder=str(f), pores=p, mask=m, out=out, name=p.name[:-len("_onlypores.tif")]))
    return jobs, problems

def voxel_size_for(pores_path):
    for key, v in VOXEL_SIZE_OVERRIDES.items():
        if key in str(pores_path): return float(v)
    return float(VOXEL_SIZE_MM)
print("helpers defined")

helpers defined
helpers defined

## 2c. Per-specimen analysis (function)

The original step-by-step analysis — validate TIFFs, detect polarity, TIFF→RAW, backend pipeline, classification, column/unit checks, specimen summary, plots, export — packaged as `analyse_specimen()` and called once per volume found in `FOLDERS`. Logic is unchanged; only the paths/voxel size/output dir are now arguments. `_display` shows tables inline (and is silent outside Jupyter).

In [4]:
try:
    _display = display
except NameError:
    _display = print

def analyse_specimen(pores_path, mask_path, out_dir, voxel_size_mm):
    PORES_PATH, MASK_PATH = Path(pores_path), Path(mask_path)
    VOXEL_SIZE_MM = voxel_size_mm
    RES_NM = VOXEL_SIZE_MM * 1e6
    VOX_UM = RES_NM / 1000.0
    OUT = Path(out_dir)
    for sub in ("", "_raw", "figures"): (OUT / sub).mkdir(parents=True, exist_ok=True)
    print("voxel size  : %.6g mm = %.6g µm = %.6g nm" % (VOXEL_SIZE_MM, VOX_UM, RES_NM))
    print("OUT_DIR     :", OUT)
    print("free disk at OUT: %.0f GB" % (psutil.disk_usage(str(OUT)).free/2**30))


    def _open(path):
        t = tifffile.TiffFile(path); s = t.series[0]
        if len(s.shape) != 3: raise ValueError(f"{path}: expected a 3-D TIFF stack, got shape {s.shape}")
        if len(t.pages) != s.shape[0]: raise ValueError(f"{path}: {len(t.pages)} pages but series shape {s.shape}; unsupported layout")
        return t, s

    for p in (PORES_PATH, MASK_PATH) + ((Path(GRAY_VOLUME_PATH),) if GRAY_VOLUME_PATH else ()):
        if not p.is_file(): raise FileNotFoundError(f"input volume not found: {p}")

    tp, sp = _open(PORES_PATH); tm, sm = _open(MASK_PATH)
    if sp.shape != sm.shape: raise ValueError(f"pores {sp.shape} and mask {sm.shape} shapes differ")
    if GRAY_VOLUME_PATH:
        tg, sg = _open(Path(GRAY_VOLUME_PATH))
        if sg.shape != sp.shape: raise ValueError(f"gray {sg.shape} differs from pores {sp.shape}")
        tg.close()
    FULL_ZYX = tuple(sp.shape)
    print("pores TIFF:", FULL_ZYX, sp.dtype, "| mask TIFF:", tuple(sm.shape), sm.dtype)

    if CROP is None:
        (z0, z1), (y0, y1), (x0, x1) = [(0, n) for n in FULL_ZYX]
    else:
        (z0, z1), (y0, y1), (x0, x1) = CROP
        assert 0 <= z0 < z1 <= FULL_ZYX[0] and 0 <= y0 < y1 <= FULL_ZYX[1] and 0 <= x0 < x1 <= FULL_ZYX[2], "CROP out of range"

    # ---- front/back wall exclusion. onlypores() only forces the wall slices to "no pore"; the saved sample mask still
    # ---- contains material there, so without this the VVF denominator would include the walls. Keep front <= z < back.
    import re
    WALL_FRONT = WALL_BACK = None
    if WALLS == "auto":
        rep_f = PORES_PATH.parent / PORES_PATH.name.replace("_onlypores.tif", "_report.txt")
        if not rep_f.exists():
            raise FileNotFoundError(f"WALLS='auto' but {rep_f} not found; pass WALLS=(front, back) or WALLS=None")
        txt = rep_f.read_text()
        mf, mb = re.search(r"Front wall slice:\s*(\d+)", txt), re.search(r"Back wall slice:\s*(\d+)", txt)
        if not (mf and mb): raise ValueError(f"could not parse wall slices from {rep_f}")
        WALL_FRONT, WALL_BACK = int(mf.group(1)), int(mb.group(1))
    elif WALLS is not None:
        WALL_FRONT, WALL_BACK = map(int, WALLS)
    if WALL_FRONT is not None:
        lo = max(WALL_FRONT, 0)                                        # onlypores(): wall applied only if > 0
        hi = WALL_BACK if 0 < WALL_BACK < FULL_ZYX[0] else FULL_ZYX[0]
        z0, z1 = max(z0, lo), min(z1, hi)
        assert z1 > z0, "wall exclusion leaves no slices"
        print(f"walls: front={WALL_FRONT}, back={WALL_BACK} -> analysing z in [{z0}, {z1}) of {FULL_ZYX[0]} "
              f"(excluded {z0} front + {FULL_ZYX[0]-z1} back slices from pores AND mask)")
    else:
        print("walls: no wall exclusion")
    Z, Y, X = z1 - z0, y1 - y0, x1 - x0
    DIMS_XYZ = (X, Y, Z)
    N_VOX = X * Y * Z
    print(f"working box (Z,Y,X) = ({Z},{Y},{X})  -> DIMENSIONS (X,Y,Z) = {DIMS_XYZ}; {N_VOX/1e6:.1f} Mvoxels; "
          f"box volume = {N_VOX*VOX_UM**3*1e-9:.3f} mm³")
    need_gb = N_VOX * 10 / 2**30
    print("estimated peak backend memory ≈ %.1f GB (available %.0f GB)" % (need_gb, psutil.virtual_memory().available/2**30))
    if need_gb > psutil.virtual_memory().available / 2**30 * 0.8:
        warnings.warn("estimated backend memory is close to / above available RAM: use CROP or expect swapping")

    # ---- value histograms + polarity on a strided sample of pages
    idx = np.unique(np.linspace(z0, z1 - 1, min(Z, 16)).astype(int))
    cnt_p, cnt_m = {}, {}
    combos = {(ip, im): 0 for ip in (False, True) for im in (False, True)}   # pore voxels outside mask
    ptot = {k: 0 for k in combos}; npx = 0
    for i in idx:
        a = tp.pages[int(i)].asarray()[y0:y1, x0:x1]; b = tm.pages[int(i)].asarray()[y0:y1, x0:x1]
        for arr, c in ((a, cnt_p), (b, cnt_m)):
            u, n = np.unique(arr, return_counts=True)
            for uu, nn in zip(u.tolist(), n.tolist()): c[uu] = c.get(uu, 0) + nn
        npx += a.size
        for (ip, im) in combos:
            P = (a == 0) if ip else (a > 0); M = (b == 0) if im else (b > 0)
            combos[(ip, im)] += int((P & ~M).sum()); ptot[(ip, im)] += int(P.sum())
    print("\nvalue histogram (sampled pages):\n  pores:", dict(sorted(cnt_p.items())[:8]), "\n  mask :", dict(sorted(cnt_m.items())[:8]))
    rows = []
    for (ip, im), out in combos.items():
        tot = ptot[(ip, im)]
        rows.append(dict(invert_pores=ip, invert_mask=im, pore_frac_of_box=tot / npx, pores_outside_mask_frac=(out / tot) if tot else np.nan))
    pol = pd.DataFrame(rows); _display(pol)
    best = pol.sort_values(["pores_outside_mask_frac", "invert_pores", "invert_mask"]).iloc[0]
    INV_P = bool(best.invert_pores) if INVERT_PORES is None else bool(INVERT_PORES)
    INV_M = bool(best.invert_mask)  if INVERT_MASK  is None else bool(INVERT_MASK)
    print(f"POLARITY -> invert_pores={INV_P} ({'auto' if INVERT_PORES is None else 'forced'}), "
          f"invert_mask={INV_M} ({'auto' if INVERT_MASK is None else 'forced'})  "
          f"[pores are {'0' if INV_P else 'non-zero'} in the file, material is {'0' if INV_M else 'non-zero'}]")
    tp.close(); tm.close()

    RAW_DIR = OUT / "_raw"
    raw_key = dict(pores=_fileid(PORES_PATH), mask=_fileid(MASK_PATH), box=[[z0, z1], [y0, y1], [x0, x1]], inv=[INV_P, INV_M])
    meta_f = RAW_DIR / "raw_meta.json"
    PORES_RAW, MASK_RAW = RAW_DIR / "pores.raw", RAW_DIR / "mask.raw"
    cached = None
    if USE_CACHE and meta_f.exists() and PORES_RAW.exists() and MASK_RAW.exists():
        m = json.loads(meta_f.read_text())
        if m["key"] == raw_key and PORES_RAW.stat().st_size == N_VOX == MASK_RAW.stat().st_size: cached = m["counts"]
    if cached is None:
        t0 = time.time(); PORES_RAW, MASK_RAW, COUNTS = convert_to_raw(PORES_PATH, MASK_PATH, RAW_DIR, ((z0, z1), (y0, y1), (x0, x1)), INV_P, INV_M)
        meta_f.write_text(json.dumps(dict(key=raw_key, counts=COUNTS))); print("converted in %.0fs" % (time.time() - t0))
    else:
        COUNTS = cached; print("RAW cache reused")

    # expected bytes = X*Y*Z*itemsize + header(0)
    for p in (PORES_RAW, MASK_RAW):
        assert p.stat().st_size == N_VOX, f"{p}: {p.stat().st_size} bytes, expected {N_VOX}"
    MASK_VOX, PORE_VOX_TOTAL = COUNTS["mask_voxels"], COUNTS["pore_voxels"]
    print(f"\nRAW sizes OK ({N_VOX} bytes each)")
    print(f"pore voxels     : {PORE_VOX_TOTAL:,}  ({100*PORE_VOX_TOTAL/N_VOX:.3f}% of box)")
    print(f"material voxels : {MASK_VOX:,}  ({100*MASK_VOX/N_VOX:.2f}% of box)")
    print(f"pore voxels outside mask: {COUNTS['pores_outside_mask']:,}")
    print(f"VVF (pore voxels / material voxels) = {100*PORE_VOX_TOTAL/MASK_VOX:.4f} %")
    rep = PORES_PATH.parent / (PORES_PATH.name.replace("_onlypores.tif", "_report.txt"))
    if rep.exists() and CROP is None and WALL_FRONT is None:
        import re
        m_ = re.search(r"Void volumetric fraction.*?\(([\d.]+)%\)", rep.read_text())
        print(f"onlypores report.txt says VVF = {m_.group(1)} %  (cross-check)" if m_ else "report.txt found, VVF line not parsed")

    # mid-slice preview from the normalised RAW files
    pm = np.memmap(PORES_RAW, np.uint8, "r", shape=(Z, Y, X)); mm = np.memmap(MASK_RAW, np.uint8, "r", shape=(Z, Y, X))
    fig, ax = plt.subplots(1, 3, figsize=(15, 5))
    k = Z // 2
    ax[0].imshow(pm[k], cmap="gray"); ax[0].set_title(f"pores (z={k})")
    ax[1].imshow(mm[k], cmap="gray"); ax[1].set_title(f"material mask (z={k})")
    ov = np.zeros((Y, X, 3), np.float32); ov[..., 1] = mm[k] > 0; ov[..., 0] = pm[k] > 0; ov[..., 2] = 0
    ax[2].imshow(ov); ax[2].set_title("overlay: red = pores, green = material")
    for a_ in ax: a_.set_xlabel("x (voxel)"); a_.set_ylabel("y (voxel)")
    plt.tight_layout(); (plt.show() if SHOW_PLOTS else plt.close('all'))

    cfg = build_config(PORES_RAW, MASK_RAW, DIMS_XYZ, RES_NM)
    errs = cfg.validate()
    print("PipelineConfig.validate() ->", errs)
    assert errs == [], "fix the errors above before running"

    run_key = dict(raw=raw_key, res_nm=RES_NM, min=MIN_SIZE_VOXELS, max=MAX_SIZE_VOXELS, conn=CONNECTIVITY,
                   merge=ENABLE_MERGING, code=CODE_VERSION)
    RAW_TBL, RAW_KEY = OUT / "pores_raw.parquet", OUT / "pores_raw.key.json"
    if USE_CACHE and RAW_TBL.exists() and RAW_KEY.exists() and json.loads(RAW_KEY.read_text()) == run_key:
        df_raw = pd.read_parquet(RAW_TBL); RUNTIME_S = None
        print(f"pipeline result loaded from cache: {RAW_TBL}  ({len(df_raw):,} pores)")
    else:
        bar = tqdm(total=100, desc="pipeline", bar_format="{l_bar}{bar}| {n:.0f}% {postfix}")
        def progress(msg, pct):
            bar.n = min(100, float(pct)); bar.set_postfix_str(str(msg)[:60]); bar.refresh()
        t0 = time.time()
        df_raw = run_backend(PORES_RAW, MASK_RAW, DIMS_XYZ, RES_NM, progress=progress)
        RUNTIME_S = time.time() - t0; bar.n = 100; bar.refresh(); bar.close()
        df_raw.to_parquet(RAW_TBL); RAW_KEY.write_text(json.dumps(run_key))
        print(f"{len(df_raw):,} pores in {RUNTIME_S:.0f}s; cached to {RAW_TBL}")

    df = enrich_table(df_raw, RES_NM)
    print("type        :", df["type"].value_counts().to_dict())
    print("shape_class :", df["shape_class"].value_counts(dropna=False).to_dict())
    print("no_cpx class:", df["shape_class_no_cpx"].value_counts(dropna=False).to_dict())
    print("border      :", df["border_classification"].value_counts().to_dict())

    pd.set_option("display.width", 220); pd.set_option("display.max_columns", 60)
    _display(df.head())
    _display(df.describe().T)
    print(f"{len(df):,} pores x {df.shape[1]} columns")

    EXPECTED = {
     "Size": ["Volume3D (µm³)", "volume_voxels", "num_pixels", "Equivalent Radius (µm)", "Equivalent Diameter (µm)"],
     "Surface": ["Area3D (µm²)", "border_voxel_count", "Area3D_capped", "Sphericity"],
     "Position": ["centroid-0", "centroid-1", "centroid-2"] + [f"bbox-{i}" for i in range(6)] + ["BoundingBox_Dx (µm)", "BoundingBox_Dy (µm)", "BoundingBox_Dz (µm)"],
     "Feret": ["Length3D (µm)", "Width3D (µm)", "Breadth3D (µm)", "Thickness3D (µm)"],
     "Ellipsoid": ["Ellipsoid_Major_Axis_Length (µm)", "Ellipsoid_Medium_Axis_Length (µm)", "Ellipsoid_Minor_Axis_Length (µm)",
                   "Ellipsoid_Semi_Axis_1 (µm)", "Ellipsoid_Semi_Axis_2 (µm)", "Ellipsoid_Semi_Axis_3 (µm)"]
                   + [f"OrientedBBox_Corner{i}_{a} (µm)" for i in range(1, 9) for a in "xyz"],
     "Tensor shape": [f"{p}_{q}" for p in ("Cov", "Inertia") for q in ("Elongation", "Flatness", "Anisotropy", "elongation_avg", "flatness_avg")]
                   + [f"Covariance_Eigenvalue_{i}" for i in (1, 2, 3)] + [f"Inertia_Eigenvalue_{i}" for i in (1, 2, 3)]
                   + [f"Covariance_Eigenvector_{i}_{a}" for i in (1, 2, 3) for a in "xyz"] + [f"Inertia_Eigenvector_{i}_{a}" for i in (1, 2, 3) for a in "xyz"],
     "Orientation": ["Phi (degrees)", "Theta (degrees)", "Cov_Phi (degrees)", "Cov_Theta (degrees)", "Inertia_Phi (degrees)", "Inertia_Theta (degrees)"],
     "Complexity": ["cpx_factor", "cpx_factor_capped"],
     "Distance to surface": [f"{k}_distance_to_surface{s}" for k in ("shortest", "mean", "centroid") for s in ("_vox", "", "_nm", "_um")],
     "Border": BORDER_COLS,
     "Classification": ["type", "ranking", "shape_class", "shape_class_no_cpx"],
    }
    if ENABLE_MERGING: EXPECTED["Merge provenance"] = ["original_labels", "merge_rules"]
    rows = []
    for grp, cols in EXPECTED.items():
        for c in cols:
            if c not in df.columns: rows.append((grp, c, "MISSING", np.nan))
            else:
                n_nan = int(df[c].isna().sum())
                rows.append((grp, c, "ALL NaN" if n_nan == len(df) and len(df) else "ok", n_nan))
    chk = pd.DataFrame(rows, columns=["group", "column", "status", "n_nan"])
    print(chk.groupby(["group", "status"]).size().unstack(fill_value=0).to_string())
    _display(chk[chk.status != "ok"])
    extra = [c for c in df.columns if c not in set(sum(EXPECTED.values(), []))]
    print("columns present but not in the spec groups:", extra)

    # missing-values report (columns with any NaN)
    nn = df.isna().sum(); nn = nn[nn > 0].sort_values(ascending=False)
    print(f"\ncolumns with NaNs: {len(nn)}"); _display((pd.DataFrame({"n_nan": nn, "pct": 100 * nn / len(df)})).head(30))

    # capped / skipped-for-large-pore flags stay visible
    for c in ("Area3D_capped", "cpx_factor_capped"):
        if c in df: print(f"{c}: {int(df[c].astype(bool).sum())} of {len(df)} pores capped")

    units_report = check_units(df, RES_NM)
    _display(units_report)
    print("ALL UNIT CHECKS PASSED  (volume in µm³, legacy distance columns in nm, *_um in µm, *_vox in voxels)")

    def specimen_summary(df, mask_vox, n_vox, pore_vox_total, res_nm):
        vox_um3 = (res_nm / 1000.0) ** 3
        kf = _volume_key_figures(df)                                  # analytics_service: d = (6V/π)^(1/3)
        pore_um3 = float(df["Volume3D (µm³)"].sum())
        mat_mm3, box_mm3 = mask_vox * vox_um3 * 1e-9, n_vox * vox_um3 * 1e-9
        internal = df[df["is_internal_defect"].astype(bool)]
        s = dict(
            voxel_size_um=res_nm / 1000.0, box_voxels=int(n_vox), box_volume_mm3=box_mm3,
            material_voxels=int(mask_vox), material_volume_mm3=mat_mm3,
            defect_count=int(len(df)),
            porosity_pct=100.0 * pore_um3 * 1e-9 / mat_mm3,                 # study.py / routers/pipeline.py: pore volume / mask volume
            porosity_box_pct=100.0 * pore_um3 * 1e-9 / box_mm3,
            porosity_internal_only_pct=100.0 * float(internal["Volume3D (µm³)"].sum()) * 1e-9 / mat_mm3,
            defect_density_per_mm3=len(df) / mat_mm3,
            total_defect_volume_um3=pore_um3, total_defect_volume_mm3=pore_um3 * 1e-9,
            largest_volume_um3=kf.get("largest_volume_um3"), largest_eq_diameter_um=kf.get("largest_eq_diameter_um"),
            median_eq_diameter_um=kf.get("median_eq_diameter_um"),
            pore_voxels_in_table=int(df["volume_voxels"].sum()), pore_voxels_in_volume=int(pore_vox_total),
            counts_by_type=df["type"].value_counts().to_dict(),
            counts_by_shape_class=df["shape_class"].value_counts(dropna=False).rename(lambda k: str(k)).to_dict(),
            counts_by_shape_class_no_cpx=df["shape_class_no_cpx"].value_counts(dropna=False).rename(lambda k: str(k)).to_dict(),
            counts_by_border_class=df["border_classification"].value_counts().to_dict(),
            n_boundary_touching=int(df["is_boundary_touching"].astype(bool).sum()),
            n_area_capped=int(df["Area3D_capped"].astype(bool).sum()) if "Area3D_capped" in df else None,
            n_cpx_capped=int(df["cpx_factor_capped"].astype(bool).sum()) if "cpx_factor_capped" in df else None,
        )
        return s

    SUMMARY = specimen_summary(df, MASK_VOX, N_VOX, PORE_VOX_TOTAL, RES_NM)
    _display(pd.Series({k: v for k, v in SUMMARY.items() if not isinstance(v, dict)}, name="value").to_frame())
    for k in ("counts_by_type", "counts_by_shape_class", "counts_by_shape_class_no_cpx", "counts_by_border_class"):
        print(k, SUMMARY[k])
    d_vox = SUMMARY["pore_voxels_in_volume"] - SUMMARY["pore_voxels_in_table"]
    print(f"\npore voxels in volume − in table = {d_vox:,}  (non-zero only if MIN_SIZE/MAX_SIZE filtering removed pores)")

    FIG = OUT / "figures"
    def save(fig, name):
        fig.savefig(FIG / f"{name}.png", dpi=150, bbox_inches="tight")
        if SHOW_PLOTS: plt.show()
        else: plt.close(fig)
    TYPE_COL = {"Pore": "#1f77b4", "LoF": "#d62728", "Cluster": "#2ca02c", "Border": "#ff7f0e"}

    # data-quality flags (shown, not hidden): covariance ratios should lie in (0, 1]; sphericity should be <= 1
    n_cov_bad = int(((df["Cov_Elongation"] <= 0) | (df["Cov_Flatness"] <= 0)).sum()); n_cov_nan = int(df["Cov_Elongation"].isna().sum())
    n_sph_gt1 = int((df["Sphericity"] > 1.0 + 1e-9).sum()); n_1vox = int((df["volume_voxels"] <= 1).sum())
    print(f"Cov_Elongation/Cov_Flatness <= 0 (numerically degenerate, no shape class): {n_cov_bad}; NaN: {n_cov_nan}")
    print(f"Sphericity > 1 (voxelised area of tiny pores): {n_sph_gt1}; pores with <= 1 voxel: {n_1vox}  (use MIN_SIZE_VOXELS to drop them)")
    SUMMARY.update(n_cov_ratio_nonpositive=n_cov_bad, n_cov_ratio_nan=n_cov_nan, n_sphericity_gt1=n_sph_gt1, n_single_voxel_pores=n_1vox)
    vol = df["Volume3D (µm³)"]; vol = vol[vol > 0]
    fig, ax = plt.subplots(2, 2, figsize=(12, 8))
    ax[0, 0].hist(vol, bins=np.logspace(np.log10(vol.min()), np.log10(vol.max()), 60)); ax[0, 0].set_xscale("log"); ax[0, 0].set_yscale("log")
    ax[0, 0].set_xlabel("Volume (µm³)"); ax[0, 0].set_ylabel("pore count"); ax[0, 0].set_title("Volume")
    ed = df["Equivalent Diameter (µm)"]; ax[0, 1].hist(ed.dropna(), bins=60); ax[0, 1].set_yscale("log")
    ax[0, 1].set_xlabel("Equivalent diameter (µm)"); ax[0, 1].set_ylabel("pore count"); ax[0, 1].set_title("Equivalent diameter")
    ax[1, 0].hist(df["Sphericity"].dropna(), bins=60); ax[1, 0].set_xlabel("Sphericity (-)"); ax[1, 0].set_ylabel("pore count"); ax[1, 0].set_title("Sphericity")
    ax[1, 1].hist(df["Cov_Elongation"].dropna(), bins=60, range=(0, 1), alpha=.7, label="Cov_Elongation (λ2/λ1)")
    ax[1, 1].hist(df["Cov_Flatness"].dropna(), bins=60, range=(0, 1), alpha=.7, label="Cov_Flatness (λ3/λ2)")
    ax[1, 1].set_xlabel("covariance ratio (-)"); ax[1, 1].set_ylabel("pore count"); ax[1, 1].legend(); ax[1, 1].set_title("Elongation / flatness")
    plt.tight_layout(); save(fig, "hist_volume_diameter_sphericity_elongation")

    fig, ax = plt.subplots(figsize=(8, 6))
    for t, g in df.groupby("type"):
        ax.scatter(g["Volume3D (µm³)"], g["Sphericity"], s=6, alpha=.4, c=TYPE_COL.get(t, "grey"), label=f"{t} ({len(g):,})", rasterized=True)
    ax.set_xscale("log"); ax.set_xlabel("Volume (µm³)"); ax.set_ylabel("Sphericity (-)"); ax.legend(markerscale=3); ax.set_title("Volume vs sphericity by type")
    save(fig, "scatter_volume_sphericity_by_type")

    fig, ax = plt.subplots(1, 2, figsize=(12, 4))
    for a_, col, rng in ((ax[0], "Phi", (-180, 180)), (ax[1], "Theta", (0, 180))):
        for pre, lab in (("", "main"), ("Cov_", "cov"), ("Inertia_", "inertia")):
            v = df[f"{pre}{col} (degrees)"].dropna()
            a_.hist(v, bins=60, histtype="step", label=f"{lab} (n={len(v):,})")
        a_.set_xlabel(f"{col} (degrees)"); a_.set_ylabel("pore count"); a_.legend(); a_.set_title(f"Orientation: {col}")
    plt.tight_layout(); save(fig, "hist_phi_theta")

    # per-slice porosity (backend: porosity_report_service.compute_direction_report), RAW files are already 0/255 => invert=False
    SLICE = {}
    if RUN_SLICE_PROFILE:
        for axis in SLICE_AXES:
            f = OUT / f"slice_profile_{axis}.csv"; kf_ = OUT / f"slice_profile_{axis}.key.json"
            if USE_CACHE and f.exists() and kf_.exists() and json.loads(kf_.read_text()) == raw_key:
                SLICE[axis] = pd.read_csv(f); continue
            bar = tqdm(total=1, desc=f"slices {axis}")
            def cb(done, total): bar.total = total; bar.n = done; bar.refresh()
            SLICE[axis] = pd.DataFrame(compute_direction_report(pm, mm, axis, VOX_UM, False, False, cb)); bar.close()
            SLICE[axis].to_csv(f, index=False); kf_.write_text(json.dumps(raw_key))
        fig, ax = plt.subplots(1, len(SLICE), figsize=(5.5 * len(SLICE), 4), squeeze=False)
        for a_, (axis, d) in zip(ax[0], SLICE.items()):
            a_.plot(d["slice_um"], d["porosity_percent"]); a_.set_xlabel(f"{axis} position (µm)"); a_.set_ylabel("porosity, area % of material (%)")
            a_.set_title(f"Porosity profile along {axis.upper()}")
        plt.tight_layout(); save(fig, "porosity_profile_slices")
        print({a: dict(mean_pct=float(d["porosity_percent"].mean()), max_pct=float(d["porosity_percent"].max())) for a, d in SLICE.items()})
    else:
        print("RUN_SLICE_PROFILE=False")

    # porosity vs Z from the pore table (centroid slab volume / material volume per slab), independent cross-check
    zc = df["centroid-0"].to_numpy(float); zv = df["Volume3D (µm³)"].to_numpy(float)
    nb = min(40, Z); edges = np.linspace(0, Z, nb + 1)
    mat_z = np.array([np.count_nonzero(mm[int(a):int(b)]) for a, b in zip(edges[:-1], edges[1:])], float) * VOX_UM**3
    slab_por = 100 * np.histogram(zc, edges, weights=zv)[0] / np.maximum(mat_z, 1)
    fig, ax = plt.subplots(figsize=(7, 4)); ax.step(edges[:-1] * VOX_UM, slab_por, where="post")
    ax.set_xlabel("z position (µm)"); ax.set_ylabel("slab porosity (%)"); ax.set_title("Porosity vs Z (pore centroid slabs)")
    save(fig, "porosity_vs_z_slabs")

    if RUN_PROJECTION:
        pr = compute_projections(pm)           # streamed along Z in slabs
        fig, ax = plt.subplots(1, 2, figsize=(13, 6))
        im0 = ax[0].imshow(pr.max_pores, cmap="gray_r"); ax[0].set_title("Z max projection (any pore in column)")
        im1 = ax[1].imshow(pr.avg_pores, cmap="viridis"); ax[1].set_title("Z average projection"); plt.colorbar(im1, ax=ax[1], label="% of Z height that is pore")
        for a_ in ax: a_.set_xlabel("x (voxel)"); a_.set_ylabel("y (voxel)")
        plt.tight_layout(); save(fig, "projection_z")

    cols_out = [c for c in df.columns if c != "coords"]
    df[cols_out].to_csv(OUT / "pores.csv", index=False)
    df[cols_out].to_parquet(OUT / "pores.parquet", index=False)
    (OUT / "specimen_summary.json").write_text(json.dumps(SUMMARY, indent=2, default=lambda o: o.item() if hasattr(o, "item") else str(o)))
    run_config = dict(
        created=datetime.now().isoformat(timespec="seconds"), code_version=CODE_VERSION, repo=str(REPO),
        kernel_python=sys.version.split()[0], numpy=np.__version__, pandas=pd.__version__, pydantic=pydantic.VERSION,
        inputs=dict(walls=[WALL_FRONT, WALL_BACK], analysed_z_range=[z0, z1], pores=str(PORES_PATH), mask=str(MASK_PATH), gray=GRAY_VOLUME_PATH, crop=CROP, full_shape_zyx=list(FULL_ZYX),
                    working_shape_zyx=[Z, Y, X]),
        polarity=dict(invert_pores=INV_P, invert_mask=INV_M, auto_pores=INVERT_PORES is None, auto_mask=INVERT_MASK is None),
        voxel_size_mm=VOXEL_SIZE_MM, resolution_nm=RES_NM,
        pipeline=dict(connectivity=CONNECTIVITY, min_size_voxels=MIN_SIZE_VOXELS, max_size_voxels=MAX_SIZE_VOXELS,
                      enable_merging=ENABLE_MERGING, enable_lof=ENABLE_LOF, calculate_shortest_distance=True, properties_to_compute=None),
        classification=dict(volume_threshold_voxels=LOF_VOLUME_THRESHOLD_VOX, elongation_threshold=LOF_ELONGATION_THRESHOLD,
                            distance_threshold_voxels=LOF_DISTANCE_THRESHOLD_VOX, cpx_threshold=CPX_THRESHOLD,
                            axis_ratio_conversion="sqrt(1/cov_ratio), " + _C2A_SRC),
        acceleration=os.environ["DEFECT_ATLAS_ACCELERATION_MODE"], pipeline_runtime_s=RUNTIME_S,
        slice_axes=list(SLICE_AXES) if RUN_SLICE_PROFILE else None,
    )
    (OUT / "run_config.json").write_text(json.dumps(run_config, indent=2, default=str))
    if not KEEP_RAW:
        for p in (PORES_RAW, MASK_RAW): Path(p).unlink(missing_ok=True)
        (RAW_DIR / "raw_meta.json").unlink(missing_ok=True)
    print("written to", OUT); [print("  ", p.relative_to(OUT)) for p in sorted(OUT.rglob("*")) if p.is_file() and "_raw" not in p.parts]

    del pm, mm
    import gc; gc.collect()
    flat = {k: v for k, v in SUMMARY.items() if not isinstance(v, dict)}
    for k in ("counts_by_type", "counts_by_shape_class", "counts_by_border_class"):
        flat[k] = json.dumps(SUMMARY[k], default=str)
    return flat

## 3. Discover volumes in the folders

In [5]:
JOBS, PROBLEMS = find_jobs(FOLDERS)
for j in JOBS: print(f"{j['name']:<30} pores={j['pores'].name}  mask={j['mask'].name}  voxel={voxel_size_for(j['pores'])} mm  -> {j['out']}")
for p, why in PROBLEMS: print("SKIPPED:", p, "-", why)
print(f"\n{len(JOBS)} volume(s) to analyse, {len(PROBLEMS)} problem(s)")

volume_eq_rotated_aligned      pores=volume_eq_rotated_aligned_onlypores.tif  mask=volume_eq_rotated_aligned_samplemask.tif  voxel=0.025 mm  -> /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/4/onlypores files/pore_analysis
volume_eq_rotated_aligned      pores=volume_eq_rotated_aligned_onlypores.tif  mask=volume_eq_rotated_aligned_samplemask.tif  voxel=0.025 mm  -> /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/5/onlypores files/pore_analysis
volume_eq_aligned              pores=volume_eq_aligned_onlypores.tif  mask=volume_eq_aligned_samplemask.tif  voxel=0.025 mm  -> /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/7/onlypores files/pore_analysis
volume_eq_aligned              pores=volume_eq_aligned_onlypores.tif  mask=volume_eq_aligned_samplemask.tif  voxel=0.025 mm  -> /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/8/onlypores files/pore_analysis
volume_eq_aligned              pores=volume_eq_aligned_onlypores.tif  mask=volume_eq_aligned_samplemask.tif  voxel=0.025 mm  -> /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/10/onlypores files/pore_analysis
volume_eq_aligned              pores=volume_eq_aligned_onlypores.tif  mask=volume_eq_aligned_samplemask.tif  voxel=0.025 mm  -> /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/11/onlypores files/pore_analysis
volume_eq_aligned              pores=volume_eq_aligned_onlypores.tif  mask=volume_eq_aligned_samplemask.tif  voxel=0.025 mm  -> /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/12/onlypores files/pore_analysis

7 volume(s) to analyse, 0 problem(s)

## 4. Run the analysis on every folder

In [6]:
RESULTS = [dict(folder=p, name=None, status="skipped: " + why) for p, why in PROBLEMS]
for n, job in enumerate(JOBS, 1):
    print("\n" + "=" * 100 + f"\n[{n}/{len(JOBS)}] {job['name']}  ({job['folder']})\n" + "=" * 100)
    t0 = time.time()
    try:
        flat = analyse_specimen(job["pores"], job["mask"], job["out"], voxel_size_for(job["pores"]))
        RESULTS.append(dict(folder=job["folder"], name=job["name"], out_dir=str(job["out"]), status="ok",
                            elapsed_s=round(time.time() - t0, 1), **flat))
    except Exception as exc:
        import traceback; traceback.print_exc()
        RESULTS.append(dict(folder=job["folder"], name=job["name"], out_dir=str(job["out"]),
                            status=f"error: {type(exc).__name__}: {exc}", elapsed_s=round(time.time() - t0, 1)))
        if STOP_ON_ERROR: raise
    plt.close("all")

====================================================================================================
[1/7] volume_eq_rotated_aligned  (/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/4/onlypores files)
====================================================================================================
voxel size  : 0.025 mm = 25 µm = 25000 nm
OUT_DIR     : /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/4/onlypores files/pore_analysis
free disk at OUT: 5368 GB
pores TIFF: (203, 3226, 1609) uint8 | mask TIFF: (203, 3226, 1609) uint8
walls: front=9, back=174 -> analysing z in [9, 174) of 203 (excluded 9 front + 29 back slices from pores AND mask)
working box (Z,Y,X) = (165,3226,1609)  -> DIMENSIONS (X,Y,Z) = (1609, 3226, 165); 856.5 Mvoxels; box volume = 13382.103 mm³
estimated peak backend memory ≈ 8.0 GB (available 225 GB)

value histogram (sampled pages):
  pores: {0: 82823928, 255: 226216}
  mask : {0: 7666756, 255: 75383388}

   invert_pores  invert_mask  pore_frac_of_box  pores_outside_mask_frac
0         False        False          0.002724                 0.000000
1         False         True          0.002724                 1.000000
2          True        False          0.997276                 0.092567
3          True         True          0.997276                 0.907433

POLARITY -> invert_pores=False (auto), invert_mask=False (auto)  [pores are non-zero in the file, material is non-zero]

TIFF -> RAW: 100%|██████████| 165/165 [00:20<00:00,  7.88it/s]
/tmp/ipykernel_2127584/872339919.py:141: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.tight_layout(); (plt.show() if SHOW_PLOTS else plt.close('all'))

converted in 21s

RAW sizes OK (856454610 bytes each)
pore voxels     : 5,811,857  (0.679% of box)
material voxels : 778,617,527  (90.91% of box)
pore voxels outside mask: 0
VVF (pore voxels / material voxels) = 0.7464 %
PipelineConfig.validate() -> []

pipeline: 100%|██████████| 100% , Pipeline complete

2,770 pores in 40s; cached to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/4/onlypores files/pore_analysis/pores_raw.parquet
type        : {'Pore': 1934, 'LoF': 825, 'Border': 11}
shape_class : {'Complex': 2283, None: 448, 'Ellipsoidal': 32, 'Disc': 7}
no_cpx class: {'Rod': 1660, 'Ellipsoidal': 929, 'Disc': 173, 'Spherical': 6, None: 2}
border      : {'internal': 2741, 'single_face': 29}

,label,type,ranking,is_boundary_touching,is_internal_defect,touching_border_faces,border_touch_voxel_count,border_touch_fraction,border_classification,BoundingBox_Dx (µm),BoundingBox_Dy (µm),BoundingBox_Dz (µm),bbox-0,bbox-1,bbox-2,bbox-3,bbox-4,bbox-5,centroid-0,centroid-1,centroid-2,num_pixels,Covariance_Eigenvalue_1,Covariance_Eigenvalue_2,Covariance_Eigenvalue_3,Covariance_Eigenvector_1_x,Covariance_Eigenvector_1_y,Covariance_Eigenvector_1_z,Covariance_Eigenvector_2_x,Covariance_Eigenvector_2_y,...,shortest_distance_to_surface_um,mean_distance_to_surface_vox,mean_distance_to_surface,mean_distance_to_surface_nm,mean_distance_to_surface_um,centroid_distance_to_surface_vox,centroid_distance_to_surface,centroid_distance_to_surface_nm,centroid_distance_to_surface_um,Area3D (µm²),border_voxel_count,Area3D_capped,Volume3D (µm³),volume_voxels,Ellipsoid_Major_Axis_Length (µm),Ellipsoid_Medium_Axis_Length (µm),Ellipsoid_Minor_Axis_Length (µm),Ellipsoid_Semi_Axis_1 (µm),Ellipsoid_Semi_Axis_2 (µm),Ellipsoid_Semi_Axis_3 (µm),cpx_factor,cpx_factor_capped,Sphericity,Equivalent Radius (µm),elong_axis_ratio,flat_axis_ratio,shape_class,shape_class_no_cpx,Equivalent Diameter (µm),Volume3D (mm³)
0,1,LoF,41,True,False,z_max,435,0.003225,single_face,12700.0,10400.0,1000.0,125,923,690,165,1339,1198,151.582851,1177.453606,915.173014,134868,1.199934e+07,2.335606e+06,13724.234337,-0.921633,-0.386472,-0.035088,-0.386001,0.922290,...,25.000000,7.061736,1.765434e+05,1.765434e+05,176.543391,6.082763,1.520691e+05,1.520691e+05,152.069068,NaN,0,True,2.107312e+09,134868,6461.221671,2850.596286,218.514351,3230.610836,1425.298143,109.257176,NaN,True,NaN,795.328926,2.266621,13.045350,None,Ellipsoidal,1590.657852,2.107312
1,2,LoF,42,True,False,z_max,1408,0.010696,single_face,12575.0,7600.0,1150.0,119,681,454,165,985,957,151.325770,810.219570,728.663086,131639,1.010569e+07,1.706997e+06,13225.837003,-0.928760,-0.366709,0.054117,-0.366319,0.930328,...,25.000000,8.108271,2.027068e+05,2.027068e+05,202.706766,0.000000,0.000000e+00,0.000000e+00,0.000000,NaN,0,True,2.056859e+09,131639,6416.743408,2637.230097,232.136420,3208.371704,1318.615049,116.068210,NaN,True,NaN,788.930350,2.433137,11.360691,None,Ellipsoidal,1577.860700,2.056859
2,3,LoF,84,True,False,z_max,10495,0.082485,single_face,8125.0,6400.0,950.0,127,2022,329,165,2278,654,156.275993,2117.475789,460.983055,127235,2.966752e+06,1.211251e+06,9269.027381,-0.971720,0.217481,0.091991,0.217825,0.975967,...,103.077638,65.272133,1.631803e+06,1.631803e+06,1631.803322,49.050995,1.226275e+06,1.226275e+06,1226.274872,5.640993e+07,115866,False,1.988047e+09,127235,4737.236390,3026.923581,264.789942,2368.618195,1513.461790,132.394971,25.997776,False,0.135544,780.032450,1.565033,11.431414,Complex,Ellipsoidal,1560.064901,1.988047
3,4,LoF,22,False,True,,0,0.000000,internal,6025.0,13625.0,300.0,56,692,174,68,1237,415,61.477806,965.690522,271.783188,111811,1.001133e+07,2.150633e+06,1827.938374,-0.252209,0.967670,-0.002289,0.967668,0.252214,...,2456.241989,175.528030,4.388201e+06,4.388201e+06,4388.200760,172.362976,4.309074e+06,4.309074e+06,4309.074402,3.676204e+07,78878,False,1.747047e+09,111811,8106.708946,3757.351981,109.541699,4053.354473,1878.675991,54.770850,14.362675,False,0.190819,747.145725,2.157559,34.300655,Complex,Ellipsoidal,1494.291451,1.747047
4,5,LoF,100,True,False,z_max,2498,0.028064,single_face,8625.0,7200.0,1050.0,123,2174,426,165,2462,771,153.523413,2367.149860,614.938748,89010,3.612343e+06,1.481451e+06,9251.448915,-0.984692,0.155492,-0.078770,0.155459,0.987820,...,25.000000,19.918070,4.979517e+05,4.979517e+05,497.951746,9.000000,2.250000e+05,2.250000e+05,225.000000,5.983049e+07,125932,False,1.390781e+09,89010,4343.770329,2781.737107,219.825093,2171.885165,1390.868554,109.912547,47.306280,False,0.100709,692.452636,1.561532,12.654320,Complex,Ellipsoidal,1384.905271,1.390781

                           count           mean           std        min         25%          50%          75%           max
label                     2770.0    1385.500000  7.997744e+02   1.000000  693.250000  1385.500000  2077.750000  2.770000e+03
ranking                   2770.0     123.005415  2.293090e+02   0.000000    0.000000     0.000000   132.750000  8.250000e+02
border_touch_voxel_count  2770.0       5.578700  2.068913e+02   0.000000    0.000000     0.000000     0.000000  1.049500e+04
border_touch_fraction     2770.0       0.002316  3.552486e-02   0.000000    0.000000     0.000000     0.000000  8.823530e-01
BoundingBox_Dx (µm)       2770.0     994.422383  1.684678e+03  50.000000  150.000000   325.000000  1050.000000  2.437500e+04
...                          ...            ...           ...        ...         ...          ...          ...           ...
Equivalent Radius (µm)    2770.0     127.918400  1.006807e+02  32.259526   51.208805    98.346113   172.236075  7.953289e+02
elong_axis_ratio          2770.0       6.495879  6.981821e+00   1.001999    2.092057     3.956874     8.350905  7.369924e+01
flat_axis_ratio           2768.0  115102.695339  3.393390e+06   1.000000    1.387801     1.716162     2.290462  1.335113e+08
Equivalent Diameter (µm)  2770.0     255.836799  2.013615e+02  64.519051  102.417609   196.692226   344.472151  1.590658e+03
Volume3D (mm³)            2770.0       0.032783  1.111773e-01   0.000141    0.000563     0.003984     0.021402  2.107312e+00

[125 rows x 8 columns]

2,770 pores x 134 columns
status               ok
group
Border                6
Classification        4
Complexity            2
Distance to surface  12
Ellipsoid            30
Feret                 4
Orientation           6
Position             12
Size                  5
Surface               4
Tensor shape         34

Empty DataFrame
Columns: [group, column, status, n_nan]
Index: []

columns present but not in the spec groups: ['label', 'Elongation', 'Flatness', 'Anisotropy', 'elongation_avg', 'flatness_avg', 'Inertia_Ixx (µm²)', 'Inertia_Ixy (µm²)', 'Inertia_Ixz (µm²)', 'Inertia_Iyy (µm²)', 'Inertia_Iyz (µm²)', 'Inertia_Izz (µm²)', 'elong_axis_ratio', 'flat_axis_ratio', 'Volume3D (mm³)']

columns with NaNs: 14

                                   n_nan        pct
cpx_factor                           448  16.173285
shape_class                          448  16.173285
Area3D (µm²)                           3   0.108303
Sphericity                             3   0.108303
flatness_avg                           2   0.072202
Cov_flatness_avg                       2   0.072202
Ellipsoid_Major_Axis_Length (µm)       2   0.072202
Ellipsoid_Medium_Axis_Length (µm)      2   0.072202
Ellipsoid_Minor_Axis_Length (µm)       2   0.072202
Ellipsoid_Semi_Axis_1 (µm)             2   0.072202
Ellipsoid_Semi_Axis_2 (µm)             2   0.072202
Ellipsoid_Semi_Axis_3 (µm)             2   0.072202
flat_axis_ratio                        2   0.072202
shape_class_no_cpx                     2   0.072202

Area3D_capped: 3 of 2770 pores capped
cpx_factor_capped: 6 of 2770 pores capped

                                                check  max_rel_err  passed
0      Volume3D (µm³) == volume_voxels·(res_nm/1000)³          0.0    True
1                         num_pixels == volume_voxels          0.0    True
2             Equivalent Radius (µm) == (3V/4π)^(1/3)          0.0    True
3       shortest_distance_to_surface_um == vox·res_um          0.0    True
4   shortest_distance_to_surface (legacy) == vox·r...          0.0    True
5       shortest_distance_to_surface_nm == vox·res_nm          0.0    True
6           mean_distance_to_surface_um == vox·res_um          0.0    True
7   mean_distance_to_surface (legacy) == vox·res_n...          0.0    True
8           mean_distance_to_surface_nm == vox·res_nm          0.0    True
9       centroid_distance_to_surface_um == vox·res_um          0.0    True
10  centroid_distance_to_surface (legacy) == vox·r...          0.0    True
11      centroid_distance_to_surface_nm == vox·res_nm          0.0    True

ALL UNIT CHECKS PASSED  (volume in µm³, legacy distance columns in nm, *_um in µm, *_vox in voxels)

                                   value
voxel_size_um               2.500000e+01
box_voxels                  8.564546e+08
box_volume_mm3              1.338210e+04
material_voxels             7.786175e+08
material_volume_mm3         1.216590e+04
defect_count                2.770000e+03
porosity_pct                7.464329e-01
porosity_box_pct            6.785949e-01
porosity_internal_only_pct  6.776896e-01
defect_density_per_mm3      2.276856e-01
total_defect_volume_um3     9.081027e+10
total_defect_volume_mm3     9.081027e+01
largest_volume_um3          2.107312e+09
largest_eq_diameter_um      1.590658e+03
median_eq_diameter_um       1.966922e+02
pore_voxels_in_table        5.811857e+06
pore_voxels_in_volume       5.811857e+06
n_boundary_touching         2.900000e+01
n_area_capped               3.000000e+00
n_cpx_capped                6.000000e+00

counts_by_type {'Pore': 1934, 'LoF': 825, 'Border': 11}
counts_by_shape_class {'Complex': 2283, 'None': 448, 'Ellipsoidal': 32, 'Disc': 7}
counts_by_shape_class_no_cpx {'Rod': 1660, 'Ellipsoidal': 929, 'Disc': 173, 'Spherical': 6, 'None': 2}
counts_by_border_class {'internal': 2741, 'single_face': 29}

pore voxels in volume − in table = 0  (non-zero only if MIN_SIZE/MAX_SIZE filtering removed pores)
Cov_Elongation/Cov_Flatness <= 0 (numerically degenerate, no shape class): 2; NaN: 0
Sphericity > 1 (voxelised area of tiny pores): 191; pores with <= 1 voxel: 0  (use MIN_SIZE_VOXELS to drop them)

/tmp/ipykernel_2127584/872339919.py:256: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  if SHOW_PLOTS: plt.show()
/tmp/ipykernel_2127584/872339919.py:256: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  if SHOW_PLOTS: plt.show()
slices z: 100%|██████████| 165/165 [00:03<00:00, 42.18it/s]
slices y: 100%|██████████| 3226/3226 [00:04<00:00, 806.16it/s]
slices x: 100%|██████████| 1609/1609 [00:10<00:00, 151.43it/s]

{'z': {'mean_pct': 0.7439590117733751, 'max_pct': 3.8382123549243228}, 'y': {'mean_pct': 0.745389462504899, 'max_pct': 2.6968180294161606}, 'x': {'mean_pct': 0.7528350342708406, 'max_pct': 20.204313280363223}}
written to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/4/onlypores files/pore_analysis
   figures/hist_phi_theta.png
   figures/hist_volume_diameter_sphericity_elongation.png
   figures/porosity_profile_slices.png
   figures/porosity_vs_z_slabs.png
   figures/projection_z.png
   figures/scatter_volume_sphericity_by_type.png
   pores.csv
   pores.parquet
   pores_raw.key.json
   pores_raw.parquet
   run_config.json
   slice_profile_x.csv
   slice_profile_x.key.json
   slice_profile_y.csv
   slice_profile_y.key.json
   slice_profile_z.csv
   slice_profile_z.key.json
   specimen_summary.json

====================================================================================================
[2/7] volume_eq_rotated_aligned  (/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/5/onlypores files)
====================================================================================================
voxel size  : 0.025 mm = 25 µm = 25000 nm
OUT_DIR     : /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/5/onlypores files/pore_analysis
free disk at OUT: 5368 GB
pores TIFF: (192, 3226, 1628) uint8 | mask TIFF: (192, 3226, 1628) uint8
walls: front=9, back=177 -> analysing z in [9, 177) of 192 (excluded 9 front + 15 back slices from pores AND mask)
working box (Z,Y,X) = (168,3226,1628)  -> DIMENSIONS (X,Y,Z) = (1628, 3226, 168); 882.3 Mvoxels; box volume = 13786.311 mm³
estimated peak backend memory ≈ 8.2 GB (available 226 GB)

value histogram (sampled pages):
  pores: {0: 83787452, 255: 243396}
  mask : {0: 8396280, 255: 75634568}

   invert_pores  invert_mask  pore_frac_of_box  pores_outside_mask_frac
0         False        False          0.002897                 0.000000
1         False         True          0.002897                 1.000000
2          True        False          0.997103                 0.100209
3          True         True          0.997103                 0.899791

POLARITY -> invert_pores=False (auto), invert_mask=False (auto)  [pores are non-zero in the file, material is non-zero]

TIFF -> RAW: 100%|██████████| 168/168 [00:15<00:00, 10.61it/s]
/tmp/ipykernel_2127584/872339919.py:141: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.tight_layout(); (plt.show() if SHOW_PLOTS else plt.close('all'))

converted in 16s

RAW sizes OK (882323904 bytes each)
pore voxels     : 7,118,691  (0.807% of box)
material voxels : 794,977,215  (90.10% of box)
pore voxels outside mask: 0
VVF (pore voxels / material voxels) = 0.8955 %
PipelineConfig.validate() -> []

pipeline: 100%|██████████| 100% , Pipeline complete

4,723 pores in 44s; cached to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/5/onlypores files/pore_analysis/pores_raw.parquet
type        : {'Pore': 3342, 'LoF': 1380, 'Border': 1}
shape_class : {'Complex': 3710, None: 952, 'Ellipsoidal': 49, 'Disc': 7, 'Rod': 5}
no_cpx class: {'Rod': 2609, 'Ellipsoidal': 1794, 'Disc': 310, 'Spherical': 9, None: 1}
border      : {'internal': 4715, 'single_face': 8}

,label,type,ranking,is_boundary_touching,is_internal_defect,touching_border_faces,border_touch_voxel_count,border_touch_fraction,border_classification,BoundingBox_Dx (µm),BoundingBox_Dy (µm),BoundingBox_Dz (µm),bbox-0,bbox-1,bbox-2,bbox-3,bbox-4,bbox-5,centroid-0,centroid-1,centroid-2,num_pixels,Covariance_Eigenvalue_1,Covariance_Eigenvalue_2,Covariance_Eigenvalue_3,Covariance_Eigenvector_1_x,Covariance_Eigenvector_1_y,Covariance_Eigenvector_1_z,Covariance_Eigenvector_2_x,Covariance_Eigenvector_2_y,...,shortest_distance_to_surface_um,mean_distance_to_surface_vox,mean_distance_to_surface,mean_distance_to_surface_nm,mean_distance_to_surface_um,centroid_distance_to_surface_vox,centroid_distance_to_surface,centroid_distance_to_surface_nm,centroid_distance_to_surface_um,Area3D (µm²),border_voxel_count,Area3D_capped,Volume3D (µm³),volume_voxels,Ellipsoid_Major_Axis_Length (µm),Ellipsoid_Medium_Axis_Length (µm),Ellipsoid_Minor_Axis_Length (µm),Ellipsoid_Semi_Axis_1 (µm),Ellipsoid_Semi_Axis_2 (µm),Ellipsoid_Semi_Axis_3 (µm),cpx_factor,cpx_factor_capped,Sphericity,Equivalent Radius (µm),elong_axis_ratio,flat_axis_ratio,shape_class,shape_class_no_cpx,Equivalent Diameter (µm),Volume3D (mm³)
0,1,LoF,6,False,True,,0,0.0,internal,25250.0,27375.0,550.0,56,963,538,78,2058,1548,65.852013,1471.457855,931.233042,204045,6.762588e+07,8.348420e+06,7697.275279,-0.687427,0.726195,-0.009228,0.726096,0.687487,...,25.000000,107.037888,2.675947e+06,2.675947e+06,2675.947189,103.402130,2.585053e+06,2.585053e+06,2585.053253,NaN,0,True,3.188203e+09,204045,11755.196197,4130.242615,125.412815,5877.598099,2065.121308,62.706407,NaN,True,NaN,913.031563,2.846127,32.933178,None,Ellipsoidal,1826.063127,3.188203
1,2,LoF,4,False,True,,0,0.0,internal,24375.0,7225.0,325.0,68,1563,589,81,1852,1564,72.685969,1696.483486,930.255449,139394,3.964984e+07,2.264570e+06,2560.098944,-0.990051,0.140703,0.001418,0.140698,0.990047,...,100.000000,98.774300,2.469357e+06,2.469357e+06,2469.357491,36.851051,9.212763e+05,9.212763e+05,921.276283,4.740134e+07,101352,False,2.178031e+09,139394,12938.836499,3092.198653,103.968762,6469.418249,1546.099327,51.984381,27.427049,False,0.171423,804.127965,4.184348,29.741613,Complex,Rod,1608.255930,2.178031
2,3,LoF,19,False,True,,0,0.0,internal,6650.0,17875.0,300.0,56,2251,1103,68,2966,1369,61.412542,2643.645850,1211.466692,132520,1.245840e+07,1.029391e+06,2038.766389,-0.097654,0.995220,0.000330,0.995166,0.097645,...,117.260385,279.296509,6.982413e+06,6.982413e+06,6982.412720,342.559479,8.563987e+06,8.563987e+06,8563.986969,4.255776e+07,89980,False,2.070625e+09,132520,10245.434345,2945.027846,131.063889,5122.717172,1472.513923,65.531945,17.753667,False,0.184603,790.686423,3.478892,22.470170,Complex,Rod,1581.372845,2.070625
3,4,LoF,28,False,True,,0,0.0,internal,12375.0,7575.0,250.0,122,1747,215,132,2050,710,127.118232,1888.783743,485.142005,78490,9.708715e+06,1.200279e+06,1407.671136,-0.956957,-0.290230,0.000282,-0.290226,0.956948,...,600.000000,124.356857,3.108921e+06,3.108921e+06,3108.921432,156.799240,3.919981e+06,3.919981e+06,3919.981003,2.980624e+07,64754,False,1.226406e+09,78490,8209.221086,2886.437196,98.848861,4104.610543,1443.218598,49.424430,20.131660,False,0.185894,664.021154,2.844067,29.200510,Complex,Ellipsoidal,1328.042309,1.226406
4,5,LoF,15,False,True,,0,0.0,internal,12050.0,1775.0,250.0,81,2345,827,91,2416,1309,85.012106,2373.705839,1004.784314,69717,7.282777e+06,1.196397e+05,1425.731903,-0.995515,0.094470,-0.005024,0.094596,0.993385,...,825.378704,67.174049,1.679351e+06,1.679351e+06,1679.351234,63.198105,1.579953e+06,1.579953e+06,1579.952621,2.053798e+07,41636,False,1.089328e+09,69717,10507.519183,1346.757136,147.018036,5253.759592,673.378568,73.509018,5.244646,False,0.249287,638.297832,7.802089,9.160489,Complex,Rod,1276.595663,1.089328

                           count         mean          std        min          25%          50%          75%           max
label                     4723.0  2362.000000  1363.556991   1.000000  1181.500000  2362.000000  3542.500000   4723.000000
ranking                   4723.0   201.755240   380.798632   0.000000     0.000000     0.000000   199.500000   1380.000000
border_touch_voxel_count  4723.0     0.096337     3.635650   0.000000     0.000000     0.000000     0.000000    233.000000
border_touch_fraction     4723.0     0.000414     0.013853   0.000000     0.000000     0.000000     0.000000      0.588235
BoundingBox_Dx (µm)       4723.0   784.046157  1432.308689  50.000000   125.000000   250.000000   825.000000  25250.000000
...                          ...          ...          ...        ...          ...          ...          ...           ...
Equivalent Radius (µm)    4723.0   109.822156    91.098297  32.259526    44.104857    77.955192   140.812449    913.031563
elong_axis_ratio          4723.0     5.597355     5.473147   1.000000     1.950144     3.389804     7.442499     43.310987
flat_axis_ratio           4722.0     2.217297     2.524666   1.000000     1.368307     1.632250     2.143076     75.167715
Equivalent Diameter (µm)  4723.0   219.644312   182.196593  64.519051    88.209714   155.910384   281.624898   1826.063127
Volume3D (mm³)            4723.0     0.023551     0.093117   0.000141     0.000359     0.001984     0.011695      3.188203

[125 rows x 8 columns]

4,723 pores x 134 columns
status               ok
group
Border                6
Classification        4
Complexity            2
Distance to surface  12
Ellipsoid            30
Feret                 4
Orientation           6
Position             12
Size                  5
Surface               4
Tensor shape         34

Empty DataFrame
Columns: [group, column, status, n_nan]
Index: []

columns present but not in the spec groups: ['label', 'Elongation', 'Flatness', 'Anisotropy', 'elongation_avg', 'flatness_avg', 'Inertia_Ixx (µm²)', 'Inertia_Ixy (µm²)', 'Inertia_Ixz (µm²)', 'Inertia_Iyy (µm²)', 'Inertia_Iyz (µm²)', 'Inertia_Izz (µm²)', 'elong_axis_ratio', 'flat_axis_ratio', 'Volume3D (mm³)']

columns with NaNs: 18

                                   n_nan        pct
shape_class                          952  20.156680
cpx_factor                           952  20.156680
Cov_Phi (degrees)                      2   0.042346
Cov_Theta (degrees)                    2   0.042346
Phi (degrees)                          2   0.042346
Theta (degrees)                        2   0.042346
flatness_avg                           1   0.021173
Ellipsoid_Semi_Axis_2 (µm)             1   0.021173
flat_axis_ratio                        1   0.021173
Sphericity                             1   0.021173
Ellipsoid_Semi_Axis_3 (µm)             1   0.021173
Ellipsoid_Minor_Axis_Length (µm)       1   0.021173
Ellipsoid_Semi_Axis_1 (µm)             1   0.021173
Cov_flatness_avg                       1   0.021173
Ellipsoid_Medium_Axis_Length (µm)      1   0.021173
Ellipsoid_Major_Axis_Length (µm)       1   0.021173
Area3D (µm²)                           1   0.021173
shape_class_no_cpx                     1   0.021173

Area3D_capped: 1 of 4723 pores capped
cpx_factor_capped: 1 of 4723 pores capped

                                                check  max_rel_err  passed
0      Volume3D (µm³) == volume_voxels·(res_nm/1000)³          0.0    True
1                         num_pixels == volume_voxels          0.0    True
2             Equivalent Radius (µm) == (3V/4π)^(1/3)          0.0    True
3       shortest_distance_to_surface_um == vox·res_um          0.0    True
4   shortest_distance_to_surface (legacy) == vox·r...          0.0    True
5       shortest_distance_to_surface_nm == vox·res_nm          0.0    True
6           mean_distance_to_surface_um == vox·res_um          0.0    True
7   mean_distance_to_surface (legacy) == vox·res_n...          0.0    True
8           mean_distance_to_surface_nm == vox·res_nm          0.0    True
9       centroid_distance_to_surface_um == vox·res_um          0.0    True
10  centroid_distance_to_surface (legacy) == vox·r...          0.0    True
11      centroid_distance_to_surface_nm == vox·res_nm          0.0    True

ALL UNIT CHECKS PASSED  (volume in µm³, legacy distance columns in nm, *_um in µm, *_vox in voxels)

                                   value
voxel_size_um               2.500000e+01
box_voxels                  8.823239e+08
box_volume_mm3              1.378631e+04
material_voxels             7.949772e+08
material_volume_mm3         1.242152e+04
defect_count                4.723000e+03
porosity_pct                8.954585e-01
porosity_box_pct            8.068115e-01
porosity_internal_only_pct  8.940527e-01
defect_density_per_mm3      3.802272e-01
total_defect_volume_um3     1.112295e+11
total_defect_volume_mm3     1.112295e+02
largest_volume_um3          3.188203e+09
largest_eq_diameter_um      1.826063e+03
median_eq_diameter_um       1.559104e+02
pore_voxels_in_table        7.118691e+06
pore_voxels_in_volume       7.118691e+06
n_boundary_touching         8.000000e+00
n_area_capped               1.000000e+00
n_cpx_capped                1.000000e+00

counts_by_type {'Pore': 3342, 'LoF': 1380, 'Border': 1}
counts_by_shape_class {'Complex': 3710, 'None': 952, 'Ellipsoidal': 49, 'Disc': 7, 'Rod': 5}
counts_by_shape_class_no_cpx {'Rod': 2609, 'Ellipsoidal': 1794, 'Disc': 310, 'Spherical': 9, 'None': 1}
counts_by_border_class {'internal': 4715, 'single_face': 8}

pore voxels in volume − in table = 0  (non-zero only if MIN_SIZE/MAX_SIZE filtering removed pores)
Cov_Elongation/Cov_Flatness <= 0 (numerically degenerate, no shape class): 1; NaN: 0
Sphericity > 1 (voxelised area of tiny pores): 512; pores with <= 1 voxel: 0  (use MIN_SIZE_VOXELS to drop them)

/tmp/ipykernel_2127584/872339919.py:256: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  if SHOW_PLOTS: plt.show()
/tmp/ipykernel_2127584/872339919.py:256: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  if SHOW_PLOTS: plt.show()
slices z: 100%|██████████| 168/168 [00:03<00:00, 42.27it/s]
slices y: 100%|██████████| 3226/3226 [00:03<00:00, 806.62it/s]
slices x: 100%|██████████| 1628/1628 [00:11<00:00, 138.27it/s]

{'z': {'mean_pct': 0.8940797989471659, 'max_pct': 5.17814756937112}, 'y': {'mean_pct': 0.8904241672118306, 'max_pct': 2.362891723703816}, 'x': {'mean_pct': 0.90774134914521, 'max_pct': 52.89719626168224}}
written to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/5/onlypores files/pore_analysis
   figures/hist_phi_theta.png
   figures/hist_volume_diameter_sphericity_elongation.png
   figures/porosity_profile_slices.png
   figures/porosity_vs_z_slabs.png
   figures/projection_z.png
   figures/scatter_volume_sphericity_by_type.png
   pores.csv
   pores.parquet
   pores_raw.key.json
   pores_raw.parquet
   run_config.json
   slice_profile_x.csv
   slice_profile_x.key.json
   slice_profile_y.csv
   slice_profile_y.key.json
   slice_profile_z.csv
   slice_profile_z.key.json
   specimen_summary.json

====================================================================================================
[3/7] volume_eq_aligned  (/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/7/onlypores files)
====================================================================================================
voxel size  : 0.025 mm = 25 µm = 25000 nm
OUT_DIR     : /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/7/onlypores files/pore_analysis
free disk at OUT: 5368 GB
pores TIFF: (196, 3227, 1685) uint8 | mask TIFF: (196, 3227, 1685) uint8
walls: front=8, back=172 -> analysing z in [8, 172) of 196 (excluded 8 front + 24 back slices from pores AND mask)
working box (Z,Y,X) = (164,3227,1685)  -> DIMENSIONS (X,Y,Z) = (1685, 3227, 164); 891.7 Mvoxels; box volume = 13933.581 mm³
estimated peak backend memory ≈ 8.3 GB (available 226 GB)

value histogram (sampled pages):
  pores: {0: 86769124, 255: 230796}
  mask : {0: 7164694, 255: 79835226}

   invert_pores  invert_mask  pore_frac_of_box  pores_outside_mask_frac
0         False        False          0.002653                 0.000000
1         False         True          0.002653                 1.000000
2          True        False          0.997347                 0.082572
3          True         True          0.997347                 0.917428

POLARITY -> invert_pores=False (auto), invert_mask=False (auto)  [pores are non-zero in the file, material is non-zero]

TIFF -> RAW: 100%|██████████| 164/164 [00:16<00:00,  9.88it/s]
/tmp/ipykernel_2127584/872339919.py:141: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.tight_layout(); (plt.show() if SHOW_PLOTS else plt.close('all'))

converted in 17s

RAW sizes OK (891749180 bytes each)
pore voxels     : 4,372,615  (0.490% of box)
material voxels : 818,969,878  (91.84% of box)
pore voxels outside mask: 0
VVF (pore voxels / material voxels) = 0.5339 %
PipelineConfig.validate() -> []

pipeline: 100%|██████████| 100% , Pipeline complete

2,023 pores in 38s; cached to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/7/onlypores files/pore_analysis/pores_raw.parquet
type        : {'Pore': 1434, 'LoF': 584, 'Border': 5}
shape_class : {'Complex': 1350, None: 611, 'Ellipsoidal': 49, 'Disc': 12, 'Spherical': 1}
no_cpx class: {'Rod': 909, 'Ellipsoidal': 895, 'Disc': 210, 'Spherical': 9}
border      : {'internal': 2009, 'single_face': 14}

,label,type,ranking,is_boundary_touching,is_internal_defect,touching_border_faces,border_touch_voxel_count,border_touch_fraction,border_classification,BoundingBox_Dx (µm),BoundingBox_Dy (µm),BoundingBox_Dz (µm),bbox-0,bbox-1,bbox-2,bbox-3,bbox-4,bbox-5,centroid-0,centroid-1,centroid-2,num_pixels,Covariance_Eigenvalue_1,Covariance_Eigenvalue_2,Covariance_Eigenvalue_3,Covariance_Eigenvector_1_x,Covariance_Eigenvector_1_y,Covariance_Eigenvector_1_z,Covariance_Eigenvector_2_x,Covariance_Eigenvector_2_y,...,shortest_distance_to_surface_um,mean_distance_to_surface_vox,mean_distance_to_surface,mean_distance_to_surface_nm,mean_distance_to_surface_um,centroid_distance_to_surface_vox,centroid_distance_to_surface,centroid_distance_to_surface_nm,centroid_distance_to_surface_um,Area3D (µm²),border_voxel_count,Area3D_capped,Volume3D (µm³),volume_voxels,Ellipsoid_Major_Axis_Length (µm),Ellipsoid_Medium_Axis_Length (µm),Ellipsoid_Minor_Axis_Length (µm),Ellipsoid_Semi_Axis_1 (µm),Ellipsoid_Semi_Axis_2 (µm),Ellipsoid_Semi_Axis_3 (µm),cpx_factor,cpx_factor_capped,Sphericity,Equivalent Radius (µm),elong_axis_ratio,flat_axis_ratio,shape_class,shape_class_no_cpx,Equivalent Diameter (µm),Volume3D (mm³)
0,1,LoF,1,False,True,,0,0.0,internal,2450.0,68300.0,350.0,76,2,260,90,2734,358,81.869585,1332.747552,306.463034,238829,3.087824e+08,1.612449e+05,3560.957732,-0.023655,-0.999720,0.001143,-0.999636,0.023668,...,25.000000,1.108182,2.770454e+04,2.770454e+04,27.704540,0.000000,0.000000e+00,0.000000e+00,0.000000,2.737357e+08,572114,False,3.731703e+09,238829,45117.483428,1031.006985,153.215248,22558.741714,515.503492,76.607624,15.993351,False,0.042503,962.216557,43.760599,6.729141,Complex,Rod,1924.433114,3.731703
1,2,LoF,11,False,True,,0,0.0,internal,9825.0,27750.0,550.0,62,1499,791,84,2609,1184,71.822707,2087.571149,1000.860628,223460,3.029393e+07,4.130175e+06,6167.644258,-0.000224,-0.999999,-0.001075,0.999989,-0.000229,...,508.060074,203.969940,5.099249e+06,5.099249e+06,5099.248505,144.682419,3.617060e+06,3.617060e+06,3617.060471,NaN,0,True,3.491562e+09,223460,10817.104090,3994.085587,154.345091,5408.552045,1997.042793,77.172546,NaN,True,NaN,941.117257,2.708280,25.877633,None,Ellipsoidal,1882.234514,3.491563
2,3,LoF,7,False,True,,0,0.0,internal,13825.0,13250.0,425.0,86,853,1075,103,1383,1628,93.613604,1076.903200,1306.884567,135620,2.389551e+07,1.287003e+05,5006.127210,-0.728967,-0.684548,0.000966,-0.684307,0.728747,...,55.901700,204.838928,5.120973e+06,5.120973e+06,5120.973206,235.365677,5.884142e+06,5.884142e+06,5884.141922,NaN,0,True,2.119062e+09,135620,15618.533240,1146.230236,226.064848,7809.266620,573.115118,113.032424,NaN,True,NaN,796.804391,13.626000,5.070360,None,Rod,1593.608783,2.119063
3,4,LoF,6,False,True,,0,0.0,internal,1450.0,15900.0,275.0,78,762,380,89,1398,438,82.190236,1092.132435,411.213554,130932,1.426766e+07,1.190809e+05,1558.260566,-0.011564,-0.999933,0.000444,-0.999841,0.011557,...,1125.277710,80.224548,2.005614e+06,2.005614e+06,2005.613708,80.006248,2.000156e+06,2.000156e+06,2000.156212,3.632541e+07,73120,False,2.045812e+09,130932,15995.319551,1461.294093,167.161653,7997.659775,730.647046,83.580826,2.758867,False,0.214545,787.515432,10.945996,8.741802,Complex,Rod,1575.030864,2.045813
4,5,LoF,3,False,True,,0,0.0,internal,1725.0,27775.0,275.0,75,497,153,86,1608,222,80.300495,1074.699207,185.778237,114248,2.606225e+07,2.035474e+05,1232.198932,-0.029806,-0.999550,0.003302,-0.999555,0.029802,...,1125.277710,83.382385,2.084560e+06,2.084560e+06,2084.559631,84.237762,2.105944e+06,2.105944e+06,2105.944061,4.214306e+07,86852,False,1.785125e+09,114248,17769.271145,1570.349625,122.181103,8884.635572,785.174813,61.090551,7.175898,False,0.168864,752.534949,11.315487,12.852639,Complex,Rod,1505.069899,1.785125

                           count         mean          std        min         25%          50%          75%           max
label                     2023.0  1012.000000   584.134117   1.000000  506.500000  1012.000000  1517.500000   2023.000000
ranking                   2023.0    84.438952   160.579746   0.000000    0.000000     0.000000    78.500000    584.000000
border_touch_voxel_count  2023.0     5.741967   139.020833   0.000000    0.000000     0.000000     0.000000   5161.000000
border_touch_fraction     2023.0     0.001695     0.030025   0.000000    0.000000     0.000000     0.000000      0.913386
BoundingBox_Dx (µm)       2023.0   523.887790  1160.102435  50.000000  100.000000   175.000000   425.000000  13825.000000
...                          ...          ...          ...        ...         ...          ...          ...           ...
Equivalent Radius (µm)    2023.0   110.806904   106.235904  32.259526   35.506202    70.012096   147.139642    962.216557
elong_axis_ratio          2023.0     5.231373     6.401344   1.000000    1.678646     2.616265     6.197189     63.939714
flat_axis_ratio           2023.0     2.237117     3.223696   1.000000    1.345981     1.643859     2.144135     89.902854
Equivalent Diameter (µm)  2023.0   221.613808   212.471808  64.519051   71.012404   140.024193   294.279285   1924.433114
Volume3D (mm³)            2023.0     0.033773     0.166356   0.000141    0.000188     0.001438     0.013344      3.731703

[125 rows x 8 columns]

2,023 pores x 134 columns
status               ok
group
Border                6
Classification        4
Complexity            2
Distance to surface  12
Ellipsoid            30
Feret                 4
Orientation           6
Position             12
Size                  5
Surface               4
Tensor shape         34

Empty DataFrame
Columns: [group, column, status, n_nan]
Index: []

columns present but not in the spec groups: ['label', 'Elongation', 'Flatness', 'Anisotropy', 'elongation_avg', 'flatness_avg', 'Inertia_Ixx (µm²)', 'Inertia_Ixy (µm²)', 'Inertia_Ixz (µm²)', 'Inertia_Iyy (µm²)', 'Inertia_Iyz (µm²)', 'Inertia_Izz (µm²)', 'elong_axis_ratio', 'flat_axis_ratio', 'Volume3D (mm³)']

columns with NaNs: 8

                     n_nan        pct
cpx_factor             611  30.202669
shape_class            611  30.202669
Area3D (µm²)             3   0.148295
Sphericity               3   0.148295
Cov_Phi (degrees)        1   0.049432
Cov_Theta (degrees)      1   0.049432
Phi (degrees)            1   0.049432
Theta (degrees)          1   0.049432

Area3D_capped: 3 of 2023 pores capped
cpx_factor_capped: 3 of 2023 pores capped

                                                check  max_rel_err  passed
0      Volume3D (µm³) == volume_voxels·(res_nm/1000)³          0.0    True
1                         num_pixels == volume_voxels          0.0    True
2             Equivalent Radius (µm) == (3V/4π)^(1/3)          0.0    True
3       shortest_distance_to_surface_um == vox·res_um          0.0    True
4   shortest_distance_to_surface (legacy) == vox·r...          0.0    True
5       shortest_distance_to_surface_nm == vox·res_nm          0.0    True
6           mean_distance_to_surface_um == vox·res_um          0.0    True
7   mean_distance_to_surface (legacy) == vox·res_n...          0.0    True
8           mean_distance_to_surface_nm == vox·res_nm          0.0    True
9       centroid_distance_to_surface_um == vox·res_um          0.0    True
10  centroid_distance_to_surface (legacy) == vox·r...          0.0    True
11      centroid_distance_to_surface_nm == vox·res_nm          0.0    True

ALL UNIT CHECKS PASSED  (volume in µm³, legacy distance columns in nm, *_um in µm, *_vox in voxels)

                                   value
voxel_size_um               2.500000e+01
box_voxels                  8.917492e+08
box_volume_mm3              1.393358e+04
material_voxels             8.189699e+08
material_volume_mm3         1.279640e+04
defect_count                2.023000e+03
porosity_pct                5.339165e-01
porosity_box_pct            4.903414e-01
porosity_internal_only_pct  5.143685e-01
defect_density_per_mm3      1.580913e-01
total_defect_volume_um3     6.832211e+10
total_defect_volume_mm3     6.832211e+01
largest_volume_um3          3.731703e+09
largest_eq_diameter_um      1.924433e+03
median_eq_diameter_um       1.400242e+02
pore_voxels_in_table        4.372615e+06
pore_voxels_in_volume       4.372615e+06
n_boundary_touching         1.400000e+01
n_area_capped               3.000000e+00
n_cpx_capped                3.000000e+00

counts_by_type {'Pore': 1434, 'LoF': 584, 'Border': 5}
counts_by_shape_class {'Complex': 1350, 'None': 611, 'Ellipsoidal': 49, 'Disc': 12, 'Spherical': 1}
counts_by_shape_class_no_cpx {'Rod': 909, 'Ellipsoidal': 895, 'Disc': 210, 'Spherical': 9}
counts_by_border_class {'internal': 2009, 'single_face': 14}

pore voxels in volume − in table = 0  (non-zero only if MIN_SIZE/MAX_SIZE filtering removed pores)
Cov_Elongation/Cov_Flatness <= 0 (numerically degenerate, no shape class): 0; NaN: 0
Sphericity > 1 (voxelised area of tiny pores): 359; pores with <= 1 voxel: 0  (use MIN_SIZE_VOXELS to drop them)

/tmp/ipykernel_2127584/872339919.py:256: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  if SHOW_PLOTS: plt.show()
/tmp/ipykernel_2127584/872339919.py:256: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  if SHOW_PLOTS: plt.show()
slices z: 100%|██████████| 164/164 [00:04<00:00, 40.11it/s]
slices y: 100%|██████████| 3227/3227 [00:04<00:00, 772.13it/s]
slices x: 100%|██████████| 1685/1685 [00:12<00:00, 140.18it/s]

{'z': {'mean_pct': 0.5351145374306823, 'max_pct': 5.096977337923063}, 'y': {'mean_pct': 0.5325011733526269, 'max_pct': 1.7443497648869568}, 'x': {'mean_pct': 0.7470263701517647, 'max_pct': 95.31615925058549}}
written to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/7/onlypores files/pore_analysis
   figures/hist_phi_theta.png
   figures/hist_volume_diameter_sphericity_elongation.png
   figures/porosity_profile_slices.png
   figures/porosity_vs_z_slabs.png
   figures/projection_z.png
   figures/scatter_volume_sphericity_by_type.png
   pores.csv
   pores.parquet
   pores_raw.key.json
   pores_raw.parquet
   run_config.json
   slice_profile_x.csv
   slice_profile_x.key.json
   slice_profile_y.csv
   slice_profile_y.key.json
   slice_profile_z.csv
   slice_profile_z.key.json
   specimen_summary.json

====================================================================================================
[4/7] volume_eq_aligned  (/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/8/onlypores files)
====================================================================================================
voxel size  : 0.025 mm = 25 µm = 25000 nm
OUT_DIR     : /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/8/onlypores files/pore_analysis
free disk at OUT: 5368 GB
pores TIFF: (202, 3228, 1660) uint8 | mask TIFF: (202, 3228, 1660) uint8
walls: front=10, back=176 -> analysing z in [10, 176) of 202 (excluded 10 front + 26 back slices from pores AND mask)
working box (Z,Y,X) = (166,3228,1660)  -> DIMENSIONS (X,Y,Z) = (1660, 3228, 166); 889.5 Mvoxels; box volume = 13898.558 mm³
estimated peak backend memory ≈ 8.3 GB (available 226 GB)

value histogram (sampled pages):
  pores: {0: 85358995, 255: 376685}
  mask : {0: 7708475, 255: 78027205}

   invert_pores  invert_mask  pore_frac_of_box  pores_outside_mask_frac
0         False        False          0.004394                 0.000000
1         False         True          0.004394                 1.000000
2          True        False          0.995606                 0.090307
3          True         True          0.995606                 0.909693

POLARITY -> invert_pores=False (auto), invert_mask=False (auto)  [pores are non-zero in the file, material is non-zero]

TIFF -> RAW: 100%|██████████| 166/166 [00:16<00:00, 10.16it/s]
/tmp/ipykernel_2127584/872339919.py:141: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.tight_layout(); (plt.show() if SHOW_PLOTS else plt.close('all'))

converted in 16s

RAW sizes OK (889507680 bytes each)
pore voxels     : 8,700,867  (0.978% of box)
material voxels : 810,123,949  (91.08% of box)
pore voxels outside mask: 0
VVF (pore voxels / material voxels) = 1.0740 %
PipelineConfig.validate() -> []

pipeline: 100%|██████████| 100% , Pipeline complete

4,930 pores in 46s; cached to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/8/onlypores files/pore_analysis/pores_raw.parquet
type        : {'Pore': 3084, 'LoF': 1844, 'Border': 2}
shape_class : {'Complex': 4072, None: 793, 'Ellipsoidal': 54, 'Disc': 10, 'Rod': 1}
no_cpx class: {'Rod': 2940, 'Ellipsoidal': 1723, 'Disc': 253, 'Spherical': 14}
border      : {'internal': 4918, 'single_face': 12}

,label,type,ranking,is_boundary_touching,is_internal_defect,touching_border_faces,border_touch_voxel_count,border_touch_fraction,border_classification,BoundingBox_Dx (µm),BoundingBox_Dy (µm),BoundingBox_Dz (µm),bbox-0,bbox-1,bbox-2,bbox-3,bbox-4,bbox-5,centroid-0,centroid-1,centroid-2,num_pixels,Covariance_Eigenvalue_1,Covariance_Eigenvalue_2,Covariance_Eigenvalue_3,Covariance_Eigenvector_1_x,Covariance_Eigenvector_1_y,Covariance_Eigenvector_1_z,Covariance_Eigenvector_2_x,Covariance_Eigenvector_2_y,...,shortest_distance_to_surface_um,mean_distance_to_surface_vox,mean_distance_to_surface,mean_distance_to_surface_nm,mean_distance_to_surface_um,centroid_distance_to_surface_vox,centroid_distance_to_surface,centroid_distance_to_surface_nm,centroid_distance_to_surface_um,Area3D (µm²),border_voxel_count,Area3D_capped,Volume3D (µm³),volume_voxels,Ellipsoid_Major_Axis_Length (µm),Ellipsoid_Medium_Axis_Length (µm),Ellipsoid_Minor_Axis_Length (µm),Ellipsoid_Semi_Axis_1 (µm),Ellipsoid_Semi_Axis_2 (µm),Ellipsoid_Semi_Axis_3 (µm),cpx_factor,cpx_factor_capped,Sphericity,Equivalent Radius (µm),elong_axis_ratio,flat_axis_ratio,shape_class,shape_class_no_cpx,Equivalent Diameter (µm),Volume3D (mm³)
0,1,LoF,3,False,True,,0,0.0,internal,8175.0,26975.0,475.0,52,1247,1132,71,2326,1459,59.142011,1701.164591,1253.975034,292033,3.686973e+07,2.881008e+06,4045.552385,-0.259605,0.965709,-0.003378,0.965698,0.259619,...,117.260385,226.548706,5.663718e+06,5.663718e+06,5663.717651,258.009705,6.450243e+06,6.450243e+06,6450.242615,NaN,0,True,4.563016e+09,292033,14384.254862,4020.912792,150.675038,7192.127431,2010.456396,75.337519,NaN,True,NaN,1028.934625,3.577361,26.685992,None,Rod,2057.869251,4.563016
1,2,Pore,0,False,True,,0,0.0,internal,5325.0,26475.0,325.0,52,1360,794,65,2419,1007,58.352008,2021.884822,891.281164,174834,4.805546e+07,1.005566e+06,2523.655961,-0.033531,-0.999438,-0.000015,-0.999421,0.033531,...,2543.373871,265.310822,6.632771e+06,6.632771e+06,6632.770538,291.940063,7.298502e+06,7.298502e+06,7298.501587,5.175357e+07,108968,False,2.731781e+09,174834,17073.525767,2469.773702,123.727695,8536.762883,1234.886851,61.863847,17.164430,False,0.182603,867.199669,6.912992,19.961365,Complex,Rod,1734.399338,2.731781
2,3,LoF,69,False,True,,0,0.0,internal,14125.0,13325.0,625.0,53,3,15,78,536,580,64.506415,248.833045,271.883462,153856,2.065290e+07,8.576443e+06,15951.255124,-0.681123,0.732163,0.003063,0.731918,0.680993,...,25.000000,12.455123,3.113781e+05,3.113781e+05,311.378074,19.104973,4.776243e+05,4.776243e+05,477.624321,NaN,0,True,2.404000e+09,153856,6352.654774,4093.722252,176.547760,3176.327387,2046.861126,88.273880,NaN,True,NaN,831.027288,1.551804,23.187619,None,Ellipsoidal,1662.054576,2.404000
3,4,LoF,5,False,True,,0,0.0,internal,4275.0,16125.0,375.0,54,133,753,69,778,924,60.757016,546.570072,834.148057,138116,1.992490e+07,6.345680e+05,2326.533090,-0.067059,0.997748,0.001743,0.997709,0.067040,...,50.000000,129.996643,3.249916e+06,3.249916e+06,3249.916077,182.838730,4.570968e+06,4.570968e+06,4570.968246,4.322303e+07,92066,False,2.158062e+09,138116,12881.188420,2298.777677,139.191428,6440.594210,1149.388838,69.595714,12.389788,False,0.186844,801.662932,5.603495,16.515224,Complex,Rod,1603.325865,2.158063
4,5,LoF,62,False,True,,0,0.0,internal,18575.0,12100.0,475.0,28,2397,95,47,2881,838,35.386745,2704.940686,384.832035,98830,1.874508e+07,7.246276e+06,4972.417153,-0.944031,-0.329843,-0.003092,-0.329827,0.944030,...,25.000000,3.049838,7.624595e+04,7.624595e+04,76.245946,33.015148,8.253787e+05,8.253787e+05,825.378704,NaN,0,True,1.544219e+09,98830,6628.554026,4121.283821,107.959005,3314.277013,2060.641911,53.979503,NaN,True,NaN,717.034531,1.608371,38.174526,None,Ellipsoidal,1434.069061,1.544219

                           count          mean           std        min          25%          50%          75%           max
label                     4930.0   2465.500000  1.423313e+03   1.000000  1233.250000  2465.500000  3697.750000  4.930000e+03
ranking                   4930.0    345.048682  5.525380e+02   0.000000     0.000000     0.000000   611.750000  1.844000e+03
border_touch_voxel_count  4930.0      1.573022  4.715753e+01   0.000000     0.000000     0.000000     0.000000  2.199000e+03
border_touch_fraction     4930.0      0.000561  1.945501e-02   0.000000     0.000000     0.000000     0.000000  9.183670e-01
BoundingBox_Dx (µm)       4930.0    793.803245  1.334015e+03  50.000000   125.000000   300.000000   850.000000  1.997500e+04
...                          ...           ...           ...        ...          ...          ...          ...           ...
Equivalent Radius (µm)    4930.0    115.836865  9.403702e+01  32.259526    50.242369    84.890369   149.832438  1.028935e+03
elong_axis_ratio          4930.0      5.980282  5.763702e+00   1.003982     2.100025     3.846439     7.838260  6.488121e+01
flat_axis_ratio           4930.0  35051.544767  2.460947e+06   1.000000     1.376024     1.664431     2.200230  1.727928e+08
Equivalent Diameter (µm)  4930.0    231.673730  1.880740e+02  64.519051   100.484739   169.780738   299.664875  2.057869e+03
Volume3D (mm³)            4930.0      0.027576  1.253821e-01   0.000141     0.000531     0.002563     0.014090  4.563016e+00

[125 rows x 8 columns]

4,930 pores x 134 columns
status               ok
group
Border                6
Classification        4
Complexity            2
Distance to surface  12
Ellipsoid            30
Feret                 4
Orientation           6
Position             12
Size                  5
Surface               4
Tensor shape         34

Empty DataFrame
Columns: [group, column, status, n_nan]
Index: []

columns present but not in the spec groups: ['label', 'Elongation', 'Flatness', 'Anisotropy', 'elongation_avg', 'flatness_avg', 'Inertia_Ixx (µm²)', 'Inertia_Ixy (µm²)', 'Inertia_Ixz (µm²)', 'Inertia_Iyy (µm²)', 'Inertia_Iyz (µm²)', 'Inertia_Izz (µm²)', 'elong_axis_ratio', 'flat_axis_ratio', 'Volume3D (mm³)']

columns with NaNs: 4

              n_nan        pct
cpx_factor      793  16.085193
shape_class     793  16.085193
Area3D (µm²)      3   0.060852
Sphericity        3   0.060852

Area3D_capped: 3 of 4930 pores capped
cpx_factor_capped: 4 of 4930 pores capped

                                                check  max_rel_err  passed
0      Volume3D (µm³) == volume_voxels·(res_nm/1000)³          0.0    True
1                         num_pixels == volume_voxels          0.0    True
2             Equivalent Radius (µm) == (3V/4π)^(1/3)          0.0    True
3       shortest_distance_to_surface_um == vox·res_um          0.0    True
4   shortest_distance_to_surface (legacy) == vox·r...          0.0    True
5       shortest_distance_to_surface_nm == vox·res_nm          0.0    True
6           mean_distance_to_surface_um == vox·res_um          0.0    True
7   mean_distance_to_surface (legacy) == vox·res_n...          0.0    True
8           mean_distance_to_surface_nm == vox·res_nm          0.0    True
9       centroid_distance_to_surface_um == vox·res_um          0.0    True
10  centroid_distance_to_surface (legacy) == vox·r...          0.0    True
11      centroid_distance_to_surface_nm == vox·res_nm          0.0    True

ALL UNIT CHECKS PASSED  (volume in µm³, legacy distance columns in nm, *_um in µm, *_vox in voxels)

                                   value
voxel_size_um               2.500000e+01
box_voxels                  8.895077e+08
box_volume_mm3              1.389856e+04
material_voxels             8.101239e+08
material_volume_mm3         1.265819e+04
defect_count                4.930000e+03
porosity_pct                1.074017e+00
porosity_box_pct            9.781666e-01
porosity_internal_only_pct  1.038115e+00
defect_density_per_mm3      3.894713e-01
total_defect_volume_um3     1.359510e+11
total_defect_volume_mm3     1.359510e+02
largest_volume_um3          4.563016e+09
largest_eq_diameter_um      2.057869e+03
median_eq_diameter_um       1.697807e+02
pore_voxels_in_table        8.700867e+06
pore_voxels_in_volume       8.700867e+06
n_boundary_touching         1.200000e+01
n_area_capped               3.000000e+00
n_cpx_capped                4.000000e+00

counts_by_type {'Pore': 3084, 'LoF': 1844, 'Border': 2}
counts_by_shape_class {'Complex': 4072, 'None': 793, 'Ellipsoidal': 54, 'Disc': 10, 'Rod': 1}
counts_by_shape_class_no_cpx {'Rod': 2940, 'Ellipsoidal': 1723, 'Disc': 253, 'Spherical': 14}
counts_by_border_class {'internal': 4918, 'single_face': 12}

pore voxels in volume − in table = 0  (non-zero only if MIN_SIZE/MAX_SIZE filtering removed pores)
Cov_Elongation/Cov_Flatness <= 0 (numerically degenerate, no shape class): 0; NaN: 0
Sphericity > 1 (voxelised area of tiny pores): 377; pores with <= 1 voxel: 0  (use MIN_SIZE_VOXELS to drop them)

/tmp/ipykernel_2127584/872339919.py:256: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  if SHOW_PLOTS: plt.show()
/tmp/ipykernel_2127584/872339919.py:256: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  if SHOW_PLOTS: plt.show()
slices z: 100%|██████████| 166/166 [00:04<00:00, 40.44it/s]
slices y: 100%|██████████| 3228/3228 [00:04<00:00, 783.96it/s]
slices x: 100%|██████████| 1660/1660 [00:11<00:00, 146.01it/s]

{'z': {'mean_pct': 1.0734067742610445, 'max_pct': 6.344852002247552}, 'y': {'mean_pct': 1.0746207174913134, 'max_pct': 2.8348427950813635}, 'x': {'mean_pct': 1.2749899347973643, 'max_pct': 93.30655957161981}}
written to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/8/onlypores files/pore_analysis
   figures/hist_phi_theta.png
   figures/hist_volume_diameter_sphericity_elongation.png
   figures/porosity_profile_slices.png
   figures/porosity_vs_z_slabs.png
   figures/projection_z.png
   figures/scatter_volume_sphericity_by_type.png
   pores.csv
   pores.parquet
   pores_raw.key.json
   pores_raw.parquet
   run_config.json
   slice_profile_x.csv
   slice_profile_x.key.json
   slice_profile_y.csv
   slice_profile_y.key.json
   slice_profile_z.csv
   slice_profile_z.key.json
   specimen_summary.json

====================================================================================================
[5/7] volume_eq_aligned  (/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/10/onlypores files)
====================================================================================================
voxel size  : 0.025 mm = 25 µm = 25000 nm
OUT_DIR     : /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/10/onlypores files/pore_analysis
free disk at OUT: 5368 GB
pores TIFF: (205, 3227, 1579) uint8 | mask TIFF: (205, 3227, 1579) uint8
walls: front=8, back=173 -> analysing z in [8, 173) of 205 (excluded 8 front + 32 back slices from pores AND mask)
working box (Z,Y,X) = (165,3227,1579)  -> DIMENSIONS (X,Y,Z) = (1579, 3227, 165); 840.7 Mvoxels; box volume = 13136.663 mm³
estimated peak backend memory ≈ 7.8 GB (available 226 GB)

value histogram (sampled pages):
  pores: {0: 81185406, 255: 341522}
  mask : {0: 3384552, 255: 78142376}

   invert_pores  invert_mask  pore_frac_of_box  pores_outside_mask_frac
0         False        False          0.004189                 0.000000
1         False         True          0.004189                 1.000000
2          True        False          0.995811                 0.041689
3          True         True          0.995811                 0.958311

POLARITY -> invert_pores=False (auto), invert_mask=False (auto)  [pores are non-zero in the file, material is non-zero]

TIFF -> RAW: 100%|██████████| 165/165 [00:15<00:00, 10.60it/s]
/tmp/ipykernel_2127584/872339919.py:141: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.tight_layout(); (plt.show() if SHOW_PLOTS else plt.close('all'))

converted in 16s

RAW sizes OK (840746445 bytes each)
pore voxels     : 6,611,711  (0.786% of box)
material voxels : 806,564,666  (95.93% of box)
pore voxels outside mask: 0
VVF (pore voxels / material voxels) = 0.8197 %
PipelineConfig.validate() -> []

pipeline: 100%|██████████| 100% , Pipeline complete

145,691 pores in 358s; cached to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/10/onlypores files/pore_analysis/pores_raw.parquet
type        : {'Pore': 144417, 'LoF': 1201, 'Border': 73}
shape_class : {None: 96175, 'Complex': 49454, 'Ellipsoidal': 48, 'Disc': 13, 'Rod': 1}
no_cpx class: {'Ellipsoidal': 99442, 'Disc': 27206, 'Rod': 18968, 'Spherical': 67, None: 8}
border      : {'internal': 145593, 'single_face': 98}

,label,type,ranking,is_boundary_touching,is_internal_defect,touching_border_faces,border_touch_voxel_count,border_touch_fraction,border_classification,BoundingBox_Dx (µm),BoundingBox_Dy (µm),BoundingBox_Dz (µm),bbox-0,bbox-1,bbox-2,bbox-3,bbox-4,bbox-5,centroid-0,centroid-1,centroid-2,num_pixels,Covariance_Eigenvalue_1,Covariance_Eigenvalue_2,Covariance_Eigenvalue_3,Covariance_Eigenvector_1_x,Covariance_Eigenvector_1_y,Covariance_Eigenvector_1_z,Covariance_Eigenvector_2_x,Covariance_Eigenvector_2_y,...,shortest_distance_to_surface_um,mean_distance_to_surface_vox,mean_distance_to_surface,mean_distance_to_surface_nm,mean_distance_to_surface_um,centroid_distance_to_surface_vox,centroid_distance_to_surface,centroid_distance_to_surface_nm,centroid_distance_to_surface_um,Area3D (µm²),border_voxel_count,Area3D_capped,Volume3D (µm³),volume_voxels,Ellipsoid_Major_Axis_Length (µm),Ellipsoid_Medium_Axis_Length (µm),Ellipsoid_Minor_Axis_Length (µm),Ellipsoid_Semi_Axis_1 (µm),Ellipsoid_Semi_Axis_2 (µm),Ellipsoid_Semi_Axis_3 (µm),cpx_factor,cpx_factor_capped,Sphericity,Equivalent Radius (µm),elong_axis_ratio,flat_axis_ratio,shape_class,shape_class_no_cpx,Equivalent Diameter (µm),Volume3D (mm³)
0,1,LoF,46,True,False,z_max,2152,0.006843,single_face,13725.0,14150.0,1075.0,122,724,553,165,1290,1102,147.424313,1022.336931,829.640442,314492,1.588664e+07,6.428043e+06,55719.797346,-0.386994,-0.922067,-0.005332,-0.922042,0.387024,...,25.000000,13.652820,3.413205e+05,3.413205e+05,341.320491,0.000000,0.000000e+00,0.000000e+00,0.000000,NaN,0,True,4.913938e+09,314492,6292.255437,4002.484288,372.644766,3146.127719,2001.242144,186.322383,NaN,True,NaN,1054.662910,1.572087,10.740750,None,Ellipsoidal,2109.325819,4.913938
1,2,LoF,131,True,False,z_max,1765,0.016819,single_face,7975.0,6200.0,1100.0,121,2602,963,165,2850,1282,154.234887,2748.301163,1157.687641,104940,2.306386e+06,1.096180e+06,20451.771872,-0.990817,0.077018,-0.111132,0.076937,0.997023,...,25.000000,42.322746,1.058069e+06,1.058069e+06,1058.068657,35.791061,8.947765e+05,8.947765e+05,894.776535,5.269019e+07,119594,False,1.639688e+09,104940,3640.234496,2509.598894,342.790509,1820.117248,1254.799447,171.395254,33.927387,False,0.127623,731.516555,1.450524,7.321086,Complex,Disc,1463.033109,1.639688
2,3,LoF,127,True,False,z_max,12,0.000172,single_face,8125.0,5725.0,1000.0,125,2562,385,165,2791,710,148.393786,2711.237989,580.873048,69751,2.697021e+06,8.927994e+05,12750.163667,-0.974966,0.195924,-0.105144,0.192764,0.980449,...,25.000000,17.686510,4.421628e+05,4.421628e+05,442.162752,10.630146,2.657537e+05,2.657537e+05,265.753651,5.211500e+07,122594,False,1.089859e+09,69751,3747.201885,2155.966000,257.645667,1873.600943,1077.983000,128.822833,43.073633,False,0.098273,638.401578,1.738062,8.367950,Complex,Ellipsoidal,1276.803156,1.089859
3,4,LoF,35,False,True,,0,0.000000,internal,16850.0,8150.0,375.0,21,2202,130,36,2528,804,28.590006,2429.865600,491.871208,69018,1.534420e+07,2.347441e+06,3290.664588,-0.987800,0.155724,0.001396,0.155729,0.987701,...,61.237246,98.706947,2.467674e+06,2.467674e+06,2467.673683,63.277164,1.581929e+06,1.581929e+06,1581.929111,2.458010e+07,56532,False,1.078406e+09,69018,7110.983126,2781.344939,104.135612,3555.491563,1390.672470,52.067806,50.169260,False,0.206898,636.157418,2.556671,26.708874,Complex,Ellipsoidal,1272.314836,1.078406
4,5,LoF,10,False,True,,0,0.000000,internal,2050.0,11275.0,475.0,43,2100,1122,62,2551,1204,51.441535,2334.691445,1141.563573,57941,9.242298e+06,6.602083e+04,5268.461301,0.005434,0.999976,0.004379,0.995095,-0.004975,...,108.972466,182.366943,4.559174e+06,4.559174e+06,4559.173584,200.860641,5.021516e+06,5.021516e+06,5021.516037,1.475310e+07,33042,False,9.053281e+08,57941,9498.061938,802.759567,226.770680,4749.030969,401.379784,113.385340,11.949725,False,0.306764,600.121428,11.831764,3.539962,Complex,Rod,1200.242857,0.905328

                             count          mean            std        min           25%           50%            75%           max
label                     145691.0  72846.000000   42057.513372   1.000000  36423.500000  72846.000000  109268.500000  1.456910e+05
ranking                   145691.0      4.954328      62.800465   0.000000      0.000000      0.000000       0.000000  1.201000e+03
border_touch_voxel_count  145691.0      0.088749      18.757789   0.000000      0.000000      0.000000       0.000000  6.544000e+03
border_touch_fraction     145691.0      0.000194       0.009933   0.000000      0.000000      0.000000       0.000000  9.552240e-01
BoundingBox_Dx (µm)       145691.0    137.664646     230.712711  50.000000    100.000000    125.000000     150.000000  1.685000e+04
...                            ...           ...            ...        ...           ...           ...            ...           ...
Equivalent Radius (µm)    145691.0     38.402940      17.254201  32.259526     33.412615     35.506202      39.079632  1.054663e+03
elong_axis_ratio          145691.0      2.173488       1.202125   1.000000      1.549193      1.956303       2.519913  9.867096e+01
flat_axis_ratio           145683.0   1807.431928  366486.180076   1.000000      1.489043      1.846492       2.352348  8.783880e+07
Equivalent Diameter (µm)  145691.0     76.805880      34.508402  64.519051     66.825231     71.012404      78.159264  2.109326e+03
Volume3D (mm³)            145691.0      0.000709       0.017170   0.000141      0.000156      0.000188       0.000250  4.913938e+00

[125 rows x 8 columns]

145,691 pores x 134 columns
status               ok
group
Border                6
Classification        4
Complexity            2
Distance to surface  12
Ellipsoid            30
Feret                 4
Orientation           6
Position             12
Size                  5
Surface               4
Tensor shape         34

Empty DataFrame
Columns: [group, column, status, n_nan]
Index: []

columns present but not in the spec groups: ['label', 'Elongation', 'Flatness', 'Anisotropy', 'elongation_avg', 'flatness_avg', 'Inertia_Ixx (µm²)', 'Inertia_Ixy (µm²)', 'Inertia_Ixz (µm²)', 'Inertia_Iyy (µm²)', 'Inertia_Iyz (µm²)', 'Inertia_Izz (µm²)', 'elong_axis_ratio', 'flat_axis_ratio', 'Volume3D (mm³)']

columns with NaNs: 18

                                   n_nan        pct
shape_class                        96175  66.013000
cpx_factor                         96175  66.013000
Cov_Phi (degrees)                     13   0.008923
Cov_Theta (degrees)                   13   0.008923
Phi (degrees)                         13   0.008923
Theta (degrees)                       13   0.008923
flatness_avg                           8   0.005491
Ellipsoid_Semi_Axis_2 (µm)             8   0.005491
flat_axis_ratio                        8   0.005491
Ellipsoid_Semi_Axis_3 (µm)             8   0.005491
Ellipsoid_Minor_Axis_Length (µm)       8   0.005491
Ellipsoid_Semi_Axis_1 (µm)             8   0.005491
Cov_flatness_avg                       8   0.005491
Ellipsoid_Medium_Axis_Length (µm)      8   0.005491
Ellipsoid_Major_Axis_Length (µm)       8   0.005491
shape_class_no_cpx                     8   0.005491
Sphericity                             1   0.000686
Area3D (µm²)                           1   0.000686

Area3D_capped: 1 of 145691 pores capped
cpx_factor_capped: 1 of 145691 pores capped

                                                check  max_rel_err  passed
0      Volume3D (µm³) == volume_voxels·(res_nm/1000)³          0.0    True
1                         num_pixels == volume_voxels          0.0    True
2             Equivalent Radius (µm) == (3V/4π)^(1/3)          0.0    True
3       shortest_distance_to_surface_um == vox·res_um          0.0    True
4   shortest_distance_to_surface (legacy) == vox·r...          0.0    True
5       shortest_distance_to_surface_nm == vox·res_nm          0.0    True
6           mean_distance_to_surface_um == vox·res_um          0.0    True
7   mean_distance_to_surface (legacy) == vox·res_n...          0.0    True
8           mean_distance_to_surface_nm == vox·res_nm          0.0    True
9       centroid_distance_to_surface_um == vox·res_um          0.0    True
10  centroid_distance_to_surface (legacy) == vox·r...          0.0    True
11      centroid_distance_to_surface_nm == vox·res_nm          0.0    True

ALL UNIT CHECKS PASSED  (volume in µm³, legacy distance columns in nm, *_um in µm, *_vox in voxels)

                                   value
voxel_size_um               2.500000e+01
box_voxels                  8.407464e+08
box_volume_mm3              1.313666e+04
material_voxels             8.065647e+08
material_volume_mm3         1.260257e+04
defect_count                1.456910e+05
porosity_pct                8.197372e-01
porosity_box_pct            7.864096e-01
porosity_internal_only_pct  7.394959e-01
defect_density_per_mm3      1.156042e+01
total_defect_volume_um3     1.033080e+11
total_defect_volume_mm3     1.033080e+02
largest_volume_um3          4.913938e+09
largest_eq_diameter_um      2.109326e+03
median_eq_diameter_um       7.101240e+01
pore_voxels_in_table        6.611711e+06
pore_voxels_in_volume       6.611711e+06
n_boundary_touching         9.800000e+01
n_area_capped               1.000000e+00
n_cpx_capped                1.000000e+00

counts_by_type {'Pore': 144417, 'LoF': 1201, 'Border': 73}
counts_by_shape_class {'None': 96175, 'Complex': 49454, 'Ellipsoidal': 48, 'Disc': 13, 'Rod': 1}
counts_by_shape_class_no_cpx {'Ellipsoidal': 99442, 'Disc': 27206, 'Rod': 18968, 'Spherical': 67, 'None': 8}
counts_by_border_class {'internal': 145593, 'single_face': 98}

pore voxels in volume − in table = 0  (non-zero only if MIN_SIZE/MAX_SIZE filtering removed pores)
Cov_Elongation/Cov_Flatness <= 0 (numerically degenerate, no shape class): 8; NaN: 0
Sphericity > 1 (voxelised area of tiny pores): 13814; pores with <= 1 voxel: 0  (use MIN_SIZE_VOXELS to drop them)

/tmp/ipykernel_2127584/872339919.py:256: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  if SHOW_PLOTS: plt.show()
/tmp/ipykernel_2127584/872339919.py:256: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  if SHOW_PLOTS: plt.show()
slices z: 100%|██████████| 165/165 [00:03<00:00, 42.30it/s]
slices y: 100%|██████████| 3227/3227 [00:03<00:00, 808.80it/s]
slices x: 100%|██████████| 1579/1579 [00:11<00:00, 138.65it/s]

{'z': {'mean_pct': 0.8188581503555645, 'max_pct': 3.2429549521893617}, 'y': {'mean_pct': 0.8229288359436352, 'max_pct': 3.2640984627022087}, 'x': {'mean_pct': 1.0393103666971488, 'max_pct': 100.0}}
written to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/10/onlypores files/pore_analysis
   figures/hist_phi_theta.png
   figures/hist_volume_diameter_sphericity_elongation.png
   figures/porosity_profile_slices.png
   figures/porosity_vs_z_slabs.png
   figures/projection_z.png
   figures/scatter_volume_sphericity_by_type.png
   pores.csv
   pores.parquet
   pores_raw.key.json
   pores_raw.parquet
   run_config.json
   slice_profile_x.csv
   slice_profile_x.key.json
   slice_profile_y.csv
   slice_profile_y.key.json
   slice_profile_z.csv
   slice_profile_z.key.json
   specimen_summary.json

====================================================================================================
[6/7] volume_eq_aligned  (/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/11/onlypores files)
====================================================================================================
voxel size  : 0.025 mm = 25 µm = 25000 nm
OUT_DIR     : /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/11/onlypores files/pore_analysis
free disk at OUT: 5368 GB
pores TIFF: (203, 3228, 1599) uint8 | mask TIFF: (203, 3228, 1599) uint8
walls: front=14, back=179 -> analysing z in [14, 179) of 203 (excluded 14 front + 24 back slices from pores AND mask)
working box (Z,Y,X) = (165,3228,1599)  -> DIMENSIONS (X,Y,Z) = (1599, 3228, 165); 851.7 Mvoxels; box volume = 13307.178 mm³
estimated peak backend memory ≈ 7.9 GB (available 225 GB)

value histogram (sampled pages):
  pores: {0: 82077006, 255: 508146}
  mask : {0: 2606250, 255: 79978902}

   invert_pores  invert_mask  pore_frac_of_box  pores_outside_mask_frac
0         False        False          0.006153                 0.000000
1         False         True          0.006153                 1.000000
2          True        False          0.993847                 0.031754
3          True         True          0.993847                 0.968246

POLARITY -> invert_pores=False (auto), invert_mask=False (auto)  [pores are non-zero in the file, material is non-zero]

TIFF -> RAW: 100%|██████████| 165/165 [00:15<00:00, 10.52it/s]
/tmp/ipykernel_2127584/872339919.py:141: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.tight_layout(); (plt.show() if SHOW_PLOTS else plt.close('all'))

converted in 16s

RAW sizes OK (851659380 bytes each)
pore voxels     : 7,140,442  (0.838% of box)
material voxels : 825,242,727  (96.90% of box)
pore voxels outside mask: 0
VVF (pore voxels / material voxels) = 0.8653 %
PipelineConfig.validate() -> []

pipeline: 100%|██████████| 100% , Pipeline complete

149,488 pores in 368s; cached to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/11/onlypores files/pore_analysis/pores_raw.parquet
type        : {'Pore': 148683, 'LoF': 771, 'Border': 34}
shape_class : {None: 99386, 'Complex': 50051, 'Ellipsoidal': 41, 'Disc': 8, 'Spherical': 2}
no_cpx class: {'Ellipsoidal': 102188, 'Disc': 28254, 'Rod': 18976, 'Spherical': 66, None: 4}
border      : {'internal': 149439, 'single_face': 47, 'edge': 2}

,label,type,ranking,is_boundary_touching,is_internal_defect,touching_border_faces,border_touch_voxel_count,border_touch_fraction,border_classification,BoundingBox_Dx (µm),BoundingBox_Dy (µm),BoundingBox_Dz (µm),bbox-0,bbox-1,bbox-2,bbox-3,bbox-4,bbox-5,centroid-0,centroid-1,centroid-2,num_pixels,Covariance_Eigenvalue_1,Covariance_Eigenvalue_2,Covariance_Eigenvalue_3,Covariance_Eigenvector_1_x,Covariance_Eigenvector_1_y,Covariance_Eigenvector_1_z,Covariance_Eigenvector_2_x,Covariance_Eigenvector_2_y,...,shortest_distance_to_surface_um,mean_distance_to_surface_vox,mean_distance_to_surface,mean_distance_to_surface_nm,mean_distance_to_surface_um,centroid_distance_to_surface_vox,centroid_distance_to_surface,centroid_distance_to_surface_nm,centroid_distance_to_surface_um,Area3D (µm²),border_voxel_count,Area3D_capped,Volume3D (µm³),volume_voxels,Ellipsoid_Major_Axis_Length (µm),Ellipsoid_Medium_Axis_Length (µm),Ellipsoid_Minor_Axis_Length (µm),Ellipsoid_Semi_Axis_1 (µm),Ellipsoid_Semi_Axis_2 (µm),Ellipsoid_Semi_Axis_3 (µm),cpx_factor,cpx_factor_capped,Sphericity,Equivalent Radius (µm),elong_axis_ratio,flat_axis_ratio,shape_class,shape_class_no_cpx,Equivalent Diameter (µm),Volume3D (mm³)
0,1,LoF,4,False,True,,0,0.000000,internal,6075.0,26375.0,550.0,100,1803,229,122,2858,472,110.166715,2381.001993,325.984633,291012,4.705149e+07,3.412923e+06,4143.800355,-0.085563,-0.996330,0.002250,-0.996295,0.085579,...,728.869009,162.301620,4.057541e+06,4.057541e+06,4057.540512,71.505241,1.787631e+06,1.787631e+06,1787.631035,NaN,0,True,4.547062e+09,291012,15089.713563,4064.036205,141.609939,7544.856781,2032.018103,70.804970,NaN,True,NaN,1027.734112,3.712987,28.698806,None,Rod,2055.468223,4.547063
1,2,LoF,83,True,False,z_max,537,0.002588,single_face,12525.0,9750.0,1300.0,113,835,588,165,1225,1089,138.252196,1065.618297,902.862639,207533,7.075400e+06,3.176756e+06,93909.581486,-0.924175,-0.379775,-0.040887,-0.381819,0.921511,...,25.000000,32.216282,8.054070e+05,8.054070e+05,805.407047,14.899665,3.724916e+05,3.724916e+05,372.491622,NaN,0,True,3.242703e+09,207533,4312.914958,2889.929909,496.878681,2156.457479,1444.964954,248.439340,NaN,True,NaN,918.204733,1.492394,5.816168,None,Disc,1836.409465,3.242703
2,3,LoF,62,True,False,z_max,1444,0.012336,single_face,11250.0,8700.0,1075.0,122,693,599,165,1041,1049,146.306778,827.534011,822.548423,117052,7.297937e+06,2.360021e+06,14475.900633,-0.985683,-0.136237,0.099338,-0.136764,0.990602,...,25.000000,8.320090,2.080023e+05,2.080023e+05,208.002257,1.000000,2.500000e+04,2.500000e+04,25.000000,NaN,0,True,1.828938e+09,117052,5166.620066,2938.085590,230.106705,2583.310033,1469.042795,115.053352,NaN,True,NaN,758.641772,1.758499,12.768362,None,Ellipsoidal,1517.283543,1.828938
3,4,LoF,28,False,True,,0,0.000000,internal,13125.0,10850.0,550.0,61,2480,355,83,2914,880,71.486562,2709.282346,609.396197,110021,1.545675e+07,1.922481e+06,6832.120910,-0.873929,0.486053,-0.001030,0.485993,0.873851,...,25.000000,115.029182,2.875730e+06,2.875730e+06,2875.729561,64.529060,1.613227e+06,1.613227e+06,1613.226509,NaN,0,True,1.719078e+09,110021,7621.996397,2688.071250,160.246103,3810.998198,1344.035625,80.123051,NaN,True,NaN,743.137200,2.835489,16.774643,None,Ellipsoidal,1486.274399,1.719078
4,5,LoF,57,True,False,"z_max,x_max",135,0.001433,edge,7250.0,31000.0,3625.0,20,1553,1309,165,2793,1599,101.878087,2105.319339,1581.835988,94182,4.838152e+07,1.082516e+06,575775.599995,-0.019896,-0.999484,-0.025233,0.914898,-0.028378,...,25.000000,1.370954,3.427384e+04,3.427384e+04,34.273839,13.490738,3.372684e+05,3.372684e+05,337.268448,NaN,0,True,1.471594e+09,94182,5563.844681,832.247357,606.962542,2781.922340,416.123679,303.481271,NaN,True,NaN,705.612786,6.685326,1.371168,None,Rod,1411.225572,1.471594

                             count          mean            std        min           25%           50%            75%           max
label                     149488.0  74744.500000   43153.612858   1.000000  37372.750000  74744.500000  112116.250000  1.494880e+05
ranking                   149488.0      1.990835      31.937382   0.000000      0.000000      0.000000       0.000000  7.710000e+02
border_touch_voxel_count  149488.0      0.053155      11.218323   0.000000      0.000000      0.000000       0.000000  3.955000e+03
border_touch_fraction     149488.0      0.000094       0.006849   0.000000      0.000000      0.000000       0.000000  9.000000e-01
BoundingBox_Dx (µm)       149488.0    135.286110     250.607823  50.000000    100.000000    125.000000     150.000000  2.182500e+04
...                            ...           ...            ...        ...           ...           ...            ...           ...
Equivalent Radius (µm)    149488.0     38.063759      16.812301  32.259526     33.412615     35.506202      39.079632  1.027734e+03
elong_axis_ratio          149488.0      2.160067       1.173113   1.000000      1.547240      1.954025       2.514116  6.923040e+01
flat_axis_ratio           149484.0   2813.513547  501582.509040   1.000000      1.493992      1.860594       2.372401  1.078208e+08
Equivalent Diameter (µm)  149488.0     76.127518      33.624601  64.519051     66.825231     71.012404      78.159264  2.055468e+03
Volume3D (mm³)            149488.0      0.000746       0.020514   0.000141      0.000156      0.000188       0.000250  4.547063e+00

[125 rows x 8 columns]

149,488 pores x 134 columns
status               ok
group
Border                6
Classification        4
Complexity            2
Distance to surface  12
Ellipsoid            30
Feret                 4
Orientation           6
Position             12
Size                  5
Surface               4
Tensor shape         34

Empty DataFrame
Columns: [group, column, status, n_nan]
Index: []

columns present but not in the spec groups: ['label', 'Elongation', 'Flatness', 'Anisotropy', 'elongation_avg', 'flatness_avg', 'Inertia_Ixx (µm²)', 'Inertia_Ixy (µm²)', 'Inertia_Ixz (µm²)', 'Inertia_Iyy (µm²)', 'Inertia_Iyz (µm²)', 'Inertia_Izz (µm²)', 'elong_axis_ratio', 'flat_axis_ratio', 'Volume3D (mm³)']

columns with NaNs: 18

                                   n_nan        pct
shape_class                        99386  66.484266
cpx_factor                         99386  66.484266
Cov_Phi (degrees)                     22   0.014717
Cov_Theta (degrees)                   22   0.014717
Phi (degrees)                         22   0.014717
Theta (degrees)                       22   0.014717
Area3D (µm²)                           7   0.004683
Sphericity                             7   0.004683
flatness_avg                           4   0.002676
Ellipsoid_Semi_Axis_3 (µm)             4   0.002676
flat_axis_ratio                        4   0.002676
Ellipsoid_Minor_Axis_Length (µm)       4   0.002676
Ellipsoid_Semi_Axis_2 (µm)             4   0.002676
Ellipsoid_Semi_Axis_1 (µm)             4   0.002676
Cov_flatness_avg                       4   0.002676
Ellipsoid_Medium_Axis_Length (µm)      4   0.002676
Ellipsoid_Major_Axis_Length (µm)       4   0.002676
shape_class_no_cpx                     4   0.002676

Area3D_capped: 7 of 149488 pores capped
cpx_factor_capped: 10 of 149488 pores capped

                                                check  max_rel_err  passed
0      Volume3D (µm³) == volume_voxels·(res_nm/1000)³          0.0    True
1                         num_pixels == volume_voxels          0.0    True
2             Equivalent Radius (µm) == (3V/4π)^(1/3)          0.0    True
3       shortest_distance_to_surface_um == vox·res_um          0.0    True
4   shortest_distance_to_surface (legacy) == vox·r...          0.0    True
5       shortest_distance_to_surface_nm == vox·res_nm          0.0    True
6           mean_distance_to_surface_um == vox·res_um          0.0    True
7   mean_distance_to_surface (legacy) == vox·res_n...          0.0    True
8           mean_distance_to_surface_nm == vox·res_nm          0.0    True
9       centroid_distance_to_surface_um == vox·res_um          0.0    True
10  centroid_distance_to_surface (legacy) == vox·r...          0.0    True
11      centroid_distance_to_surface_nm == vox·res_nm          0.0    True

ALL UNIT CHECKS PASSED  (volume in µm³, legacy distance columns in nm, *_um in µm, *_vox in voxels)

                                   value
voxel_size_um               2.500000e+01
box_voxels                  8.516594e+08
box_volume_mm3              1.330718e+04
material_voxels             8.252427e+08
material_volume_mm3         1.289442e+04
defect_count                1.494880e+05
porosity_pct                8.652536e-01
porosity_box_pct            8.384152e-01
porosity_internal_only_pct  7.960374e-01
defect_density_per_mm3      1.159323e+01
total_defect_volume_um3     1.115694e+11
total_defect_volume_mm3     1.115694e+02
largest_volume_um3          4.547062e+09
largest_eq_diameter_um      2.055468e+03
median_eq_diameter_um       7.101240e+01
pore_voxels_in_table        7.140442e+06
pore_voxels_in_volume       7.140442e+06
n_boundary_touching         4.900000e+01
n_area_capped               7.000000e+00
n_cpx_capped                1.000000e+01

counts_by_type {'Pore': 148683, 'LoF': 771, 'Border': 34}
counts_by_shape_class {'None': 99386, 'Complex': 50051, 'Ellipsoidal': 41, 'Disc': 8, 'Spherical': 2}
counts_by_shape_class_no_cpx {'Ellipsoidal': 102188, 'Disc': 28254, 'Rod': 18976, 'Spherical': 66, 'None': 4}
counts_by_border_class {'internal': 149439, 'single_face': 47, 'edge': 2}

pore voxels in volume − in table = 0  (non-zero only if MIN_SIZE/MAX_SIZE filtering removed pores)
Cov_Elongation/Cov_Flatness <= 0 (numerically degenerate, no shape class): 4; NaN: 0
Sphericity > 1 (voxelised area of tiny pores): 14404; pores with <= 1 voxel: 0  (use MIN_SIZE_VOXELS to drop them)

/tmp/ipykernel_2127584/872339919.py:256: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  if SHOW_PLOTS: plt.show()
/tmp/ipykernel_2127584/872339919.py:256: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  if SHOW_PLOTS: plt.show()
slices z: 100%|██████████| 165/165 [00:03<00:00, 42.57it/s]
slices y: 100%|██████████| 3228/3228 [00:04<00:00, 794.49it/s]
slices x: 100%|██████████| 1599/1599 [00:10<00:00, 145.81it/s]

{'z': {'mean_pct': 0.864566696005222, 'max_pct': 2.6571015559765483}, 'y': {'mean_pct': 0.8617572639470129, 'max_pct': 3.410141430725029}, 'x': {'mean_pct': 1.1910626986589044, 'max_pct': 100.0}}
written to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/11/onlypores files/pore_analysis
   figures/hist_phi_theta.png
   figures/hist_volume_diameter_sphericity_elongation.png
   figures/porosity_profile_slices.png
   figures/porosity_vs_z_slabs.png
   figures/projection_z.png
   figures/scatter_volume_sphericity_by_type.png
   pores.csv
   pores.parquet
   pores_raw.key.json
   pores_raw.parquet
   run_config.json
   slice_profile_x.csv
   slice_profile_x.key.json
   slice_profile_y.csv
   slice_profile_y.key.json
   slice_profile_z.csv
   slice_profile_z.key.json
   specimen_summary.json

====================================================================================================
[7/7] volume_eq_aligned  (/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/12/onlypores files)
====================================================================================================
voxel size  : 0.025 mm = 25 µm = 25000 nm
OUT_DIR     : /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/12/onlypores files/pore_analysis
free disk at OUT: 5368 GB
pores TIFF: (200, 3227, 1593) uint8 | mask TIFF: (200, 3227, 1593) uint8
walls: front=8, back=173 -> analysing z in [8, 173) of 200 (excluded 8 front + 27 back slices from pores AND mask)
working box (Z,Y,X) = (165,3227,1593)  -> DIMENSIONS (X,Y,Z) = (1593, 3227, 165); 848.2 Mvoxels; box volume = 13253.138 mm³
estimated peak backend memory ≈ 7.9 GB (available 226 GB)

value histogram (sampled pages):
  pores: {0: 82053474, 255: 196302}
  mask : {0: 2974157, 255: 79275619}

   invert_pores  invert_mask  pore_frac_of_box  pores_outside_mask_frac
0         False        False          0.002387                 0.000000
1         False         True          0.002387                 1.000000
2          True        False          0.997613                 0.036247
3          True         True          0.997613                 0.963753

POLARITY -> invert_pores=False (auto), invert_mask=False (auto)  [pores are non-zero in the file, material is non-zero]

TIFF -> RAW: 100%|██████████| 165/165 [00:15<00:00, 10.63it/s]
/tmp/ipykernel_2127584/872339919.py:141: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.tight_layout(); (plt.show() if SHOW_PLOTS else plt.close('all'))

converted in 16s

RAW sizes OK (848200815 bytes each)
pore voxels     : 5,820,953  (0.686% of box)
material voxels : 818,065,627  (96.45% of box)
pore voxels outside mask: 0
VVF (pore voxels / material voxels) = 0.7116 %
PipelineConfig.validate() -> []

pipeline: 100%|██████████| 100% , Pipeline complete

73,040 pores in 193s; cached to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/12/onlypores files/pore_analysis/pores_raw.parquet
type        : {'Pore': 72047, 'LoF': 950, 'Border': 43}
shape_class : {None: 50808, 'Complex': 22189, 'Ellipsoidal': 32, 'Disc': 9, 'Spherical': 2}
no_cpx class: {'Ellipsoidal': 48564, 'Disc': 13652, 'Rod': 10786, 'Spherical': 33, None: 5}
border      : {'internal': 72974, 'single_face': 64, 'edge': 2}

,label,type,ranking,is_boundary_touching,is_internal_defect,touching_border_faces,border_touch_voxel_count,border_touch_fraction,border_classification,BoundingBox_Dx (µm),BoundingBox_Dy (µm),BoundingBox_Dz (µm),bbox-0,bbox-1,bbox-2,bbox-3,bbox-4,bbox-5,centroid-0,centroid-1,centroid-2,num_pixels,Covariance_Eigenvalue_1,Covariance_Eigenvalue_2,Covariance_Eigenvalue_3,Covariance_Eigenvector_1_x,Covariance_Eigenvector_1_y,Covariance_Eigenvector_1_z,Covariance_Eigenvector_2_x,Covariance_Eigenvector_2_y,...,shortest_distance_to_surface_um,mean_distance_to_surface_vox,mean_distance_to_surface,mean_distance_to_surface_nm,mean_distance_to_surface_um,centroid_distance_to_surface_vox,centroid_distance_to_surface,centroid_distance_to_surface_nm,centroid_distance_to_surface_um,Area3D (µm²),border_voxel_count,Area3D_capped,Volume3D (µm³),volume_voxels,Ellipsoid_Major_Axis_Length (µm),Ellipsoid_Medium_Axis_Length (µm),Ellipsoid_Minor_Axis_Length (µm),Ellipsoid_Semi_Axis_1 (µm),Ellipsoid_Semi_Axis_2 (µm),Ellipsoid_Semi_Axis_3 (µm),cpx_factor,cpx_factor_capped,Sphericity,Equivalent Radius (µm),elong_axis_ratio,flat_axis_ratio,shape_class,shape_class_no_cpx,Equivalent Diameter (µm),Volume3D (mm³)
0,1,LoF,45,True,False,z_max,1887,0.009369,single_face,11625.0,12300.0,1075.0,122,2278,804,165,2770,1269,146.100998,2548.689439,1048.383823,201400,1.416693e+07,4.261074e+06,64054.843565,-0.777260,0.629144,-0.006646,0.628521,0.775921,...,25.000000,14.098755,3.524689e+05,3.524689e+05,352.468872,0.000000,0.000000e+00,0.000000e+00,0.000000,NaN,0,True,3.146875e+09,201400,5462.276128,2995.679844,367.292298,2731.138064,1497.839922,183.646149,NaN,True,NaN,909.069236,1.823384,8.156119,None,Ellipsoidal,1818.138472,3.146875
1,2,LoF,33,True,False,"y_max,x_max",2132,0.011366,edge,16275.0,40150.0,3800.0,6,1621,942,158,3227,1593,72.334041,2443.757994,1506.824050,187570,1.166528e+08,1.273630e+07,633051.185032,-0.243578,-0.969565,-0.024773,-0.964815,0.244834,...,25.000000,2.218765,5.546913e+04,5.546913e+04,55.469131,36.249138,9.062284e+05,9.062284e+05,906.228447,NaN,0,True,2.930781e+09,187570,6126.507614,2024.356537,451.320229,3063.253807,1012.178269,225.660115,NaN,True,NaN,887.765503,3.026398,4.485411,None,Rod,1775.531006,2.930781
2,3,LoF,59,True,False,z_max,351,0.003672,single_face,8150.0,10350.0,1200.0,117,849,544,165,1263,870,146.598830,1063.129151,667.120854,95578,6.473673e+06,2.531708e+06,11902.686061,-0.238092,0.966323,0.097635,0.971166,0.238129,...,25.000000,11.873251,2.968313e+05,2.968313e+05,296.831274,1.000000,2.500000e+04,2.500000e+04,25.000000,NaN,0,True,1.493406e+09,95578,4738.057050,2963.000159,203.164293,2369.028525,1481.500080,101.582147,NaN,True,NaN,709.081985,1.599074,14.584256,None,Ellipsoidal,1418.163970,1.493406
3,4,LoF,5,False,True,,0,0.000000,internal,18175.0,18425.0,375.0,42,1527,516,57,2264,1243,48.807093,1869.729650,885.432494,92029,3.980860e+07,1.086779e+06,2459.138079,-0.704915,0.709291,-0.000675,0.709210,0.704820,...,300.000000,143.897034,3.597426e+06,3.597426e+06,3597.425842,64.505814,1.612645e+06,1.612645e+06,1612.645340,NaN,0,True,1.437953e+09,92029,12835.722083,2120.813666,100.884231,6417.861041,1060.406833,50.442116,NaN,True,NaN,700.194519,6.052263,21.022251,None,Rod,1400.389037,1.437953
4,5,LoF,17,False,True,,0,0.000000,internal,12675.0,11775.0,350.0,42,522,839,56,993,1346,49.398444,825.872401,1083.061671,79178,1.415571e+07,2.492787e+06,2138.348169,-0.761828,0.647777,-0.001505,0.647758,0.761820,...,106.066012,160.745178,4.018629e+06,4.018629e+06,4018.629456,155.614914,3.890373e+06,3.890373e+06,3890.372849,3.052527e+07,69456,False,1.237156e+09,79178,7708.891485,3234.958179,94.746970,3854.445742,1617.479090,47.373485,44.424739,False,0.182575,665.955661,2.382996,34.143131,Complex,Ellipsoidal,1331.911321,1.237156

                            count          mean            std        min           25%           50%           75%           max
label                     73040.0  36520.500000   21084.976168   1.000000  18260.750000  36520.500000  54780.250000  7.304000e+04
ranking                   73040.0      6.184625      62.296020   0.000000      0.000000      0.000000      0.000000  9.500000e+02
border_touch_voxel_count  73040.0      0.115225      12.087473   0.000000      0.000000      0.000000      0.000000  2.132000e+03
border_touch_fraction     73040.0      0.000219       0.010535   0.000000      0.000000      0.000000      0.000000  9.748430e-01
BoundingBox_Dx (µm)       73040.0    141.221591     252.491240  50.000000    100.000000    125.000000    150.000000  1.817500e+04
...                           ...           ...            ...        ...           ...           ...           ...           ...
Equivalent Radius (µm)    73040.0     39.317609      24.648960  32.259526     33.412615     35.506202     38.247897  9.090692e+02
elong_axis_ratio          73040.0      2.281828       1.575862   1.000000      1.554961      1.977371      2.570304  5.522646e+01
flat_axis_ratio           73035.0   5984.592140  699652.355138   1.000000      1.523264      1.903669      2.444272  9.782474e+07
Equivalent Diameter (µm)  73040.0     78.635219      49.297921  64.519051     66.825231     71.012404     76.495794  1.818138e+03
Volume3D (mm³)            73040.0      0.001245       0.023458   0.000141      0.000156      0.000188      0.000234  3.146875e+00

[125 rows x 8 columns]

73,040 pores x 134 columns
status               ok
group
Border                6
Classification        4
Complexity            2
Distance to surface  12
Ellipsoid            30
Feret                 4
Orientation           6
Position             12
Size                  5
Surface               4
Tensor shape         34

Empty DataFrame
Columns: [group, column, status, n_nan]
Index: []

columns present but not in the spec groups: ['label', 'Elongation', 'Flatness', 'Anisotropy', 'elongation_avg', 'flatness_avg', 'Inertia_Ixx (µm²)', 'Inertia_Ixy (µm²)', 'Inertia_Ixz (µm²)', 'Inertia_Iyy (µm²)', 'Inertia_Iyz (µm²)', 'Inertia_Izz (µm²)', 'elong_axis_ratio', 'flat_axis_ratio', 'Volume3D (mm³)']

columns with NaNs: 18

                                   n_nan        pct
shape_class                        50808  69.561884
cpx_factor                         50808  69.561884
Cov_Phi (degrees)                     15   0.020537
Cov_Theta (degrees)                   15   0.020537
Phi (degrees)                         15   0.020537
Theta (degrees)                       15   0.020537
flatness_avg                           5   0.006846
Ellipsoid_Semi_Axis_2 (µm)             5   0.006846
flat_axis_ratio                        5   0.006846
Ellipsoid_Semi_Axis_3 (µm)             5   0.006846
Ellipsoid_Minor_Axis_Length (µm)       5   0.006846
Ellipsoid_Semi_Axis_1 (µm)             5   0.006846
Cov_flatness_avg                       5   0.006846
Ellipsoid_Medium_Axis_Length (µm)      5   0.006846
Ellipsoid_Major_Axis_Length (µm)       5   0.006846
shape_class_no_cpx                     5   0.006846
Sphericity                             4   0.005476
Area3D (µm²)                           4   0.005476

Area3D_capped: 4 of 73040 pores capped
cpx_factor_capped: 6 of 73040 pores capped

                                                check  max_rel_err  passed
0      Volume3D (µm³) == volume_voxels·(res_nm/1000)³          0.0    True
1                         num_pixels == volume_voxels          0.0    True
2             Equivalent Radius (µm) == (3V/4π)^(1/3)          0.0    True
3       shortest_distance_to_surface_um == vox·res_um          0.0    True
4   shortest_distance_to_surface (legacy) == vox·r...          0.0    True
5       shortest_distance_to_surface_nm == vox·res_nm          0.0    True
6           mean_distance_to_surface_um == vox·res_um          0.0    True
7   mean_distance_to_surface (legacy) == vox·res_n...          0.0    True
8           mean_distance_to_surface_nm == vox·res_nm          0.0    True
9       centroid_distance_to_surface_um == vox·res_um          0.0    True
10  centroid_distance_to_surface (legacy) == vox·r...          0.0    True
11      centroid_distance_to_surface_nm == vox·res_nm          0.0    True

ALL UNIT CHECKS PASSED  (volume in µm³, legacy distance columns in nm, *_um in µm, *_vox in voxels)

                                   value
voxel_size_um               2.500000e+01
box_voxels                  8.482008e+08
box_volume_mm3              1.325314e+04
material_voxels             8.180656e+08
material_volume_mm3         1.278228e+04
defect_count                7.304000e+04
porosity_pct                7.115509e-01
porosity_box_pct            6.862706e-01
porosity_internal_only_pct  6.334829e-01
defect_density_per_mm3      5.714163e+00
total_defect_volume_um3     9.095239e+10
total_defect_volume_mm3     9.095239e+01
largest_volume_um3          3.146875e+09
largest_eq_diameter_um      1.818138e+03
median_eq_diameter_um       7.101240e+01
pore_voxels_in_table        5.820953e+06
pore_voxels_in_volume       5.820953e+06
n_boundary_touching         6.600000e+01
n_area_capped               4.000000e+00
n_cpx_capped                6.000000e+00

counts_by_type {'Pore': 72047, 'LoF': 950, 'Border': 43}
counts_by_shape_class {'None': 50808, 'Complex': 22189, 'Ellipsoidal': 32, 'Disc': 9, 'Spherical': 2}
counts_by_shape_class_no_cpx {'Ellipsoidal': 48564, 'Disc': 13652, 'Rod': 10786, 'Spherical': 33, 'None': 5}
counts_by_border_class {'internal': 72974, 'single_face': 64, 'edge': 2}

pore voxels in volume − in table = 0  (non-zero only if MIN_SIZE/MAX_SIZE filtering removed pores)
Cov_Elongation/Cov_Flatness <= 0 (numerically degenerate, no shape class): 5; NaN: 0
Sphericity > 1 (voxelised area of tiny pores): 7205; pores with <= 1 voxel: 0  (use MIN_SIZE_VOXELS to drop them)

/tmp/ipykernel_2127584/872339919.py:256: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  if SHOW_PLOTS: plt.show()
/tmp/ipykernel_2127584/872339919.py:256: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  if SHOW_PLOTS: plt.show()
slices z: 100%|██████████| 165/165 [00:03<00:00, 42.70it/s]
slices y: 100%|██████████| 3227/3227 [00:03<00:00, 809.09it/s]
slices x: 100%|██████████| 1593/1593 [00:10<00:00, 147.29it/s]

{'z': {'mean_pct': 0.7107273688154156, 'max_pct': 3.8811220043310004}, 'y': {'mean_pct': 0.7112214219812912, 'max_pct': 2.1819409393873275}, 'x': {'mean_pct': 1.0307172809255258, 'max_pct': 99.67058823529412}}
written to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/12/onlypores files/pore_analysis
   figures/hist_phi_theta.png
   figures/hist_volume_diameter_sphericity_elongation.png
   figures/porosity_profile_slices.png
   figures/porosity_vs_z_slabs.png
   figures/projection_z.png
   figures/scatter_volume_sphericity_by_type.png
   pores.csv
   pores.parquet
   pores_raw.key.json
   pores_raw.parquet
   run_config.json
   slice_profile_x.csv
   slice_profile_x.key.json
   slice_profile_y.csv
   slice_profile_y.key.json
   slice_profile_z.csv
   slice_profile_z.key.json
   specimen_summary.json

## 5. Batch summary

In [7]:
BATCH = pd.DataFrame(RESULTS)
if BATCH_SUMMARY_PATH: _bp = Path(BATCH_SUMMARY_PATH)
else: _bp = Path(JOBS[0]["out"]).parent / "pore_analysis_batch_summary.csv" if JOBS else Path(FOLDERS[0]) / "pore_analysis_batch_summary.csv"
if len(BATCH):
    BATCH.to_csv(_bp, index=False); print("batch summary written to", _bp)
    _cols = [c for c in ("name", "status", "elapsed_s", "voxel_size_um", "defect_count", "porosity_pct", "porosity_internal_only_pct",
                         "defect_density_per_mm3", "largest_eq_diameter_um", "median_eq_diameter_um") if c in BATCH.columns]
    _display(BATCH[_cols])
n_bad = int((~BATCH["status"].eq("ok")).sum()) if len(BATCH) else 0
print(f"{len(BATCH) - n_bad} ok, {n_bad} failed/skipped")

batch summary written to /home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/02_XCT_data/Juan Ignacio/probetas/4/onlypores files/pore_analysis_batch_summary.csv

                        name status  elapsed_s  voxel_size_um  defect_count  porosity_pct  porosity_internal_only_pct  defect_density_per_mm3  largest_eq_diameter_um  median_eq_diameter_um
0  volume_eq_rotated_aligned     ok       92.3           25.0          2770      0.746433                    0.677690                0.227686             1590.657852             196.692226
1  volume_eq_rotated_aligned     ok       90.6           25.0          4723      0.895458                    0.894053                0.380227             1826.063127             155.910384
2          volume_eq_aligned     ok       85.3           25.0          2023      0.533916                    0.514368                0.158091             1924.433114             140.024193
3          volume_eq_aligned     ok       92.6           25.0          4930      1.074017                    1.038115                0.389471             2057.869251             169.780738
4          volume_eq_aligned     ok      415.3           25.0        145691      0.819737                    0.739496               11.560417             2109.325819              71.012404
5          volume_eq_aligned     ok      427.6           25.0        149488      0.865254                    0.796037               11.593234             2055.468223              71.012404
6          volume_eq_aligned     ok      244.8           25.0         73040      0.711551                    0.633483                5.714163             1818.138472              71.012404

7 ok, 0 failed/skipped

## 6. How to reuse

1. Edit only the **Parameters** cell: list the specimen folders in `FOLDERS` and set `VOXEL_SIZE_MM` (default) / `VOXEL_SIZE_OVERRIDES` (per specimen). Use the `defect-atlas` kernel.
2. *Run All*. Each folder is searched recursively for `*_onlypores.tif` + the matching `*_samplemask.tif`; folders with no pair, or a missing mask, are reported and skipped. A failure in one specimen is logged and the loop continues (`STOP_ON_ERROR=True` to abort instead).
3. Outputs per specimen in `<pores folder>/pore_analysis/` (or `pore_analysis_<prefix>/` if a folder holds several volumes): `pores.csv/.parquet`, `specimen_summary.json`, `slice_profile_*.csv`, `figures/*.png`, `run_config.json`, `_raw/`. Across specimens: `pore_analysis_batch_summary.csv`.
4. Re-runs are cheap (per-specimen cache, same invalidation rules as before; `USE_CACHE=False` forces a rerun). `SHOW_PLOTS=False` saves figures without rendering them inline.
5. Units: volumes µm³, lengths µm, `*_distance_to_surface` (no suffix) in **nm**, `*_vox` in voxels, `centroid-*`/`bbox-*` in voxels `(z, y, x)`.
6. Caveats unchanged: `shape_class` is dominated by the `cpx_factor` override — prefer `shape_class_no_cpx`; tiny pores can give NaN covariance ratios / Sphericity > 1 (`MIN_SIZE_VOXELS`). The notebook never writes inside the Defect Atlas repo.